### ISSUE TITLE
[Localization] Missing strings

### ISSUE THREAD

**Issue by Satton2** [TTT-2/TTT2#1008]
1. Test Popup. (**gamemodes\terrortown\gamemode\client\cl_eventpopup.lua**)
Lines: 10, 13.
![Desktop Screenshot 2022 12 30 - 17 22 15 90](https://user-images.githubusercontent.com/23385240/210080372-c679d090-0fef-4cbd-9159-efecfe41a7e6.png)

2. Chat messages. (**gamemodes\terrortown\gamemode\client\cl_hud_editor.lua**)
Lines: 268, 269, 270, 271.
![Desktop Screenshot 2022 12 30 - 17 23 03 45](https://user-images.githubusercontent.com/23385240/210080573-4dedf403-9180-4a09-8c04-575234b2930c.png)

3. "Nothing here yet" in 'Guide' menu:
**lua\terrortown\menus\gamemode\guide\equipment.lua** Lines: 11, 18.
**lua\terrortown\menus\gamemode\guide\gameplay.lua** Lines: 12, 19.
**lua\terrortown\menus\gamemode\guide\roles.lua** Lines: 12, 19.
![Desktop Screenshot 2022 12 30 - 17 28 02 90](https://user-images.githubusercontent.com/23385240/210080963-3b7a9d86-f896-4616-a9a1-53279edb52b6.png)

4. TTT2's scoreboard tooltips (**gamemodes\terrortown\gamemode\client\vgui\cl_sb_row.lua**)
Lines: 158, 164, 170, 176, 182, 188 (hm?), 208.
![Desktop Screenshot 2022 12 30 - 17 37 34 91](https://user-images.githubusercontent.com/23385240/210082230-b7a76689-3f09-470b-b264-5ea258e154de.png)

5. Warnings and notifications? (**gamemodes\terrortown\gamemode\server\sv_main.lua**)
Lines: plenty. Especially, 357, 363.
— Found them accidently, but I like to have all the notifications and warnings (even the initializational ones) to be localized. Gimme the fully localized addon! :3

6. Traitor buttons description. (**lua\ttt2\libraries\targetid.lua**)
Lines: 241.
![Desktop Screenshot 2022 12 30 - 17 52 26 98](https://user-images.githubusercontent.com/23385240/210083296-2f61a1c6-f54e-4dbc-9012-3a6b46c0e86e.png)
There is also team names that are not translated but I currently didn't find the line.

That's it. I might add them by myself but I didn't learn how to do that, so if someone would like to teach me for futher cases I will be glad to.

**Comment by EntranceJew** [comment]
This seems like it's solved.

**Comment by TimGoll** [comment]
> This seems like it's solved.

not sure though. Not all of them are translatable. But at least the chat print should be removed at some point anyway. So I'm not sure what is left missing right now
