### ISSUE TITLE
Round beginning role distribution broken when players disconnect

### ISSUE THREAD

**Issue by BDJslime-UnaverageJoe** [TTT-2/TTT2#1009]
## Your version of TTT2 (mandatory)

v0.11.6b (Workshop)

## Describe the bug (mandatory)

On end of round scoreboard, viewing the role distribution of round beginning will be broken should any players of the round leave during it.

## To reproduce

Steps to reproduce the behaviour:

1. Have multiple players/bots before round begins.
2. Remove a player/bot by kicking/diconnecting during the round.
3. Trigger round end.
4. Clicking Round Begin tab will show broken scoreboard and trigger lua error

## Expected behaviour

Round begin tab should show scoreboard as normal and with the expected score/karma the disconnected player/bot should get.

## Context (please provide as much as you can)

![20221230115749_1](https://user-images.githubusercontent.com/77141332/210109283-6207e3d1-2754-44a3-8b55-cf1a28732243.jpg)
![20221230115800_1](https://user-images.githubusercontent.com/77141332/210109286-9959f6b0-6801-4b17-8faf-8b0aa3c6c021.jpg)

**Comment by NickCloudAT** [comment]
Will push a PR for this soon.

The error only occurs if a player quits in an active round with no scoring event triggered. This will result in "eventdata.GetPlayerScores()" not containing this player and will produce an error for "MakePlayerScoreTooltip" as the table "plyScores" will not exists.
