### ISSUE TITLE
bot spectators tend to wander very far away from the map, creating log noise and instability

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1043]
## Your version of TTT2 (mandatory)

- Workshop version from Steam

## Video

![image](https://github.com/TTT-2/TTT2/assets/5711436/a518fd15-393d-4cc5-921d-987ed83d0a21)

## Describe the bug (mandatory)

Basic bots that are added as spectator have a tendency to wander far outside the reasonable realm of the map, and flood consoles with print messages, potentially resulting in long term instability for the server.

## To reproduce

Steps to reproduce the behaviour:

1. Open a game with 3 bots.
2. Kill them.
3. Prevent the round from starting / nextmap from happening.
4. Bots will wander as invisible gheists into parts unknown.

## Expected behaviour

I know a typical Source Bot isn't the direct responsibility of the gamemode, but because they are useful for stress testing other facets of the game mode, they may continue to provide bogus input as a spectator for the purposes of testing other things.

But potentially special handling code be added to warp them back to points of interest, or cycle spectators, rather than let them float away outside the engine's limitations and flood the console or stop simulating inputs entirely.

## Context (please provide as much as you can)

- see above

**Comment by Histalek** [comment]
Depending on your testing needs, setting `bot_zombie` to 1 will disable all bot ai for all bots always, regardless this definitely a good idea.

I don't know if there is a possibility to disable the AI on a specific bot more elegantly but my naive workaround would be to check :IsBot() on player death and then call :Lock() [2] on the bots. On respawn we can :UnLock() [3] them again.

[1] https://wiki.facepunch.com/gmod/Player:IsBot
[2] https://wiki.facepunch.com/gmod/Player:Lock
[3] https://wiki.facepunch.com/gmod/Player:UnLock
