### ISSUE TITLE
[Equipment Editor] Explain Damage scaling

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/TTT2#1059]
After I came back from my hiatus I noticed this new damage scaling variable. It should probably have a small helptext that explains it, especially since the value seems so arbitrary? Or is just me?

![image](https://github.com/TTT-2/TTT2/assets/13639408/4a9a6a1f-b109-43c9-a704-b8c29817d752)

Reference: https://github.com/TTT-2/TTT2/pull/1040

**Comment by EntranceJew** [comment]
Definitely, I was going to come back to this with other changes such as the default amount of shots available (the leading cause in people reuploading existing addons). Was trying to draw a line between making the weapon base a full blown weapon editor.

The description for this would have to come with the note that certain weapons obviously don't use primary/secondary damage, FireBullets, etc and I wasn't certain how much of that was relevant to the user.

**Comment by TimGoll** [comment]
> Was trying to draw a line between making the weapon base a full blown weapon editor.

There is still a "implement a weapon editor into TTT2" note on our todo list. We actually did want to implement something like this. This is the reason why we implemented all the synced database stuff.

> I wasn't certain how much of that was relevant to the user.

You should probably write something like: `Note: Some weapons might not use this value which causes this modifier to be ineffective`
