### ISSUE TITLE
[UI] - Corpse Identifcation Hud

### ISSUE THREAD

**Issue by Gensokian** [TTT-2/TTT2#1061]
This is an Issue to collect the Ideas and track the progress of the Corpse Identification HUD element

**Comment by TimGoll** [comment]
Later today I will search through messages and docs to post my ideas here

**Comment by TimGoll** [comment]
## Old Mockup:
![image](https://github.com/TTT-2/TTT2/assets/13639408/b9349318-94f2-405b-83a4-b25730ef282d)

The new body search should be completely overhauled. The design shown in this image is by no means final, it is actually pretty bad. But it is a placeholder to start woking with.

## Think I'd like to add:
- a rendering of the player's head as shown in the screenshot
- information about the ground surface where the player died

## Things that should be reworked:
- everything should be "dynamic", if someone else confirms the body, the button should update its state
- the information about the weapon, the time etc should be easier to understand

## Thinks I'd like to keep
- everything important should be visible on first glance. If we add tabs like in the mockup, these should only be used for unimportant information

## General confirm changes:
Right now there are also these two convars `ttt2_inspect_detective_only` and `ttt2_confirm_detective_only`. They should be replaced by a new system. This was already discussed on discord with a nice solution, but I'm unable to find it right now.

### related:
- https://github.com/TTT-2/TTT2/issues/596
- https://github.com/TTT-2/TTT2/issues/1013
