### ISSUE TITLE
Language selection error

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/TTT2#1068]
## Your version of TTT2 (mandatory)

- Workshop version from Steam

## Describe the bug (mandatory)

If you switch the language in the F1 menu to another language and then switch back to another language you will receive the following error in the console:
[TTT2 (Base) - v0.11.7b] lua/includes/modules/cvars.lua:48: attempt to call local 'callback' (a nil value)
  1. unknown - lua/includes/modules/cvars.lua:48
   2. SetString - [C]:-1
    3. SetConVarValues - gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua:398
     4. ChooseOptionID - gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua:188
      5. ChooseOptionValue - gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua:197
       6. SetValue - gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua:336
        7. DoClick - gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua:307
         8. OnMouseReleased - lua/vgui/dlabel.lua:237
          9. unknown - lua/vgui/dmenuoption.lua:76

The language completion rate is also bugged.
For example English is 100 % complete then you change to another language and back to English and you will see something different like 81.7 % or 45.8 % ... .

## To reproduce

Steps to reproduce the behaviour:

1. Go to the F1 menu
2. Click on Language
3. Select a different language
4. Switch back to another language
5. See error and weird completion rate

## Expected behaviour

It should not create an error and the completion rate should be correct.

## Context (please provide as much as you can)

Tested with TTT2 Base, ULX, ULIB, ULX for TTT2 and some TTT2 roles installed.

**Comment by TimGoll** [comment]
yes, the language selection has a few minor bugs that we have to fix

**Comment by NickCloudAT** [comment]
Not sure if I'm correct, but it seems like the game can't keep track of the callback function created here: https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua#L343

If I take out those two line here:
https://github.com/TTT-2/TTT2/blob/master/lua/terrortown/menus/gamemode/language/language.lua#L31
https://github.com/TTT-2/TTT2/blob/master/lua/terrortown/menus/gamemode/language/language.lua#L32

The error disappears after changing the language once. It then only comes back if I go back one menu (so main menu) and then go into the language menu again and select a language. The error then only happens once though.

**Comment by NickCloudAT** [comment]
Soo.. after digging through it I'm now pretty sure that the game doesn't keep track of the functions correctly..
I made a "draft" in a branch which would fix both issues: https://github.com/NickCloudAT/TTT2/commit/752492aae0ba0aefcbc3a2144cbac76e4d6b805e

It still contains debug messages and is not fletched out though.. but works.

**Comment by Spanospy** [comment]
Adding a comment to say that this error message can be replicated with an addon's convar combobox!
