### ISSUE TITLE
Ideal karma

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#107]
Как вам идея улучшить карму? Если любая активная роль, чья цель убивать всех не закупался в C магазине, не разу не выстрелил из оружия, то есть из любого. И в него начинают стрелять просто так, то если его убьет человек(который начал стрелять просто так), у этого человека снимется карма, так-как он сделал рдм.
Так-как много ролей и срдмить убийц очень легко.

**Comment by Alf21** [comment]
Could you split the sentences without using as many commas? I couldn't understand what you try to say ^^

**Comment by dok441** [comment]
Обновил текст

**Comment by dok441** [comment]
Я же написал, что необходимо улучшить.

**Comment by Alf21** [comment]
Do you have an idea or formula to improve the karma system (focused on punishments)

**Comment by dok441** [comment]
Есть идея как раз связанная с наказанием, когда человек становится активной ролью, которая должна убивать, его награждают за убийства любого игрока, но это не правильно, так-как человек мог до этого rdm 5 человек, а потом стать активом и вернуть себе всю карму за 1 раунд и продолжать rdm дальше. Поэтому я хотел бы предложить убрать награду за убийства у активных ролей. Чтоб если ты rdm, то восстановить мог только играя и получая каждый раунд бонус кармы.

**Comment by Alf21** [comment]
That‘s a great suggestion. I will decrease the karma punishment for teamkilling from doubled into the standard one & implement your suggestion :)

Active roles will be e.g. Jackal, Serialkiller, Traitor,...
But what about Infected? What if you kill as zombie your host, that results in killing every other zombie?

**Comment by Alf21** [comment]
Please (re-)open your request with your idea of the infected teamkilling 
handling. :)

And tell me, whether you can cope with these new changes. Ty! Oh, and happy new Year :)

**Comment by dok441** [comment]
Я хотел уточнить, вы так и не сделали, что я предлагал на счет уберания наказание, если человек вам снес больше 30hp? К примеру: невиновный в невиновного стрельнул, снес 30hp, тот его убил и ему карму не убирают, так-как тот потенциальный RDM. Или же, предатель стреляет в hitman, предатель наносит 30 урона, hitman убивает его и ему не снимают карму.

**Comment by dok441** [comment]
Я увидел, что вы сделали умножитель кармы если убивают детектива, я думаю это не корректно. У меня стоит наказание за rdm невиновного 150, а если убивают детектива, там прилетает сразу бан за карму. Я думаю, необходимо поставить не умножитель, а просто прибавлять к текущему наказание 50 или 100 кармы за детектива.

**Comment by Alf21** [comment]
If you have a formula, I can include it. But I finally need a suggestion, there is no sense in modifying it all the time.
