### ISSUE TITLE
[Bomb Wallhack Renderer] Rework

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/TTT2#1088]
Rework the existing bomb UI that is used by C4 for example and make it an easy to use interface. It should use the TTT2 marks module, but also add some text/icons. The color should be team independant.

Reason: Addons such as the melon mine use this wallhack, but it is not that easy to understand:
![image](https://github.com/TTT-2/TTT2/assets/13639408/83bd6dac-95be-464a-997b-150a15e290e9)

**Comment by a7f3** [comment]
So just to confirm, we would be trying to replace the code in [RADAR:Draw()](https://github.com/TTT-2/TTT2/blob/master/lua/terrortown/entities/items/item_ttt_radar/cl_init.lua#L158C2-L169C5), which just shows a 2d image + text, and replace it with a 3d wallhack using Marks and adding some text?


Could always have a visible countdown overlayed on top of the wallhack and if you hovered (or pressed tab) you could see your distance and other info
![image](https://github.com/TTT-2/TTT2/assets/124642739/760b8779-ac03-4df9-9472-9163a3eb9699)
Little mockup I hacked together

**Comment by TimGoll** [comment]
yes, this is what I want to do, I already started coding it

**Comment by TimGoll** [comment]
See: https://github.com/TTT-2/TTT2/compare/master...bomb-vision
