### ISSUE TITLE
[Player Spectator] LMB inconsistency

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/TTT2#1092]
When observing a player the RMB cycles to the next player in the list. The LMP however sometimes does nothing, sometimes cycles back and sometimes jumps to a random player.

The LMB should cycle backwards through the player list

**Comment by mexikoedi** [comment]
Wasn't this always the case?
I remember that this was also in TTT1.
LMB chooses a random player while RMB the next player.

The code in TTT2 is here: 
https://github.com/TTT-2/TTT2/blob/4c0b98044d35125099e3652415abff5b3592ef61/gamemodes/terrortown/gamemode/server/sv_player.lua#L398

And the code in TTT1 is here: 
https://github.com/Facepunch/garrysmod/blob/e189f14c088298ca800136fcfcfaf5d8535b6648/garrysmod/gamemodes/terrortown/gamemode/player.lua#L318

Seems to me that's it working as intended or do you want to change this mechanic (just asking)?

**Comment by TimGoll** [comment]
Huh, but then the random is really bad. It did not felt random to me. And the fact, that the currenty spectated player is not removed from the list, makes it feel as if it is not working when you have to click multiple times to get a new candidate.

After I played lots of Rainbow I think it would be best to change it so that it cycles forwards / backwards. Don't you agree?

**Comment by mexikoedi** [comment]
Every game I played so far had also the forwards/backwards mechanic which makes more sense.
Or something similar like the use of the arrow keys.
I don't know why Gmod is different in this aspect.
So yes it would be better to change this.
(Maybe even suggesting it to the Gmod repo?)

**Comment by EntranceJew** [comment]
I think "reload" should be random instead, fwiw.

**Comment by mexikoedi** [comment]
> I think "reload" should be random instead, fwiw.

Or middle click on the mouse?

**Comment by TimGoll** [comment]
> > I think "reload" should be random instead, fwiw.
> 
> Or middle click on the mouse?

I'm not sure if middle mouse has a default bindings and many weapons already use reload. So I think reload is fitting here
