### ISSUE TITLE
[Feature] zm_carry ragpin as a role permission

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1100]
**Is your feature request related to a problem? Please describe.**
Not being able to find these config settings in the F1menu easily, tightly coupled to TTT's role system and doesn't embrace TTT2's changes.

**Describe the solution you'd like**
1. Remove the GlobalVars that control pinning ragdolls with the magneto stick
2. Move the toggle for it into the role submenu as a per-role convar the way the rest of the role permissions are set up.

**Describe alternatives you've considered**

**Additional context**
I plan on doing something like this during an integration of all of wget's equipment rework features, in which I ensure all the stock equipment:
- has a unique buymenu icon
- has proper TTT2HUDHintText defined
- has all relevant UI convars in the Edit Equipment menu rather than as variables strewn around
- removes all Remove in OnDrop limitations, has worldmodel, etc -- just allow them to be dropped on purpose

**Comment by TimGoll** [comment]
Just FYI, there is a convar for innocent pinning, that should probably be removed
