### ISSUE TITLE
Lua error on fast search entries

### ISSUE THREAD

**Issue by xopez** [TTT-2/TTT2#1158]
## Your version of TTT2 (mandatory)

- Workshop version from Steam (v0.11.7b)

## Video

https://www.youtube.com/watch?v=NEtx6_ADKiU

## Describe the bug (mandatory)

If searched to fast, I'll get a lua error.

Searched in the F1 menu and got a lua error on client side:

```
[TTT2 (Base) - v0.11.7b] gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua:86: attempt to call method 'SetValue' (a nil value)
  1. receiveFunc - gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua:86
   2. func - lua/ttt2/extensions/cvars.lua:161
    3. unknown - lua/includes/extensions/net.lua:38 (x3)
```
```
[TTT2 (Base) - v0.11.7b] gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua:271: attempt to call method 'SetValue' (a nil value)
  1. receiveFunc - gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua:271
   2. func - lua/ttt2/extensions/cvars.lua:161
    3. unknown - lua/includes/extensions/net.lua:38 (x2)
```

## To reproduce

Steps to reproduce the behaviour:

1. Go to submenu with search function
2. type something fast in the search menu
3. get lua error

## Expected behaviour

there should be no error happening, independent of typing speed

## Context (please provide as much as you can)

- Collection link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=600164891)

**Comment by TimGoll** [comment]
might be already fixed in v0.12. We will release the update in the coming week. Could you please test it after the release an report back?

**Comment by sbzlzh** [comment]
This bug is fixed in the GitHub version!

**Comment by xopez** [comment]
Sure I can test and thanks for the fast replies :)

**Comment by sbzlzh** [comment]
You can try using the GitHub version and see if that resolves it. I had the same problem as you before.

**Comment by TimGoll** [comment]
I'll close it as it is probably fixed on master. Please reopen if the issue persists after the 0.12 update. Thank you!

**Comment by xopez** [comment]
Thanks for uploading the new version to the workshop. I have tested it and the problem is fixed :)
