### ISSUE TITLE
Binoculars changing zoom level interrupts scan

### ISSUE THREAD

**Issue by a7f3** [TTT-2/TTT2#1160]
**Is your feature request related to a problem? Please describe.**
binoculars changing zoom level interrupts scan

**Describe the solution you'd like**
The scan should only be interrupted when the body is no longer focused

**Additional context**
![Binoculars](https://github.com/TTT-2/TTT2/assets/124642739/6823afaf-7e47-43ab-b8bb-209d61c26027)

**Comment by a7f3** [comment]
Would it be worth it to send a pr for upstream?

**Comment by TimGoll** [comment]
Probably almost no one will notice it. However if you fix it, we will really appreciate it
