### ISSUE TITLE
NULL Entity Client Error

### ISSUE THREAD

**Issue by thebigsleepjoe** [TTT-2/TTT2#1171]
## TTT2 Version

- Workshop version from Steam (v0.12.0b)

## Describe the bug (mandatory)

A clientside error is spammed in the console, often at seemingly random intervals. It does not occur outside of an active round, and only happens when the UI is rendering.

The stack trace is as follows:
```
[TTT2 (Base) - v0.12.0b] gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:46: Tried to use a NULL entity!
  1. Team - [C]:-1
   2. IsSpec - gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:46
    3. Draw - gamemodes/terrortown/gamemode/shared/hud_elements/tttminiscoreboard/pure_skin_miniscoreboard.lua:182
     4. DrawElemAndChildren - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:306
      5. DrawElemAndChildren - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:303
       6. Draw - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:332
        7. DrawHUD - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:18
         8. unknown - game modes/terror town/gamemode/client/cl_hud_manager.lua:45
```
## To reproduce

Steps to reproduce the behaviour:

1. Play the game with any significant number of players
2. Have a player leave the game at any point during the match. This seems to be best replicated when a player in the match that dies disconnects.
3. Sometimes the error will occur, depending on your luck.

## Expected behaviour

There should be no errors in console.

## Context (please provide as much as you can)

- I am playing with my TTT bots that I have been actively developing, and this error only began as of this recent TTT2 update. I have triple-and-quadruple-checked that my bots are not causing this error.
- I am not playing with any other addons.

## Anticipated source/resolution

It appears there is an unsafe player cache being maintained in pure_skin_miniscoreboard.lua at HUDELEMENT:Draw()

Within this code, the line 182 (`if not ply:IsSpec() and ply:WasRevivedAndConfirmed() then`) is throwing the error, presumably because ply is NULL. This error propagates up the chain until the Player meta's Team function finally throws this entity-invalid error.

I believe this can be resolved by checking if ply is NULL, or by having some form of active cache invalidation. For context, the players table is only updated every 0.1 seconds, so replicating this issue is admittedly difficult without a large number of players.

**Comment by sbzlzh** [comment]
It's exactly the same as your description, I used ulx to slay a bot after starting the round, and then the bot got the same error you got.

**Comment by TimGoll** [comment]
This seems to be tied to a player trying to search the body of a disconnected player if I'm not mistaken

**Comment by sbzlzh** [comment]
> This seems to be tied to a player trying to search the body of a disconnected player if I'm not mistaken

I seem to have solved it le

**Comment by TimGoll** [comment]
> > This seems to be tied to a player trying to search the body of a disconnected player if I'm not mistaken
> 
> I seem to have solved it le

what?

**Comment by sbzlzh** [comment]
> Member

I'm testing to see if it's solved :D
