### ISSUE TITLE
Bug: Missing Translation Dete Combobox

### ISSUE THREAD

**Issue by ZenBre4ker** [TTT-2/TTT2#1175]
Dete Mode Combox is missing translation
![grafik](https://github.com/TTT-2/TTT2/assets/72046466/0231ef3a-49ca-4913-bbe1-7237a4e30df7)

Has to be manually done, like in equipment editor:
![grafik](https://github.com/TTT-2/TTT2/assets/72046466/dab442d2-62a9-483c-b7c1-7c0bf23e03ea)

**Comment by TimGoll** [comment]
it is not really missing, but the dropdown has no per frame translation yet.
because we want to refactor this anyway in a coming rework, this can be fixed by adding a translation when creating the UI element
