### ISSUE TITLE
Bug: Missing 3D Render of own corpse as spec

### ISSUE THREAD

**Issue by ZenBre4ker** [TTT-2/TTT2#1177]
As spectator you cant see your own 3D Rendering
![grafik](https://github.com/TTT-2/TTT2/assets/72046466/b1b3bd5f-036d-4253-8963-c5146cf6136d)

**Comment by Histalek** [comment]
Does this also happen as other roles? especially as innocent?

**Comment by ZenBre4ker** [comment]
Also as innocent

![grafik](https://github.com/TTT-2/TTT2/assets/72046466/0ed213f2-ba53-4940-b3d7-21da3aac6f58)
