### ISSUE TITLE
Featurerequest: Prevent Friendly Fire

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/TTT2#1185]
_[Taken from SMORE]_

> Don't allow roles to hurt other people with the exact same role as themselves.
For example, to prevent Infected zombies from killing their companions or masters.

Would be a nice setting that should be disabled by default. My suggestion would be a global convar, not one per role, but I need feedback from the community / the dev team on this one

**Comment by Histalek** [comment]
i'm not sure if this is generally useful as it can't be applied to the three base roles ever.

Infected zombies are definitely an outlier for this usecase.

I don't think this should be done in the gamemode. Roles should take of this themselves if it would useful for them.

**Comment by TimGoll** [comment]
> i'm not sure if this is generally useful as it can't be applied to the three base roles ever.
> 
> Infected zombies are definitely an outlier for this usecase.
> 
> I don't think this should be done in the gamemode. Roles should take of this themselves if it would useful for them.

fair point, I have to gree with you here. I'll close this. If someone has a valid argument to keep it, then we can reopen it
