### ISSUE TITLE
Missing 'corpse_hint_inspect_limited_details' string translation

### ISSUE THREAD

**Issue by sbzlzh** [TTT-2/TTT2#1193]
![image](https://github.com/TTT-2/TTT2/assets/92261479/adfa4291-9b5c-40a1-9f4c-779d68fcb9ea)

**Comment by Racpy** [comment]
L.hud_health is another missing strings.

**Comment by sbzlzh** [comment]
> L.hud_health is another missing strings.

Can you take a screenshot so I can see it, I'm still not seeing where it comes up.

**Comment by Racpy** [comment]
This string is the killer's health displayed on the right after you die.

![5](https://github.com/TTT-2/TTT2/assets/59442552/ad19e765-5577-4b00-93bd-35b4a70ba2e2)

**Comment by sbzlzh** [comment]
> This string is the killer's health displayed on the right after you die.
> 
> ![5](https://private-user-images.githubusercontent.com/59442552/289970827-ad19e765-5577-4b00-93bd-35b4a70ba2e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDcxODYsIm5iZiI6MTcwMjQwNjg4NiwicGF0aCI6Ii81OTQ0MjU1Mi8yODk5NzA4MjctYWQxOWU3NjUtNTU3Ny00YjAwLTkzYmQtMzViNGE3MGJhMmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE4NDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNTRlMWRiYTk4NmQ0NGE0MDJkM2VhZGE3YjdlNmI5MDFhZDcxYWQ2NmNmYjIwZmU1Y2E4ODRmY2E2OGQ2YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u60Owd40Pw1IT9yNaix5al13JK78Q7-I4ltndUjMIdE)

This how I feel is a problem with another plugin and doesn't seem to be missing from TTT2 itself. That would be a good question for @TimGoll

**Comment by sbzlzh** [comment]
> > > L.hud_health is another missing strings.
> > 
> > 
> > Can you take a screenshot so I can see it, I'm still not seeing where it comes up.
> 
> This string is the killer's health displayed on the right after you die.
> 
> ![5](https://private-user-images.githubusercontent.com/59442552/289970827-ad19e765-5577-4b00-93bd-35b4a70ba2e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDcyMjgsIm5iZiI6MTcwMjQwNjkyOCwicGF0aCI6Ii81OTQ0MjU1Mi8yODk5NzA4MjctYWQxOWU3NjUtNTU3Ny00YjAwLTkzYmQtMzViNGE3MGJhMmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE4NDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMzVkOWZlNDczMmI0YjliMjJmNTVmY2MwZmUxODVjOWI4ZDA2ODNhMmRkYjRkOGJiMGQ1OWFmZGVhMTIzOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BmxGeC_qISXwBMMTKrBZ0s-Vk5e0GZXn7uZS3nbNsHM)

That missing string you have is from this plugin: https://steamcommunity.com/sharedfiles/filedetails/?id=1367128301&searchtext=ttt2+Info

**Comment by TimGoll** [comment]
That's already fixed, restart your server once to get the update

**Comment by Racpy** [comment]
> That's already fixed, restart your server once to get the update @Racpy

Yeah, my bad, didn't notice there was a new update. Now the display is normal.

**Comment by TimGoll** [comment]
> > That's already fixed, restart your server once to get the update @Racpy
> 
> Yeah, my bad, didn't notice there was a new update. Now the display is normal.

No worries. This is on Gmod. If you restart your server while we are in the process of updating, you only receive some parts of the updates
