### ISSUE TITLE
Right click spectating behaves weirdly

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/TTT2#1209]
## Your version of TTT2 (mandatory)

- Workshop version from Steam

## Describe the bug (mandatory)

If you want to spectate someone and do right click (Secondary attack key) then nothing happens.
But if you do left click (Primary attack key) you will start spectating a player.
Everything else works as expected.

## To reproduce

Steps to reproduce the behaviour:

1. Spectate no one
2. Try to spectate a player by doing right click (Secondary attack)
3. Nothing happens
4. Try to spectate a player by doing left click (Primary attack)
5. It works as it should

## Expected behaviour

Right click (Secondary attack) should work like left click (Primary attack).
You should start spectating a player.

## Context (please provide as much as you can)

- Collection link: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195

**Comment by TimGoll** [comment]
Worked for me a few days ago. Are you sure no other addon messes with the inputs? We also only changed the leftclick action, the right click action stayed the same

**Comment by TimGoll** [comment]
Ah! I misunderstood your issue. As you can see in the keyhelper UI only one of these bindings can be used to select a random player.

I see no point why there should be two bindings that do the same. So this works as intended

**Comment by Spanospy** [comment]
If you're the coding type, feel free to have a go at making the spectator controls you envision!

(Actually, I might try this myself sometime.)

**Comment by mexikoedi** [comment]
Ah, I see it now.
Yes makes sense, I just saw the information about this on the bottom.
Ok, thanks.
