### ISSUE TITLE
killed player list (folder icon) not present on body search

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1211]
## Your version of TTT2 (mandatory)

Leave one of the following:

- Latest GitHub version

## Describe the bug (mandatory)

A list of players that a particular player killed is not present on their corpse.

## To reproduce

1. Watch a player kill someone.
2. Kill that player.
3. Inspect their body.
4. MSTACK confirms a player's death.
5. miniscoreboard shows gray X.
6. Inspected corpse will not list players they killed.

## Expected behavior

A list of players they killed is visible.

## Context (please provide as much as you can)

![image](https://github.com/TTT-2/TTT2/assets/5711436/8cc522ef-0b6c-4456-a0a3-8e8b26e7db89)

![image](https://github.com/TTT-2/TTT2/assets/5711436/6182c00e-a50a-4704-9699-488d619d6c11)

Happens as both traitor and detective.

## Additional context

This is a regression.

**Comment by TimGoll** [comment]
Weird. I'm pretty sure it worked last week when we played. But I will check it
