### ISSUE TITLE
confirmed bodies are acting like they're unconfirmed

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1213]
## Your version of TTT2 (mandatory)

- Latest GitHub version

## Describe the bug (mandatory)

Bodies that appear confirmed are not, or the other way around.

## To reproduce

Steps to reproduce the behaviour:

1. Kill someone
2. Inspect their corpse
3. Get prompted to confirm body
4. Confirm the body.
5. Look at the body.
6. Get prompted to confirm it again.

## Expected behavior

The body isn't confirmed until I press the button, or the UI reflects the body state accurately.

## Context (please provide as much as you can)

![image](https://github.com/TTT-2/TTT2/assets/5711436/b2652f36-2109-4685-af88-5f5a1443cf50)
![image](https://github.com/TTT-2/TTT2/assets/5711436/b5f5e7f4-c895-4bbd-9181-d7236d4c2f73)
![image](https://github.com/TTT-2/TTT2/assets/5711436/aa2e16a0-7642-4be4-a9f5-6778001842fa)
![image](https://github.com/TTT-2/TTT2/assets/5711436/e4fc9b83-1953-4762-bfcf-2cbf010099c6)
go back to the first picture here

## Additional context

The body appeared to have a name prior to inspecting it but the MSTACK still pushed as if I discovered it, and I was prompted to confirm it.

**Comment by TimGoll** [comment]
![image](https://github.com/TTT-2/TTT2/assets/13639408/4d5d0f59-0a1a-4782-8416-51c504def774)

I can't confirm this issue, it works for me. Maybe it is linked to another (already fixed?) issue?

**Comment by EntranceJew** [comment]
I checked it and in the time I'd be able to recreate it previously, it doesn't seem to be happening. one of the changes for #1232 must have fixed it

**Comment by TimGoll** [comment]
thanks for ivestigating this

**Comment by EntranceJew** [comment]
https://github.com/TTT-2/TTT2/assets/5711436/844ebdfc-ecee-408f-8152-1f5f72018f61

nevermind, i was wrong -- but i've narrowed it down to only happening to bodies whose names are recognizable from a distance. the bodies that I have recently created are identifiable. the targetid learns more, but the minihud doesn't.

https://github.com/TTT-2/TTT2/assets/5711436/662557c1-8428-4f19-871f-12ac8d8a9c7a

it may have something to do with the TTT-Bots that I'm testing with and the manual confirm mode, so i'm documenting this for the future's sake in case it does happen during a session
