### ISSUE TITLE
Can't open bodysearch

### ISSUE THREAD

**Issue by ChrisBkt** [TTT-2/TTT2#1230]
# Version of TTT2
Steam Workshop, Version from 12.12.2023
"Update: 12. Dec. at 12:54"

# Console Error
[TTT2 (Base) - v0.12.1b] lua/ttt2/libraries/bodysearch.lua:271: Tried to use a NULL CTakeDamageInfo!
  1. IsBulletDamage - [C]:-1
   2. AssimilateSceneData - lua/ttt2/libraries/bodysearch.lua:271
    3. ShowSearch - gamemodes/terrortown/gamemode/server/sv_corpse.lua:207
     4. unknown - gamemodes/terrortown/gamemode/server/sv_player.lua:544
      5. unknown - lua/includes/modules/concommand.lua:54
      
# Info
The error is caused when you kill someone with a weapon and try to search the body with "E"
When your cause of death is Fall Damage, there's no error and the body search will open

# Workshop List
https://steamcommunity.com/sharedfiles/filedetails/?id=2682937664

**Comment by TimGoll** [comment]
Do you know which weapon was used? Because with the weapons I tested this wasn't a problem

**Comment by ChrisBkt** [comment]
Actually currently every weapon on our server.
Just if you don't die with a weapon, you don't get this error.

**Comment by ChrisBkt** [comment]
Could you try it with the Crescent Rose?
https://steamcommunity.com/sharedfiles/filedetails/?id=684592258

There's also the error

And also every weapon we tried with the upper Workshop list

**Comment by ChrisBkt** [comment]
The only addons but these from the workshop is the Pointshop2 with it's libs

**Comment by TimGoll** [comment]
I will try to see if I can reproduce this. Because I tested it with so many different weapons without a problem

**Comment by TimGoll** [comment]
Ahhh, all weapons that overwrite stuff like the crowbar are likely to cause problems. Could you try to reproduce the issue if you remove that addon from the server?

**Comment by ChrisBkt** [comment]
Still the same problem with the default crowbar

**Comment by TimGoll** [comment]
Hmm, weird. I will take a look at the weapons in your collection tomorrow

**Comment by ChrisBkt** [comment]
Okay.
Also tried once again killing someone with crowbar and there's also the error. So it's also with the default weapons.

**Comment by EntranceJew** [comment]
The default crowbar raises this problem after the addon is removed, and the server and clients restart? If the problem is specifically an overwritten file the server needs to refresh without that.

**Comment by TimGoll** [comment]
It has to habe something to do with your collection because a few hours ago it worked for me

**Comment by ChrisBkt** [comment]
Yes server and client restarted.

**Comment by Spanospy** [comment]
Getting it with my collection too, though if an explosion killed multiple players at once, the error only occurs with (presumably) the first body.


https://steamcommunity.com/sharedfiles/filedetails/?id=2810383547

**Comment by BenitoTV** [comment]
Same here, the same collection as the days earlier, I changed nothing (added no addon to the collection/server). I get the exact same error:

[TTT2 (Base) - v0.12.1b] lua/ttt2/libraries/bodysearch.lua:271: Tried to use a NULL CTakeDamageInfo!
  1. IsBulletDamage - [C]:-1
   2. AssimilateSceneData - lua/ttt2/libraries/bodysearch.lua:271
    3. ShowSearch - gamemodes/terrortown/gamemode/server/sv_corpse.lua:207
     4. unknown - gamemodes/terrortown/gamemode/server/sv_player.lua:517

**Comment by EntranceJew** [comment]
I had this happen also, but the game didn't change anything and I'm not seeing a trace. I think the latest gmod update itself caused a problem?

the only addons that changed between my last reboot:
https://steamcommunity.com/sharedfiles/filedetails/?id=771487490
https://steamcommunity.com/sharedfiles/filedetails/?id=3100318253
https://steamcommunity.com/sharedfiles/filedetails/?id=3014777152

I believe the problem originates somewhere in: `CORPSE.Create` I'm still looking into it. It's clear `rag.dmgtype` is goofed.

**Comment by EntranceJew** [comment]
sampling of servers affected by running `version` in console:

my game client:
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 14:18:45 Dec 13 2023 (9033) (4000)
GMod version 2023.12.19, branch: x86-64, multicore: 1
Windows 64bit
```

affected server (hosted solution):
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 15:18:09 Dec 14 2023 (9040) (4000)
GMod version 2023.12.19, branch: unknown
Linux 32bit Dedicated Server
```

affected srcds64
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 14:18:45 Dec 13 2023 (9033) (4000)
GMod version 2023.12.19, branch: unknown
Windows 64bit Dedicated Server
```

unaffected server:
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 14:16:48 Dec 13 2023 (9033) (4000)
GMod version 2023.12.15, branch: unknown
Linux 64bit Dedicated Server
```
