### ISSUE TITLE
Don't show voice keys in UI if voice is disabled

### ISSUE THREAD

**Issue by xopez** [TTT-2/TTT2#1246]
## Describe the solution you'd like
The voice UI here shouldn't be shown if `sv_voiceenable` is set to zero
![Unbenannt](https://github.com/TTT-2/TTT2/assets/28950736/47fee69c-d29d-47e6-9096-33b379ff875c)

Also you shouldn't be able to cycle through the voice modes.

Since I don't think it's a bug I open it as a feature request. It would definitly be an enhancement.

**Comment by TimGoll** [comment]
That's correct and something I missed when adding the UI. Will be updated
