### ISSUE TITLE
Visualizer hint no longer using.

### ISSUE THREAD

**Issue by Racpy** [TTT-2/TTT2#1248]
## Your version of TTT2 (mandatory)

Workshop version from Steam ( v0.12.2b )

## Screenshot

![06](https://github.com/TTT-2/TTT2/assets/59442552/aaa8853e-e4fe-4217-8932-d22ad9cd0c78)
![07](https://github.com/TTT-2/TTT2/assets/59442552/37d62a19-0ebf-499a-99b5-c36e77cec755)

## Describe the bug (mandatory)

Visualizer hint now using `L.target_pickup`
e.g. The survivalist role mirror to detective shop. When the buyer throws it out, it cannot be picked up.
because "Visualizer" can only be picked up by the detective.

## Expected behaviour

Since a recent update changed the radio to only be picked up by the owner, I thought "Visualizer" could follow up with this update.

**Comment by TimGoll** [comment]
already fixed in #1198
