### ISSUE TITLE
Weapon position misalignment

### ISSUE THREAD

**Issue by Racpy** [TTT-2/TTT2#1252]
## Your version of TTT2 (mandatory)

Workshop version from Steam ( v0.12.2b )

## Video
1 and 2 are examples of problematic weapons.
[[1]](https://discord.com/channels/442107660955942932/547119387392475136/1188050917820465182)
[[2]](https://discord.com/channels/442107660955942932/547119387392475136/1188052156251648070)
3 seems unaffected
[[3]](https://discord.com/channels/442107660955942932/547119387392475136/1188053205955919912)

## Describe the bug (mandatory)

When switching weapons, some weapons vmodel will be misaligned, and some will only happen after shooting or reloading.

If turn off "Lower weapon when using ironsight", they will get confused when aiming.

## To reproduce

use CSS weapons for testing because TTT weapons mount by CSS, non-CSS weapons will also be affected.
1. Switch to TMP or USP-S
2. Check if vmodel pos and ang are normal
3. Check if ironsight pos and ang are normal after shooting or reloading

## Expected behaviour

This looks like a model problem, but try asking if it can be solved without modifying the model.

## Addons weapons

https://steamcommunity.com/sharedfiles/filedetails/?id=496383004

**Comment by EntranceJew** [comment]
![image](https://github.com/TTT-2/TTT2/assets/5711436/43d6b944-1e85-4f2a-9edf-06d8727737dc)
i asked around and the only real solution to this is if someone implements a "force play idle after inactivity" flag on the weapon's viewmodel for the affected CS:S weapons, and then it would be up to addon authors to utilize this flag for anything that uses a viewmodel for an affected weapon.

if the models and animations are authored like in addon content, honestly I think the workshop creators themselves should correct the animations where possible and not rely on this flag, only for things that continue to rely on mounted content.
