### ISSUE TITLE
[v0.12.2b] Sprinting doesn't work, floods console with errors

### ISSUE THREAD

**Issue by KyuuGryphon** [TTT-2/TTT2#1273]
## Your version of TTT2 (mandatory)

Latest Workshop build (v0.12.2b)

## Describe the bug (mandatory)

Loading up the current Steam Workshop version of TTT2 on a dedicated server (hosted on Windows 10) does not work properly - sprinting doesn't work, and the server console is constantly flooded with this error message:

> [TTT2 (Base) - v0.12.2b] gamemodes/terrortown/gamemode/shared/sh_sprint.lua:51: attempt to call method 'GetSprintStamina' (a nil value)
> 1. HandleStaminaCalculation - gamemodes/terrortown/gamemode/shared/sh_sprint.lua:51
> 2. unknown - gamemodes/terrortown/gamemode/shared/sh_main.lua:273

## To reproduce

1. Start a GMod Dedicated Server running TTT2 v0.12.2b - I don't know if it's important, but the server in question is being hosted from a Windows 10 machine.
2. Connect a client to the server. The console will start to flood with that error message, and the client won't be able to sprint.

## Context (please provide as much as you can)

- Server Collection: https://steamcommunity.com/sharedfiles/filedetails/?id=703984676 (note that the TTT2 base is missing right now, as I manually switched to v0.11.7b, which works correctly)
- The only non-Workshop addons installed are some weapon tweaks/additions, a voice chat tweak (allowing Jesters/Swappers and Traitors to hear each other), and a small mod that announces the presence of a Marker at the start of a round. None of them touch any of the sprint-related code.

**Comment by Spanospy** [comment]
Heyo,

Does this error occur if you remove all addons _except_ TTT2 v0.12.2b?

**Comment by Spanospy** [comment]
Did a bit of surface level digging: Any addon that overrides `gamemodes/terrortown/gamemode/sv_player.lua` will likely cause this error.

**Comment by KyuuGryphon** [comment]
Ahhh, that seems to be the cause, yeah. A server running just the Workshop version of TTT2 appears to work just fine, oops. It didn't even occur to me to check, given that the error was pointing at the TTT2 base itself. Sorry about that.

Thanks!
