### ISSUE TITLE
Incorrect language translation display

### ISSUE THREAD

**Issue by sbzlzh** [TTT-2/TTT2#1324]
![image](https://github.com/TTT-2/TTT2/assets/92261479/9cecb908-f1e7-4262-9148-6e4b39f2910b)
![image](https://github.com/TTT-2/TTT2/assets/92261479/d7cf0ac5-e14a-491a-84bb-89bbd3ff033b)

I found that switching to another language also has the same effect as in the picture.
This string translates to 'L.help_roles_builtin'

**Comment by TimGoll** [comment]
Did you add a translation for it? Because it isn't translated to German because there is no German translation. Only one of the two Chinese translations has a string for it:

![image](https://github.com/TTT-2/TTT2/assets/13639408/f7e35a5a-232a-4ca7-a7f8-25fa171f39c1)

**Comment by sbzlzh** [comment]
> Did you add a translation for it? Because it isn't translated to German because there is no German translation. Only one of the two Chinese translations has a string for it:
> 
> ![image](https://private-user-images.githubusercontent.com/13639408/301125605-f7e35a5a-232a-4ca7-a7f8-25fa171f39c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MzA4MjAsIm5iZiI6MTcwNjczMDUyMCwicGF0aCI6Ii8xMzYzOTQwOC8zMDExMjU2MDUtZjdlMzVhNWEtMjMyYS00Y2E3LWE3ZjgtMjVmYTE3MWYzOWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE5NDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYmNjNzU4M2E4OGVkNjFlMjk2YjJhMzhkMzU2NWZhN2ZhZDYxOGVlMGZlNzc5ZTk1YzMxZGY5ZjM0MzIzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6JfMQTSV00SCg6CnImzPEi8rgMlaN--oKQzjJ4yjz1Q)

It's okay, I'm using the GitHub version without the error in the picture. The picture shows the workshop version appearing so it doesn't have this translation. Problem solved.
