### ISSUE TITLE
Voice Chat Bug

### ISSUE THREAD

**Issue by cakety** [TTT-2/TTT2#1334]
TTT2 - v0.12.3b

One player is having an unreproducable issue with voice chat. 
Console shows following error whenever that player attempts to talk.

[ERROR] gamemodes/terrortown/gamemode/client/cl_voice.lua:499: bad argument #1 to 'SetVoiceVolumeScale' (number expected, got nil)
  1. SetVoiceVolumeScale - [C]:-1
   2. UpdatePlayerVoiceVolume - gamemodes/terrortown/gamemode/client/cl_voice.lua:499
    3. unknown - gamemodes/terrortown/gamemode/client/cl_voice.lua:176

All other players do not have this issue, and I have been unable to replicate it. 
Error continues when server is run with no other addons enabled. 
Player can use voice chat normally when base TTT is run instead.

**Comment by ZenBre4ker** [comment]
Could that person try to set the volume of other players and try again?

**Comment by cakety** [comment]
Causes a different error:

[ERROR] gamemodes/terrortown/gamemode/client/cl_voice.lua:499: bad argument #1 to 'SetVoiceVolumeScale' (number expected, got nil)
  1. SetVoiceVolumeScale - [C]:-1
   2. UpdatePlayerVoiceVolume - gamemodes/terrortown/gamemode/client/cl_voice.lua:499
    3. DoClick - gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua:337
     4. OnMouseReleased - lua/vgui/dlabel.lua:237
      5. unknown - lua/vgui/dimagebutton.lua:103

**Comment by EntranceJew** [comment]
that one should also be solved via #1335

**Comment by EntranceJew** [comment]
Are you playing a dedicated server?
Are you playing peer to peer?

Is the error in other client's consoles? Is the error in the server's console? What color is the error?

Is one of the players on LAN? Are they authorized on steam?
The system uses SteamID64 so multiple users on the same account may be impacted by this behavior.

It's very hard to pinpoint a cause without more information about how this is being played or getting that user's steamid64.

**Comment by cakety** [comment]
Dedicated server run from my machine.
Console log when player attempts to join, same errors are seen in their console, but is not seen by others in the server.
User's SteamID64 is 76561198177059830
![image](https://github.com/TTT-2/TTT2/assets/158010764/79609c81-d086-452e-aa7b-ff926237d469)

**Comment by TimGoll** [comment]
Since the voice UI is completely redone in 0.14.0 I will close this one. If anyone notices the bug reaapearing, please reopen it
