### ISSUE TITLE
Bodysearch: Local results overwrite policing results in the scoreboard

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1359]
## Your version of TTT2 (mandatory)

Leave one of the following:

- Latest GitHub version

## Describe the bug (mandatory)

corpses don't get marked as detective peeped

## To reproduce

1. Begin a round as an innocent.
2. Have a player kill another player.
3. Have any non-detective, non-you player check the body with instant-confirm enabled.
4. The corpse will display as confirmed.
5. Have a detective inspect the confirmed corpse.
6. The corpse will not show the "This body has been inspected by a public policing role" targetid info.
7. The scoreboard row for that corpse will not have been updated to show the magnifying glass to display corpse information.

## Expected behaviour

- The corpse shows the blue flare.
- The scoreboard is adequately updated.

## Context (please provide as much as you can)

- This might be mitigated by #1260, idk.
- If you **are** a detective, you will always observe this as functioning correctly -- because local search results still preside over publicly available knowledge. You must remain an innocent to see this occur.

**Comment by TimGoll** [comment]
It is working in the scoreboard, I'll check if it also works in targetID later today

**Comment by Histalek** [comment]
> ![image](https://private-user-images.githubusercontent.com/13639408/303846165-da75e922-2c19-4502-bd3e-c150edf1097d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODExNDUsIm5iZiI6MTcwNzU4MDg0NSwicGF0aCI6Ii8xMzYzOTQwOC8zMDM4NDYxNjUtZGE3NWU5MjItMmMxOS00NTAyLWJkM2UtYzE1MGVkZjEwOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE2MDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZWM0ODAzZjRhMWViM2I3MDEyNjZkYTIxY2E1ZDkwOTljMmVjYTQ5MDQ4ZDMyZjYxNjRmMjE5OGVlM2IyZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WItjB0vu5HpdUus5lN3SVKOFNt7FYmW6srXc1Fg_tWE)
> 
> I can not reproduce this issue, it works on my end. It was probably fixed "on accident" in another PR.

> If you are a detective, you will always observe this as functioning correctly -- because local search results still preside over publicly available knowledge. You must remain an innocent to see this occur.

how did you test this specifically?

**Comment by TimGoll** [comment]
> > ![image](https://private-user-images.githubusercontent.com/13639408/303846165-da75e922-2c19-4502-bd3e-c150edf1097d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODExNDUsIm5iZiI6MTcwNzU4MDg0NSwicGF0aCI6Ii8xMzYzOTQwOC8zMDM4NDYxNjUtZGE3NWU5MjItMmMxOS00NTAyLWJkM2UtYzE1MGVkZjEwOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE2MDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZWM0ODAzZjRhMWViM2I3MDEyNjZkYTIxY2E1ZDkwOTljMmVjYTQ5MDQ4ZDMyZjYxNjRmMjE5OGVlM2IyZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WItjB0vu5HpdUus5lN3SVKOFNt7FYmW6srXc1Fg_tWE)
> > I can not reproduce this issue, it works on my end. It was probably fixed "on accident" in another PR.
> 
> > If you are a detective, you will always observe this as functioning correctly -- because local search results still preside over publicly available knowledge. You must remain an innocent to see this occur.
> 
> how did you test this specifically?

I killed the player, set my role as dete, confirmed it and changed my role again

**Comment by Histalek** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/13639408/303846165-da75e922-2c19-4502-bd3e-c150edf1097d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODExNDUsIm5iZiI6MTcwNzU4MDg0NSwicGF0aCI6Ii8xMzYzOTQwOC8zMDM4NDYxNjUtZGE3NWU5MjItMmMxOS00NTAyLWJkM2UtYzE1MGVkZjEwOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE2MDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZWM0ODAzZjRhMWViM2I3MDEyNjZkYTIxY2E1ZDkwOTljMmVjYTQ5MDQ4ZDMyZjYxNjRmMjE5OGVlM2IyZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WItjB0vu5HpdUus5lN3SVKOFNt7FYmW6srXc1Fg_tWE)
> > > I can not reproduce this issue, it works on my end. It was probably fixed "on accident" in another PR.
> > 
> > 
> > > If you are a detective, you will always observe this as functioning correctly -- because local search results still preside over publicly available knowledge. You must remain an innocent to see this occur.
> > 
> > 
> > how did you test this specifically?
> 
> I killed the player, set my role as dete, confirmed it and changed my role again

so this is still an issue. Reopening.

**Comment by TimGoll** [comment]
![image](https://github.com/TTT-2/TTT2/assets/13639408/6cd4509f-024d-466f-8ccf-841662e65716)

no, it isn't. The workflow described in the issue produces the same. I tested this. Feel free to test yourself.

**Comment by Histalek** [comment]
This was not reproducible in our testsession.

Please reopen if you encounter this again.

**Comment by EntranceJew** [comment]
https://github.com/TTT-2/TTT2/assets/5711436/d5edee2e-4541-49f9-ab2f-4f0798c759c4
if i check a corpse a detective checked, then it overwrites it with my local results both on the corpse and on the scoreboard

**Comment by EntranceJew** [comment]
#reopen
