### ISSUE TITLE
SEARCHSCREEN:Show Passing Incorrect Raw Search Data to TTTBodySearchPopulate Hook

### ISSUE THREAD

**Issue by dhkatz** [TTT-2/TTT2#1376]
`SEARCHSCREEN:Show` is currently passing in bad data to the `TTTBodySearchPopulate` hook call.

It appears to actually be passing in Garry's Mod's own `search` module (evident by the `AddProvider` and `GetResults` methods available on the table)

https://github.com/TTT-2/TTT2/blob/6c02cda557f0a9f19f3652b0bbcae9f91afa73e4/gamemodes/terrortown/gamemode/client/cl_search.lua#L309

This seems to be because `search` isn't actually defined in this method. I assume the actual variable that is meant to be passed in here is `data`?

I don't think this issue has come up because not many addons actually listen to this hook, but ArcCW does and this is blocking a fix for TTT2 being written

**Comment by TimGoll** [comment]
Good catch, I will take a look at it!

**Comment by TimGoll** [comment]
Fixed, will be released in the next release probably this week
