### ISSUE TITLE
TTTOrderedEquipment seems to return the wrong IDs

### ISSUE THREAD

**Issue by saibotk** [TTT-2/TTT2#1383]
In #1290 we might have introduced changes that alter the behavior. This needs investigation.

As reported on Discord: https://discord.com/channels/442107660955942932/744888706338652170/1204961305279201330

My add-on Team Buy Notifications hooks into the `TTTOrderedEquipment` hook and then sends this info down to the client.
But after the recent changes on master it seems like some of the "No Status X" items all show up as the "No Drowning Damage" item.

@ZenBre4ker do you maybe have a clue? Otherwise, I'll take a look in the coming days.

**Comment by EntranceJew** [comment]
![image](https://github.com/TTT-2/TTT2/assets/5711436/06b5c345-e969-4d92-be7b-f9db3e1a4ac6)
for reference

**Comment by ZenBre4ker** [comment]
Actually looks quite good.
I printed the parameters of the hooks.
The old items with old id, still have that and where its not defined we have proper equipmentNames.

Upper ones are arguments of  TTTOrderedEquipment( ply, oldId, isItem )
Lower ones are arguments of TTT2OrderedEquipment( ply, equipmentName, isItem, credits, ignoreCost )

[TTT dev] Player [1][ZenBreaker] "item_ttt_noenergydmg" true
[TTT dev] Player [1][ZenBreaker] "item_ttt_noenergydmg" true 1 false

[TTT dev] Player [1][ZenBreaker] "item_ttt_speedrun" true
[TTT dev] Player [1][ZenBreaker] "item_ttt_speedrun" true 1 false

[TTT dev] Player [1][ZenBreaker] 2 true
[TTT dev] Player [1][ZenBreaker] "item_ttt_radar" true 1 false

[TTT dev] Player [1][ZenBreaker] "item_ttt_nofalldmg" true ""
[TTT dev] Player [1][ZenBreaker] "item_ttt_nofalldmg" true 1 false ""

[TTT dev] Player [1][ZenBreaker] "item_ttt_nopropdmg" true
[TTT dev] Player [1][ZenBreaker] "item_ttt_nopropdmg" true 1 false

[TTT dev] Player [1][ZenBreaker] "item_ttt_nodrowningdmg" true
[TTT dev] Player [1][ZenBreaker] "item_ttt_nodrowningdmg" true 1 false

[TTT dev] Player [1][ZenBreaker] 4 true
[TTT dev] Player [1][ZenBreaker] "item_ttt_disguiser" true 1 false

[TTT dev] Player [1][ZenBreaker] "item_ttt_noexplosiondmg" true
[TTT dev] Player [1][ZenBreaker] "item_ttt_noexplosiondmg" true 1 false

[TTT dev] Player [1][ZenBreaker] "item_ttt_nofiredmg" true
[TTT dev] Player [1][ZenBreaker] "item_ttt_nofiredmg" true 1 false

[TTT dev] Player [1][ZenBreaker] 1 true
[TTT dev] Player [1][ZenBreaker] "item_ttt_armor" true 1 false

**Comment by saibotk** [comment]
I need to test this, maybe it was broken before

**Comment by saibotk** [comment]
That would be very kind, thanks for checking!

**Comment by ZenBre4ker** [comment]
So it still seems to be the same with release 0.12.3b b6df5f1fcd75f822b211c00b9e754d6c86e85636
Looks like the same output and it only fails for items that use strings instead of numbers. Rest seems to work.

**Comment by saibotk** [comment]
Thanks for taking a look, i guess this can be closed then!
