### ISSUE TITLE
requestrevivalstatus is an expensive netmessage

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1386]
## Your version of TTT2 (mandatory)

- Latest GitHub version

## Video

![image](https://github.com/TTT-2/TTT2/assets/5711436/53996e6d-246a-47f7-b184-ce70b12ba304)
![image](https://github.com/TTT-2/TTT2/assets/5711436/e8ae290f-5dee-4cf4-b097-54ca4d5c5215)

## Describe the bug (mandatory)

requestrevivalstatus is an expensive netmessage

## To reproduce

1. Find a dead person
2. Try to revive them with a defib, or potentially other means
3. Produce 60 netmessages while this occurs.

## Expected behavior

The client doesn't produce so many netmessages.

## Context (please provide as much as you can)

- The code is probably firing in UI code or some trace/tick situation 
- While it isn't long-running or time consuming to process like `ttt2_net_stream`, it does still burden the server.
- It was a highly occurring message in proportion to the amount of times it was utilized during the playsession.

**Comment by EntranceJew** [comment]
![image](https://github.com/TTT-2/TTT2/assets/5711436/fa64f4e9-95d5-4f38-964f-13e1e8366e2e)
can you spot where i was holding a defib

**Comment by TimGoll** [comment]
A band-aid fix would be to limit the defi to send this request only once per second or so. I would still prefer to just have that value shared

**Comment by Histalek** [comment]
i'm somewhat inclined to agree with Tim on making this shared.

IIRC our last discussion about this ended up with the netmessage way because we wanted to prevent other players snooping on revives, but seeing the sheer amount of netmessages players could at least assume that someone is getting revived.

Maybe there is some middle ground to be found.

**Comment by TimGoll** [comment]
> i'm somewhat inclined to agree with Tim on making this shared.
> 
> IIRC our last discussion about this ended up with the netmessage way because we wanted to prevent other players snooping on revives, but seeing the sheer amount of netmessages players could at least assume that someone is getting revived.
> 
> Maybe there is some middle ground to be found.

The cleanest solution would probably be a polling in a good intrerval. But it is way more complex then a shared variable which would reduce the traffic a lot.

Because by polling the client has to request the data. If the server only updates the data when changed, then the traffic is vastly reduced

**Comment by saibotk** [comment]
I think this is not a direct issue for TTT2 but rather the defib repo.

Even though fixing this might also need some changes in TTT2. The defib only needs this for the TargetID, idk about the functionality and what it really does, like is this for other players to see that the corpse is being revived?
Sounds very niche if that is the case and id rather suggest removing this for now.

@TimGoll should we rather move this to the defib repo?

**Comment by TimGoll** [comment]
If we move this to the defi, we need the same custom systen for the marker and the necro.

I'm still in favor of changing this in TTT2

**Comment by saibotk** [comment]
TTT2 does not expose anything like this and i don't really see what you would "change"?
This is some custom functionality added by the defib alone. Just for displaying it in the target id.

**Comment by TimGoll** [comment]
TTT2 exposes the revival status on the server. I have three addons that need it on the client.

The best solution would be to have this exposed on the client as well. The other solution would be to implement a better custom syncing system in all three addons, which means I have to maintain in three times. Therefore I'd like to just use a shared variable on the player ent in TTT2. It is easy, vastly reduces net traffic ans pretty stable

**Comment by saibotk** [comment]
Do that no one is against that.
But you did not answer my question. What is this used for and in which context? Without this it is much harder to reason about possible solutions

**Comment by TimGoll** [comment]
I'm against implementing the same syncing code in three addons and maintaining it in three addons. So I don't know which solution noone is against

It is used to show the holder of the defi if they are able to use the defi on a player

**Comment by EntranceJew** [comment]
I think the base game should just handle it FWIW, it's not just the defib that could potentially break with a corpse being revived. For example, cannibalizing a swapper prior to respawning might break things. Cannibalizing a player killed by the infected could also break things prior to their respawn. There's a bunch of situations where authors should be able to consider a corpse "engaged". Fultoning a burnt coprse, cannibalizing a fultoned corpse, reviving a burning corpse, cannibalizing a burning corpse ...

**Comment by saibotk** [comment]
Coming back to this just now, @TimGoll, i think we can just make it shared as you first proposed. Sorry for somewhat blocking this some months ago :/ 

Just realized its much worse to have it like this than just trying to keep it serverside.
