### ISSUE TITLE
drawing changes negatively impact sniffer footprints

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1390]
## Your version of TTT2 (mandatory)

- Latest GitHub version

## Describe the bug (mandatory)

Footprints for the sniffer's lens will not be drawn.

## To reproduce

1. Procure a `Lens` or spawn as the Sniffer
2. right-click to look down the lens
3. wander around so that footprints should be documented
4. turn around and look at the floor, observe a lack of footprints

## Expected behavior

The sniffer's lens renders footprints

## Context (please provide as much as you can)

This worked prior to any rendering changes such as surface.Reset wherever it might be implemented

## Additional context

I didn't mention this to @WardenPotato yet, I forgot.

**Comment by TimGoll** [comment]
> This worked prior to any rendering changes such as surface.Reset wherever it might be implemented

But this is only called if there are arcs on the screen. Were there any in your test? If not, it can't be related to that change

**Comment by EntranceJew** [comment]
Any changes to anything running within "PostDrawTranslucentRenderables" could have affected this, including changes from 4 days ago to overhead role icons, beacons, it's hard to attribute due to the stylua run.

**Comment by TimGoll** [comment]
We couldn't reproduce this error in 0.14.0, as can be seen in this comment: https://github.com/TTT-2/ttt2-role_snif/pull/14#issuecomment-2366944779

If the issue persists, please reopen it.
