### ISSUE TITLE
players can alter each-other's desired FOV

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1391]
## Your version of TTT2 (mandatory)

- Latest GitHub version

## Describe the bug (mandatory)

All players can mess with each-other's desired FOV settings, or certain SWEPs can mess with something that it responds to, and alter the baseline FOV of every single player on the server.

## To reproduce

1. Join a game.
2. Disable `F1 > Gameplay > Accessibility > FOV punch`
3. `Esc > Options > Game > FOV`
4. Move the slider.
5. Hit `Apply`
6. Move the slider again.
7. Hit `Apply`
8. The new desired FOV will be sent to everyone.

## Expected behavior

A player's desired FOV remain exclusive to themselves.

## Context (please provide as much as you can)

this is what happens when you read a stranger's convar in the alps

## Additional context

Some combination of disabling FOV punch and enabling FOV punch plus the other things may be required but just going back and forth between the moving the slider phase and toggling the UI button should expose the issue.

**Comment by TimGoll** [comment]
Fixed in #1393
