### ISSUE TITLE
voice-chat volume indication

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1398]
## Is your feature request related to a problem? Please describe.
It is difficult to tell when audio is transmitting through local player's microphones.
It is difficult to tell when other people are holding the talk button or transmitting voice.

## Describe the solution you'd like
A FFT visualization (even if faked) of the voice volume activity.
![image](https://github.com/TTT-2/TTT2/assets/5711436/7be9d446-f4c9-4be0-8914-4d77fa5b35b2)
This gives several visual cues for the voice activity:
- Transparency continues to act as a cue for raw voice receive volume.
- A new FFT visualizer of some form indicates transmit and receive microphone volume, even if faked heavily.
- Never flatline, so that people can still keep their transmission ambiguous with proximity voice enabled. Simulate some low threshold of activity.
- Force FFT visualizer to indicate extremely low amplitude if distance is extremely great.

## Describe alternatives you've considered
semaphores

## Additional context
i wish gmod had a way to control proximity voice server-sided

**Comment by TimGoll** [comment]
Is there a FFT in GMod or would we need to use an external library for that?

Also I think this should be combined with moving this element to our HUD system first imho. One of the reason we didn't do it in the past was because of the player icon. But we have systems for that by now, so it would be easy to do

**Comment by TimGoll** [comment]
![image](https://github.com/TTT-2/TTT2/assets/13639408/cd254259-2098-4fce-92ee-63f4cd63fd91)

maybe the UI can also be a bit like this OBS discord plugin

**Comment by EntranceJew** [comment]
addons like these handle it, i recall seeing a million darkrp servers doing it, a FFT is pretty inexpensive, i handed off a lot of my old FFT code to the OSU! dev; but even these look simple:
https://github.com/SupinePandora43/VoiceVisualizer/tree/master
https://steamcommunity.com/sharedfiles/filedetails/?id=1825794230

**Comment by EntranceJew** [comment]
> maybe the UI can also be a bit like this OBS discord plugin

if that's what you like, Kuma's already got one: https://steamcommunity.com/sharedfiles/filedetails/?id=1469659378, but I personally find it easier to diagnose particular problems with my microphone with either meters or a waveform

**Comment by TimGoll** [comment]
> > maybe the UI can also be a bit like this OBS discord plugin
> 
> if that's what you like, Kuma's already got one: https://steamcommunity.com/sharedfiles/filedetails/?id=1469659378, but I personally find it easier to diagnose particular problems with my microphone with either meters or a waveform

I though about a nice looking element combined with your idea of the audio bars

**Comment by TimGoll** [comment]
This is done by now, TTT2 now has a voice indicator

**Comment by TimGoll** [comment]
Regarding the point of the distance: I have something different in mind for this. But probably not for the 0.14.0 major release.
