### ISSUE TITLE
add role debugger locking states to the base UI

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1399]
## Is your feature request related to a problem? Please describe.
i want to use and extend the [ROLE DEBUGGER](https://github.com/LukasMandok/ttt2-role_debugger) without causing additional problems with the base gamemode / overwrites

## Describe the solution you'd like
- add all the [UI features required for the ROLE DEBUGGER](https://github.com/LukasMandok/ttt2-role_debugger) into the base gamemode addon, so that it doesn't need to overwrite literally every single UX control in existence

## Describe alternatives you've considered
there's literally no other way forward with repairing this addon that doesn't involve diffing the root repositories where they originally diverged and rectifying things arduously by hand

## Additional context
it's so pretty and useful it just breaks TTT-Bots-2 and makes me miserable

**Comment by TimGoll** [comment]
I'm always a fan of adding more menu elements to the TTT2 base, so yes, this sounds good to me. We're specifically talking about [these](https://github.com/LukasMandok/ttt2-role_debugger/tree/main/lua/terrortown/gamemode/client/cl_vskin/vgui) elements. If @LukasMandok gives their ok here; I'd pull these files into TTT2 and clean them up so they fit our style

**Comment by LukasMandok** [comment]
Hey, by all means go for it. Maybe I should have made an effort to create some pull request at the time I did the addon.

**Comment by LukasMandok** [comment]
I guess I will have to look into it again, once you ported over those elements, to make the addon compatible with those.

**Comment by TimGoll** [comment]
The UI Part of this is done. Adding role features to TTT2 will be another todo, but this issue is finished
