### ISSUE TITLE
Spawning ttt_random_weapon after round start does not create a weapon

### ISSUE THREAD

**Issue by pontMakesThings** [TTT-2/TTT2#1406]
**TTT2 version:**
workshop v0.12.3b

**Description:**
Spawning ttt_random_weapon after the round has started does not spawn a weapon. 

**To reproduce:**
`ent_create ttt_random_weapon`, or spawn ttt_random_weapon via point_template. No weapon will spawn, and TTT2 Base will encounter a lua error.

**Expected behaviour:**
A random weapon spawns.

**Context:**
Spawning in random weapons and ammo after the initial round start is handy for maps with round variants and mid-round mechanics. I'm currently playtesting an in-development map that makes heavy use of this. ttt_random_weapon functions correctly in the original TTT. I have verified that random weapons are failing to spawn entirely, not just being misplaced. ttt_random_ammo works correctly.

**Relevant console readout:**
```
] ent_create ttt_random_weapon

[TTT2 (Base) - v0.12.3b] gamemodes/terrortown/entities/entities/ttt_random_weapon.lua:18: attempt to call field 'GetSpawnableSWEPs' (a nil value)
  1. unknown - gamemodes/terrortown/entities/entities/ttt_random_weapon.lua:18
```

**Map:**
While this is simple to create a test map for (or use any map where you know the origin), here's the map I'm working on where the bug is clearly observed between loading it in TTT and TTT2. A majority of weapons in the map are templated ttt_random_weapon. The origin is on the lower floor. Mind the round variant where it might fixed-spawn HUGEs everywhere.
https://steamcommunity.com/sharedfiles/filedetails/?id=3147823480

**Comment by EntranceJew** [comment]
have you checked out how these maps do it?
https://steamcommunity.com/sharedfiles/filedetails/?id=1326819008
https://steamcommunity.com/sharedfiles/filedetails/?id=1358920571

if you can help it, you should be using `entspawn.SpawnRandomWeapon` or `entspawn.SpawnRandomAmmo` within TTT2 -- but the source of ttt_random_weapon doesn't currently reference GetSpawnableSWEPs at all so i'm confused as to which addon you may have that is overwriting it
![image](https://github.com/TTT-2/TTT2/assets/5711436/ec614a4c-9791-4eef-9762-964a1cc4cf47)

can you run `which gamemodes/terrortown/entities/entities/ttt_random_weapon.lua` as a client to see where it originates from?

**Comment by pontMakesThings** [comment]
well, that's egg on my face - going back ingame it seems like it's working fine now. i guess gmod kept addon scripts cached as i disabled them while trying to figure out what was causing this. sorry about that, and thanks for the quick response! hope your night's going well. :)

**Comment by EntranceJew** [comment]
![image](https://github.com/TTT-2/TTT2/assets/5711436/888d7b84-c653-4cb5-a580-bf9faf3f843b)
i did check out the map, and did find an abundance of HUGEs, but I can't really say that's related to the SpawnRandomGun thing just yet, because there was a similar bug with the ammo function in an addon i made that prompted me to fix it and if that was broken then I feel like I would have noticed sooner, so definitely let me know if things don't behave because I like and want to support/facilitate dynamic maps :)

**Comment by TimGoll** [comment]
I want to chime in here and add that my testmap has mostly random weapon spawns and the weapon distribution is pretty balanced for me

**Comment by pontMakesThings** [comment]
have verified that the issue was caused by an addon script. some caching weirdness meant that the broken script was kept around after the addon was disabled and the map reloaded, but the console wrongfully pointed to ttt2 base in the error readout. sorry for the trouble, again! 😅

don't worry about the HUGEs, the map does that on purpose sometimes - i was just giving a heads-up in case it happened during any testing.

**Comment by TimGoll** [comment]
could you tell us which addon this is? so we can put it on the addonchecker

**Comment by pontMakesThings** [comment]
[here you go](https://steamcommunity.com/sharedfiles/filedetails/?id=2990353959). it was a weapon spawn ratio addon for the original TTT that'd been left in a server collection on accident after switching things over to TTT2.
