### ISSUE TITLE
Sqlite PRAGMA will return nil in the future

### ISSUE THREAD

**Issue by JustPlayerDE** [TTT-2/TTT2#1418]
## Your version of TTT2 (mandatory)

TTT2-0.12.3b (workshop)

## Describe the bug (mandatory)

Garrysmod will not support PRAGMA and will start to return `nil` in the future.
(currently only the dev branch is affected)

Affected files i found:

https://github.com/TTT-2/TTT2/blob/88849ec06924779df67abda37c0b6f5eb03e14f2/gamemodes/terrortown/gamemode/shared/sh_sql.lua#L251

https://github.com/TTT-2/TTT2/blob/88849ec06924779df67abda37c0b6f5eb03e14f2/lua/ttt2/extensions/sql.lua#L16-L72

This will cause a error like this:

```
[TTT2 (Base) - v0.12.3b] gamemodes/terrortown/gamemode/shared/sh_sql.lua:237: attempt to get length of local 'clmns' (a nil value)
  1. CreateSqlTable - gamemodes/terrortown/gamemode/shared/sh_sql.lua:237
   2. Register - lua/ttt2/libraries/database.lua:960
    3. OnLoaded - lua/ttt2/libraries/items.lua:115
     4. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:422
```

## Context (please provide as much as you can)

![image](https://github.com/TTT-2/TTT2/assets/19864478/497359e0-0cba-4fe8-81c2-2af1e74c4bfa)
(screenshot of next-update channel on the garrysmod discord)

**Comment by TimGoll** [comment]
probably something worth looking at @Histalek and @ZenBre4ker 

Maybe they should just delete Garry's Mod to fix the security issues!

Thanks for notifying us

**Comment by Histalek** [comment]
Thanks for noticing and notifying us!

I'll write down some thoughts on how we can remedy this.

Generally we need to figure out if this only happens for the `PRAGMA` statement or the whole functionality/access behind it. (Every `PRAGMA` statement can be achieved through a `SELECT` statement as far as i'm aware; it is most definitely the case for the `table_info` at least).

If the underlying information is still accessible to use through the use of a `SELECT` statement that would be the "easy fix" kinda way.

If not this get's a bit more complicated.

We can probably eliminate the first usage in `sh_sql.lua` completely. We'd probably want to do this anyway as we want to transition to database tables being controlled by our newly merged migrations #1300 .
Given the `-- @todo usage` existing for 5 years this was never properly documented especially the part about adding columns to an already existing table.
I would propose to remove the `else` block and deprecating the whole function now. Giving us some time to test migrations before removing the function completely.


The second occurrence in our `sql.lua` extension might be a bit more tricky. It should be possible to fix this without ripping out those functions, but i really do not want to parse `CREATE TABLE` statement for it... there are hopefully other ways of handling this.

**Comment by TimGoll** [comment]
thanks for keeping us posted!

If the discussions are not too long, it would be helpful to post them here as well. Especially for the future if someone might take a look at this issue in a year it is good to have everything in place.

**Comment by Histalek** [comment]
`table_info` will stay [1] so we are fine :)

Thanks again for getting the ball rolling on this one :heart: 

[1] ![2024-02-16_22-02-1708120219](https://github.com/TTT-2/TTT2/assets/16392835/ae5492b0-594d-4af8-a947-e24aad3df6e4) - [Discord message link](https://discord.com/channels/565105920414318602/589120351238225940/1208166849309708329)
