### ISSUE TITLE
PlaceableEntityBase: Movement with magneto stick possible

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/TTT2#1443]
![image](https://github.com/TTT-2/TTT2/assets/13639408/1e520722-65fb-45f3-8181-0ec5d324149f)

Aparently v0.13.0 broke the welding. I thought I implemented everything the same, but it seems like something is missing so that a magneto stick can move entities even when welded to the ground. This is true for every entity based on the placeable base.

**Comment by TimGoll** [comment]
It is likely due to this chang:

Old C4:
https://github.com/TTT-2/TTT2/blob/v0.12.3b/gamemodes/terrortown/entities/entities/ttt_c4/shared.lua#L170-L182

New Placeable Base:
https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/entities/entities/ttt_base_placeable.lua#L198-L205

But then again, just setting the mass seems weird. The magneto stick should probably check if the entity has motion enabled. What's your thought on this @EntranceJew? You recently reworked parts of the magneto stick.

**Comment by TimGoll** [comment]
Is the magneto stick respecting that flag?

**Comment by EntranceJew** [comment]
Yeah, the linked lines should still be in effect.

**Comment by TimGoll** [comment]
Did you add that line? or was it there previously? I'm asking because I want to know if it also works with lebroomers advanced magneto stick

**Comment by TimGoll** [comment]
thanks for checking! I guess I'll add a quick fix then and we can push it to 0.13.1 as well

**Comment by EntranceJew** [comment]
i do think carrying around armed C4 with a stick is funny if there were a way to break it off of a wall or something

![batman](https://media1.tenor.com/m/ctO_aPhejvIAAAAC/batman-bomb.gif)

something to visit in the future

**Comment by TimGoll** [comment]
You can still move the C4 with a magneto stick if it is not welded to a surface. Maybe it would be nice to have a way to rip welded items from surfaces?

**Comment by EntranceJew** [comment]
sounds like the mass isn't getting set, 'cause if C4 is setting itself to 150 mass then it shouldn't be moveable either

otherwise, i'm fine with that

**Comment by TimGoll** [comment]
> sounds like the mass isn't getting set, 'cause if C4 is setting itself to 150 mass then it shouldn't be moveable either
> 
> otherwise, i'm fine with that

In the 0.13 update I changed it so that it is welded when placing on a surface, not when activating. So the mass is set, but the weld function is not called when activating.

**Comment by EntranceJew** [comment]
> > sounds like the mass isn't getting set, 'cause if C4 is setting itself to 150 mass then it shouldn't be moveable either
> > otherwise, i'm fine with that
> 
> In the 0.13 update I changed it so that it is welded when placing on a surface, not when activating. So the mass is set, but the weld function is not called when activating.

right, but if something [weighs more than 45 then it shouldn't be able to be carried](https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua#L369) still, which is why i'm confused

**Comment by TimGoll** [comment]
Yes, but as weld is not called, the prop has a weight of 40
