### ISSUE TITLE
Map prop/entity pickups not working

### ISSUE THREAD

**Issue by Kowalski1700** [TTT-2/TTT2#1474]
## Versioning and issue
- Using workshop version
- Players are unable to pickup some map props

## The issue
On some maps, mainly one my community plays, players are unable to pickup the gold block or diamond ore on the common Minecraft map "ttt_minecraft_b5"

## To reproduce

1. Enable TTT2 and ttt_minecraft_b5.
2. Attempt to pickup gold block (spawns randomly on map) or pickup diamond ore with magneto stick.

## Expected behavior

The block/ore would be picked up and held by the magneto stick, allowing the player to enable core map functionality such as the traitor tester.
This was able to be achieved by disabling TTT2 and loading the map in TTT1.

## Context

Testing done in Singleplayer server (Start new game)
Issue arises with only 1 addon + map but the collection can be found [here](https://steamcommunity.com/sharedfiles/filedetails/?id=3169259228)

I couldn't find anyone else mentioning this issue so my apologies if it has been mentioned before.
Any help or recommendations are welcome. Thanks!

**Comment by TimGoll** [comment]
Thanks for reporting, we will look into it

**Comment by Histalek** [comment]
i haven't verified this yet but this might have been fixed by #1488
