### ISSUE TITLE
BUG: innocents can see detective's radio due to team affiliation

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1477]
workshop

![image](https://github.com/TTT-2/TTT2/assets/5711436/897de43e-cca5-4bb3-ae8b-7ca140a29ce3)

**Comment by Histalek** [comment]
i'm thinking about this and am wondering: Is there ever any reason for something being team visible for TEAM_INNOCENT ?
Because this whole thing as a concept just screams Inno-tester to me and we should probably remove this outright?

**Comment by TimGoll** [comment]
> i'm thinking about this and am wondering: Is there ever any reason for something being team visible for TEAM_INNOCENT ? Because this whole thing as a concept just screams Inno-tester to me and we should probably remove this outright?

Yes, I thought about this as well. Maybe team innocent should only stream to the owner and public roles? So in this case if a normal inno would place this, only them and the detes (and any other public inno role) would be able to see this

**Comment by Histalek** [comment]
> > i'm thinking about this and am wondering: Is there ever any reason for something being team visible for TEAM_INNOCENT ? Because this whole thing as a concept just screams Inno-tester to me and we should probably remove this outright?
> 
> Yes, I thought about this as well. Maybe team innocent should only stream to the owner and public roles? So in this case if a normal inno would place this, only them and the detes (and any other public inno role) would be able to see this

it should not stream it to public roles, because then it is also an inno tester.
