### ISSUE TITLE
vfire-enabled explosions is not affected by explosion resistance

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1478]
workshop,

![image](https://github.com/TTT-2/TTT2/assets/5711436/ca713f4e-8f59-4fc5-8e4d-384ddbcf9023)

this is more of a concern for [ttt2-ext_addon_settings](https://github.com/TTT-2/ttt2-ext_addon_settings) maybe, but still

**Comment by EntranceJew** [comment]
![image](https://github.com/TTT-2/TTT2/assets/5711436/14c11ccc-1595-44f0-8d5e-b5e9269361df)
not 100% related but these functions also play nicely with vfire related things

**Comment by TimGoll** [comment]
I'm unsure whether that should be added to TTT2 or a new compat addon. Best would be to have this in vFire itself, but I guess they don't care?

**Comment by TimGoll** [comment]
Due to loading order shenanigans it is hard for me to reproduce this issue. I think this issue only exists if a player would die from an explosion, not if they'd only take some damage. If it is the case, I know a fix for that.
