### ISSUE TITLE
bug: dead players that move to spectator cannot have their bodysearch info accessed

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1483]
## Your version of TTT2 (mandatory)

- Workshop version from Steam

## Describe the bug (mandatory)

A player which is moved to spectator cannot have their name clicked and expanded to show their bodysearch details
Even if that info was collected prior to them disconnecting

## To reproduce

1. Kill someone
  a. (optional: check their corpse now)
3. Have that person switch to spectator
4. Attempt to investigate their corpse

## Expected behavior

Info which is available on the corpse remains accessible on the scoreboard regardless of the player's connection status
I expect as much because their death may be the only thing linking activity to a specific killer but that info is diminished if someone ragequits or has to restart their client

## Context (please provide as much as you can)

This may have some relationship to the issue
- [ ] todo: put a link to that here

Where the confirmation status of a disconnected player's corpse is not retained, therefore reporting it to the detectives require two clicks (one to re-confirm it in the UI and one to call the detective) -- in addition to not networking that info to any clients because the associated player is disconnected.

A proper solution for this may involve creating a LUT of players for a round (or utilizing something like `GAMEMODE.StartingPlayers`) when the round begins, because somewhere an IsValid() call is dead-ending something that is ordinarily a rational ask.

**Comment by TimGoll** [comment]
I'm unable to reproduce that issue. Maybe I'm missing something here. I killed that player, kicked them from the server and then attempted to confirm their corpse. It worked without any issues.

![image](https://github.com/TTT-2/TTT2/assets/13639408/ae818dc6-a2c1-4f9e-9745-3bfbe3773807)
![image](https://github.com/TTT-2/TTT2/assets/13639408/a978bb0e-f6f4-47e4-9adc-9fc889d34157)

**Comment by TimGoll** [comment]
Ah, you wrote spectator. Somewhere later you wrote about disconnecting. I try it again with spec.

**Comment by TimGoll** [comment]
Maybe it is because I'm using bots but if I'm killing a player, run `SetTeam(TEAM_SPEC)` and `SetForceSpec(true)` I can still confirm them as I could before. I need help reproducing the issue

**Comment by TimGoll** [comment]
Ok, I am able to reproduce the exact scenario now. But it is still almost working. I foced the player as a spectator with the command and then confirmed the body:

![image](https://github.com/TTT-2/TTT2/assets/13639408/17f56cad-e9f1-4f63-a214-c8f9ff18fb19)

The UI appears as desired and the message shows in the top right corner. The scoreboard shows that the body has search information available. However I can't see the body search result in the scoreboard. That is the only issue I can reproduce right now, the rest is working fine.

**Comment by TimGoll** [comment]
The linked PR fixes the part I was able to reproduce. Feel free to reopen the issue if I missed something.
