### ISSUE TITLE
Any non solid entities cannot be interacted with

### ISSUE THREAD

**Issue by Zeni44** [TTT-2/TTT2#1557]
## Your version of TTT2

- Latest GitHub version [afdfd91](https://github.com/TTT-2/TTT2/commit/afdfd91836c45087728e08c882a8d3ace90730c9)

## Describe the bug

Any interactable entity that is not solid is not handled properly and cannot be interacted with. 
Due to the nature of this bug, this should apply to any map with commonly hammer placed buttons that are not solid which are meant to be interacted with and makes the button completely unusable. This behavior isn't limited to necessarily buttons either and should go as far as any non solid entity.
The fault seems to lie within [this](https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/gamemode/client/cl_keys.lua#L82-L93) part of the code as traces ignore non solid entities resulting in no entity being found.

## To reproduce

Steps to reproduce the behaviour on an example map:

1. Load up [ttt_clue_se](https://steamcommunity.com/sharedfiles/filedetails/?id=281454209)
2. Attempt to use this button
![image](https://github.com/TTT-2/TTT2/assets/11852198/e7219053-08b5-4f6c-9df8-7a8fc2f6f684)

## Expected behaviour

The button triggers and the lights are turned off/on accordingly.

## Context (please provide as much as you can)

- This was tested on a clean, fresh install of TTT2 with nothing else
- No errors were given

## Additional context

Source does correctly handle this kinda behavior by doing a 80 units sphere check as can be seen inside [this method](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/baseplayer_shared.cpp#L1068) to find any valid entities that the player may try to interact with. There's multiple checks in place to prevent interacting through objects among other things.

**Comment by TimGoll** [comment]
Phew, I tested this for a solid 30 minutes and I don't get why it is broken. I think it has something to do with the changes @ZenBre4ker did, but I looked at the diffs and I don't see what could have broken it. 

One think that makes me wonder is that hitting use on this lever detects only the worldspawn entity, and GMod say that this entity is non-valid
HOWEVER the code that handles this was untouched in @ZenBre4ker's rework. So I'm a bit confused what changed here.

**Comment by saibotk** [comment]
@TimGoll did you try checking out the commit before those that you suspect to break it? And verify that it actually has to do something with these changes?

**Comment by TimGoll** [comment]
> @TimGoll did you try checking out the commit before those that you suspect to break it? And verify that it actually has to do something with these changes?

Histalek voiced an idea on discord yesterday. I think that is the issue. I'll test that tomorrow

**Comment by TimGoll** [comment]
I fixed it! Maybe you can verify it works on this (and other maps) soon-ish :)
