### ISSUE TITLE
Localization: missing/broken strings or issues

### ISSUE THREAD

**Issue by Satton2** [TTT-2/TTT2#1565]
Hello there!

Long time no see but I didn't forget about you! ;)

Here is some missing or broken strings:
1. This one should use the `item_disguiser_sidebar` line, but for some reason it's not:
![Снимок экрана 2024-06-25 024636](https://github.com/TTT-2/TTT2/assets/23385240/0d18f444-de2e-421e-82b8-087bc4bef3e9)
2. For some reason last words section in the UI doesn't use quickchat localization: 
![image](https://github.com/TTT-2/TTT2/assets/23385240/b0b8a2e0-a69b-4c3b-965a-72584b0c11a6)
3. There is no spaces between these lines (for example `search_kill_from_front` and `search_head`).
![Снимок экрана 2024-06-25 025017](https://github.com/TTT-2/TTT2/assets/23385240/613f4247-2029-441b-b0e9-409a277ae6b0)
4. In old_ttt skin the `status_off` line doesn't work.
![2024-06-27_18-42-04](https://github.com/TTT-2/TTT2/assets/23385240/27dc5ae7-3261-4e65-aa87-5d12afee5f74)

Issues:
1. These are not presented in commands. They are planned or it's just a false description?
![image](https://github.com/TTT-2/TTT2/assets/23385240/ddba8656-c477-447a-93cd-8445e91df8cb)
2. There is something not okay with this font. I believe it doesn't support cyrillic symbols and there for some are in different font while those which looks similar to latin ones are not. That's why it's shifting and is not lined up. Could you change the font to some that supports cyrillic symbols?
![image](https://github.com/TTT-2/TTT2/assets/23385240/6d5fd016-2a48-450d-a379-afc3bc7b0a87)
3. Is it possible to make this list showing names differently? Like in straight line with the line break only at the end?
![image](https://github.com/TTT-2/TTT2/assets/23385240/aa378816-c948-46f7-a06d-d842ca4baffa)

**Comment by TimGoll** [comment]
Issues:
1. planned
2. same thing happens in any language and I'm not sure why and how to fix

**Comment by TimGoll** [comment]
![image](https://github.com/user-attachments/assets/8f21d75e-0616-430a-8c05-5023d816a567)

I can't fix that one, the rest is done

**Comment by Satton2** [comment]
@TimGoll 
The 4 in "missing or broken strings" (`status_off`) wasn't changed / fixed in old_ttt skin.

Could you look at it? 👀

**Comment by TimGoll** [comment]
> @TimGoll The 4 in "missing or broken strings" (`status_off`) wasn't changed / fixed in old_ttt skin.
> 
> Could you look at it? 👀

I tend to forget that the old HUD exists and therefore didn't check it

**Comment by Satton2** [comment]
> > @TimGoll The 4 in "missing or broken strings" (`status_off`) wasn't changed / fixed in old_ttt skin.
> > Could you look at it? 👀
> 
> I tend to forget that the old HUD exists and therefore didn't check it

But will you fix it? 👀

**Comment by TimGoll** [comment]
I can take a look at it
