### ISSUE TITLE
Add Sprint Speed Factor To Settings

### ISSUE THREAD

**Issue by Cyxxus** [TTT-2/TTT2#1607]
## Is your feature request related to a problem? Please describe.

The sprint speed is higher than I would like but there is no way to adjust it.

## Describe the solution you'd like

A setting that allows me to change how much sprinting multiplies the base speed.
ie. 1.5 to make it 50% faster or 1.3 to make it 30% faster.

## Describe alternatives you've considered

There is an addon that changes the way sprinting works but even that doesn't allow changing the actual speed.

## Additional context

none

**Comment by TimGoll** [comment]
There actually is already a convar, it is just wrongly labeled in the menu
