### ISSUE TITLE
Binoculars cause an error

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/TTT2#1625]
## Your version of TTT2 (mandatory)

- TTT2 v0.14.0b Workshop version from Steam

## Describe the bug (mandatory)

If you try using the binoculars they create an error.

## To reproduce

Steps to reproduce the behaviour:

1. Go into a round
2. Equip binoculars
3. Use them (zoom, ...)

## Expected behaviour

This error shouldn't happen.

## Context (please provide as much as you can)

- Collection link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195
- Server error in the server console:
```
[TTT2 (Base) - v0.14.0b] gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua:126: attempt to call method 'SetFOV' (a nil value)
  1. SetZoomLevel - gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua:126
   2. unknown - gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua:174
```

**Comment by TimGoll** [comment]
That's such a strange error, why is this function non-existent? it is a base GMod function?

https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua#L117-L127

**Comment by NickCloudAT** [comment]
I can not reproduce this on my server right now. Zoom with Binoculars works just fine

**Comment by TimGoll** [comment]
It is maybe related to the one necro issue: https://github.com/TTT-2/ttt2-role_necro/issues/34

Because that also had a broken player entity. I wonder how that happens

**Comment by Histalek** [comment]
I still have to test this but i suspect `owner` to be `NULL` here. This would explain why `SetFov()` doesn't exist - NULL only has Entity functions defined [1]; and `SetFov()` is only defined on Players [2] - but still i would expect a `Tried to use NULL entity` error instead ...

As for how this might happen: We never explicitly set the owner and therefor rely on `Weapon:Equip()` or `Weapon:Deploy()` to set the owner. Problem is we call `SetZoomLevel(1)` - which expects a valid owner - *in* the binoculars `Deploy()` function *before* calling the baseclasses `Deploy()` [3] which then sets sets the owner.


[1] https://wiki.facepunch.com/gmod/null

[2] https://wiki.facepunch.com/gmod/Player:SetFOV

[3] https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua#L163-L167

**Comment by Histalek** [comment]
I wonder if we could just skip setting the FOV if we don't have a valid owner or if that might have other adverse effects

(also why do we only set the FOV on the server? with that we prevent it from being predicted ...)

**Comment by TimGoll** [comment]
> (also why do we only set the FOV on the server? with that we prevent it from being predicted ...)

It should be done predicted, yes. Many weapons don't do it though. This is why my playercam rework was such a pain
