### ISSUE TITLE
SK wins if Jackal and Serialkiller are alive

### ISSUE THREAD

**Issue by V3kta** [TTT-2/TTT2#163]
As already told in the title, the SK side wins if a Sidekick and a Serialkiller is still alive. Important Note: The Sidekick was a Detective before.

**Comment by Alf21** [comment]
What was the role of the sidekick's mate?

**Comment by V3kta** [comment]
Okay sry, it was a Jackal and Serialkiller who won as Serialkiller team.

**Comment by TimGoll** [comment]
Has the sidekick become a jackal?

**Comment by V3kta** [comment]
As I stated, yea, the previous jackal died before and the sidekick became the new jackal and the last other role died, and then the jackal and serialkiller won on the serialkiller side.

**Comment by TimGoll** [comment]
Okay, it wasn't clear to me, thanks.

**Comment by Alf21** [comment]
Is this bug still active?

**Comment by V3kta** [comment]
We had this situation once (since the new item system update). Same as before.

**Comment by Alf21** [comment]
I'm not able to reproduce this. Maybe re-open with some more instructions

**Comment by TimGoll** [comment]
There was this error, which was/is also seen in TTT Heroes (Dhalucard). As far as I know @lebroomer fixed this
