### ISSUE TITLE
Loading screen alignment and text issue

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/TTT2#1630]
## Your version of TTT2 (mandatory)

- TTT2 v0.14.0b Workshop version from Steam

## Describe the bug (mandatory)

The loading screen seems to not fit the whole screen. There is a visible gap at the top and the left side of the screen.
There also seems to be an issue with the text. It looks like there are broken words at the top of the text.

## To reproduce

Steps to reproduce the behaviour:

1. Go into a round
2. Wait until the loading screen appears
3. See described issue

## Expected behaviour

The loading screen should fill the whole screen and the text shouldn't look broken.

## Context (please provide as much as you can)

- Collection link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195
- Screenshot:
![ttt2_loading_screen](https://github.com/user-attachments/assets/2307310c-d387-4125-90dc-f54dd01b24bb)

## Additional context

Tested on a 1920x1080p monitor.

**Comment by TimGoll** [comment]
Sadly I don't know why the text looks broken. I tried a few things and couldn't get it working.
