### ISSUE TITLE
Missing translation for None role

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/TTT2#1631]
## Your version of TTT2 (mandatory)

- TTT2 v0.14.0b Workshop version from Steam

## Describe the bug (mandatory)

The translation of the None role doesn't exist and therefore shows an error at the bottom of the screen.

## To reproduce

Steps to reproduce the behaviour:

1. Go into a round
2. Restart the round a couple of times (fast)
3. Look at the bottom of the screen
4. See described issue

## Expected behaviour

This error message should be removed or the translation should be added for the None role.

## Context (please provide as much as you can)

- Collection link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195
- Screenshot:
![ttt2_missing_translation](https://github.com/user-attachments/assets/fc24a647-a152-4600-86a7-2ed35049ae19)

**Comment by Histalek** [comment]
I'm torn between showing nothing for role none and showing some help text along the lines of "This is only a placeholder role given to you until the server has decided your real role".

@TimGoll what do you think? The former should be fine, given that role none has no gameplay relevance. The latter explains the purpose of the role, but might still be confusing the player in situations like the one mentioned in this issue.

**Comment by TimGoll** [comment]
I'd prefer hiding it, as there is no real benefit to a detailed description. ROLE_NONE should never be relevant in a real game
