### ISSUE TITLE
Client error at round start

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/TTT2#1648]
## Your version of TTT2 (mandatory)

- TTT2 v0.14.0b Workshop version from Steam

## Describe the bug (mandatory)

At round start one player has received an error in the console.

## To reproduce

Steps to reproduce the behaviour:

1. Join a server
2. Wait until round starts
3. See described issue (happened only twice so far)

## Expected behaviour

The error shouldn't appear.

## Context (please provide as much as you can)

- Collection link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195
- Client error in the developer console:
```
[TTT2 (Base) - v0.14.0b] gamemodes/terrortown/gamemode/client/cl_main.lua:499: attempt to call method 'IsReady' (a nil value)
  1. Run - gamemodes/terrortown/gamemode/client/cl_main.lua:499
   2. func - lua/ttt2/libraries/gameloop.lua:824
    3. unknown - lua/includes/extensions/net.lua:38
```

## Additional context

I guess an additional check if the client is valid or something like that should solve this.

**Comment by TimGoll** [comment]
Was the player still in the connection screen at that point?

**Comment by mexikoedi** [comment]
> Was the player still in the connection screen at that point?

I can't say that for sure but it's the first (or one of the first) log entries right after changing to a new map. So I guess yes.

**Comment by Fesiug** [comment]
I get this client error as the first player in a dedicated server. Up-to-date.
