### ISSUE TITLE
Missing translation of the Beacon in the world

### ISSUE THREAD

**Issue by MisterClems** [TTT-2/TTT2#1652]
## Your version of TTT2 (mandatory)

- Latest GitHub version

## Describe the bug (mandatory)

Missing translation of the Beacon in the world
It has translated everywhere menu/shop/settings but not when placed in the world

## To reproduce

Buy a Beacon
Place it

## Expected behaviour
Have the translation of the Beacon

## Context (please provide as much as you can)

![Screenshot 2024-09-29 235255](https://github.com/user-attachments/assets/b18f95cd-0478-4bf7-94b3-493e236b0270)
![Screenshot 2024-09-29 235251](https://github.com/user-attachments/assets/53526515-8944-44fa-a5fa-c3047978d989)

**Comment by TimGoll** [comment]
ah, this is because of this line:

https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/entities/entities/ttt_beacon.lua#L13

It should be `beacon_name`
