### ISSUE TITLE
attempt to call field 'ReadPlayer' (a nil value)

### ISSUE THREAD

**Issue by Spark61** [TTT-2/TTT2#1670]
## Your version of TTT2 (mandatory)

- TTT2 v0.14.0b Workshop version from Steam

## Describe the bug (mandatory)

At the start of the round, all players receive this error in the console, and a blurry overlay appears for everyone.

## To reproduce

Steps to reproduce the behaviour:

1. Join a server
2. Wait until round starts
3. See described issue (happened only twice so far)

## Expected behaviour

The error shouldn't appear.

## Context (please provide as much as you can)

- Collection link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=3226786374
- **All** Server errors in the server console
```
[Spark61|2|STEAM_0:1:168886790] Lua Error:

[TTT2 (Base) - v0.14.0b] gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:308: attempt to call field 'ReadPlayer' (a nil value)
  1. func - gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:308
   2. unknown - lua/includes/extensions/net.lua:38
```
- Client errors in the developer console

```
[TTT2 (Base) - v0.14.0b] gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:308: attempt to call field 'ReadPlayer' (a nil value)
  1. func - gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:308
   2. unknown - lua/includes/extensions/net.lua:38 (x2)
```

- Screenshots

## Additional context
![Image](https://github.com/user-attachments/assets/a565699d-ae03-4622-8aac-10b2add6a4e1)

**Comment by NickCloudAT** [comment]
This issue arrises if your gmod or your server (depending on if you use peer to peer or dedicated) is out of date.
Just to check, please use "version" in server console and send us your output.

**Comment by TimGoll** [comment]
Yep, update your server and then it will work again
