### ISSUE TITLE
A error that is happening

### ISSUE THREAD

**Issue by Ikd13123123123** [TTT-2/TTT2#1675]
## TTT2 version
0.14.0b on steam

## Describe the bug

A hud bug that won't let me start the game at all.

## To reproduce

Steps to reproduce the behaviour:

1. Enable the gamemode
2. Click on a map
3. Look at the console after it loads
4. See the error

## Expected behaviour

That it would let me play the game normally.

## Context

https://steamcommunity.com/sharedfiles/filedetails/?id=3358369189

The error:
https://raw.githubusercontent.com/Ikd13123123123/myttt2errors/refs/heads/main/Errors/ttt2error1

## Additional context

This happens without ttt2

**Comment by NickCloudAT** [comment]
As far as I see, you also have other gamemodes in that collection. Some modes don't make good enough checks to see if they should load (or some files) or may even do some bad things.

Please try to remove everything that has todo with murder for example
Also please provide the output of the addonchecker command and the version command.

**Comment by TimGoll** [comment]
Yeah, the gamemode or the bots addon are most likely incompatible with TTT2. There is an TTT2 bots addon if you need "intelligent" bots

**Comment by Ikd13123123123** [comment]
NickCloudAT addonchecker didnt say anything

TimGoll the bots are not incompatible
