### ISSUE TITLE
Client error related to translations

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/TTT2#1695]
## Your version of TTT2 (mandatory)

- TTT2 v0.14.0b Workshop version from Steam

## Describe the bug (mandatory)

The issue appeared for the first time for only one player. He got an error which is related to translations. We don't know why this error happened because we only noticed it later on. Maybe it is an edge case like dying/disconnecting/... at the time the code tries to run or something in that direction. There could be a missing check at the code section.

## To reproduce

Steps to reproduce the behaviour:

1. Go into a round (maybe try the collection below)
2. Play some rounds and try to trigger the error
3. See the described issue and error

## Expected behaviour

This error shouldn't appear for the player.

## Context (please provide as much as you can)

- Collection link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195
- Client error in the developer console:
```
[TTT2 (Base) - v0.14.0b] gamemodes/terrortown/gamemode/client/cl_lang.lua:543: bad argument #1 to 'pairs' (table expected, got string)
  1. pairs - [C]:-1
   2. Msg - gamemodes/terrortown/gamemode/client/cl_lang.lua:543
    3. ClientUse - gamemodes/terrortown/entities/entities/ttt_base_placeable.lua:70
     4. unknown - gamemodes/terrortown/gamemode/client/cl_keys.lua:97
```

## Additional context

We never saw this error in prior TTT2 versions.
Maybe it is only an issue in TTT2 v0.14.0.

**Comment by Histalek** [comment]
I have a loose idea of what might be going on here, but i haven't been able to reproduce this yet

that player probably tried to pickup a radio/visualizer/decoy/beacon that didn't belong to them, could that be correct?

**Comment by mexikoedi** [comment]
> I have a loose idea of what might be going on here, but i haven't been able to reproduce this yet
> 
> that player probably tried to pickup a radio/visualizer/decoy/beacon that didn't belong to them, could that be correct?

Yes that could be it, there were beacons placed by a Detective who wasn't the player who got the error.
