### ISSUE TITLE
Spectator bug

### ISSUE THREAD

**Issue by TheNickSkater** [TTT-2/TTT2#194]
**Video**
https://youtu.be/ZApH1V-vU54 not best quality but at 12 seconds, there you defenetly see it for a short moment (in the video even more times, but not as clear).

**Describe the bug**
Sometimes, spectators who are flying around in free mode, are flashing for all other players (specs and alive) as flying hands, sometimes also with weapons..

**To Reproduce**
Steps to reproduce the behaviour:
Well, I dont know, just happenes.

**Expected behaviour**
Well, not seeing flying hands?

**Screenshots**
Video above

**Comment by Alf21** [comment]
<img width="534" alt="bug" src="https://user-images.githubusercontent.com/11843790/50383266-5d400c00-06b0-11e9-94bb-e5619c70c7c8.png">

I don't know what you mean. This entity?

**Comment by TheNickSkater** [comment]
Yes, it's appearing for players randomly. And those are the spectators. I already looked a bit in the Spectator code, and Spectators are getting the SetupHands thingy. Probably thats why..

**Comment by Alf21** [comment]
Hmm maybe you find a fix. Currently i don't have a lot of time :/ But i will give a look in some days maybe

**Comment by Alf21** [comment]
You should report this bug to Facepunch :) Maybe this is connected with the PostDrawOpaqueRenderables hook
