### ISSUE TITLE
Inaccuracy in terms of the possibility of buying an item.

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#217]
Показатели не совсем точно работают, как видно на картинке, по показателям его можно купить, но он не покупается. Возможно предмет купил другой детектив, но тогда нужно, чтоб это показывало и человек не думал, что это какая-то ошибка сервера.
![default](https://user-images.githubusercontent.com/7480655/50917440-8b627180-144e-11e9-9b2c-c7c207bcc492.png)

**Comment by saibotk** [comment]
Did you use the TTT2 Teamlimited functionality?

**Comment by Alf21** [comment]
@dok441
