### ISSUE TITLE
Roundtime-Sync

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/TTT2#232]
**Video**
https://www.youtube.com/watch?v=VehQZ96nVLc ab etwa 9 Minuten die neue Runde

**Describe the bug**
Die Rundezeit steht auf 0 und bekommt nicht den Wert den sie eigentlich bekommen sollte. (In den Videos kann man auch überprüfen ob das nur bei einem Spieler, oder bei allen gleichzeitig auftritt).

**Comment by Alf21** [comment]
#279
