### ISSUE TITLE
Suggestion for improving the mode.

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#235]
Есть предложение, для улучшение режима, а именно, часто карты очень маленькие или же в них часто когда появляются люди застревают в друг-друге или же мешают друг-другу, к примеру кидают бочки или толкают. Я предлагают сделать до начала раунда чтоб игроки могли проходить через друг-друга, а когда раунд начнется, это выключится. Это позволит ставить карты с маленьким количеством появления и уберет глупые и не нужные убийства в начале.

**Comment by Alf21** [comment]
You should use the "ttt_spawn_wave_interval" convar
