### ISSUE TITLE
Critical bug DNA scanner

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#248]
The new version does not work DNA scanner, I took DNA, but it is not shown.

**Comment by dok441** [comment]
I also note that objects are not displayed as mines, which should be visible through the walls.

**Comment by dok441** [comment]
Проблема осталась на стороне невиновных, у детектива видно днк, а у невиновных нет.

**Comment by Alf21** [comment]
Why should the Innocent see the DNA?

**Comment by dok441** [comment]
Как понять с чего? Они подобрали с трупа детектива ДНК, взяли к примеру с него днк и невиновным должен видеть же.

**Comment by Alf21** [comment]
I don't see any reason why the innocent shouldn't see the dna...

**Comment by dok441** [comment]
Я говорю, что они не видят днк, а не должны. При подбирании невиновным днк, ему не показывает днк, оно пищит, но его не видно, это когда был баг, что даже детектив его не видел.

**Comment by Alf21** [comment]
Yea as I said, i can't reproduce it...
