### ISSUE TITLE
Rework Network System

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/TTT2#279]
Rework the network system in a way that the server knows if the client has received the message

```
Der  Server weiß, was er dem Client gesendet hat
Problem is nur, dass das spinnt, wenn der Client die Nachricht nicht bekommen hat
weil der Server denkt, er habe es schon gesendet
Man müsste noch ne Rückmeldung vom Client an den Server geben
```

**Comment by saibotk** [comment]
The initial thought of reworking the networking system will be done, but not as described above. There won't be a method to know if the client received a message, rather we should make sure that net messages are only sent / received, when a client is able to receive messages (eg. not in hooks like https://wiki.garrysmod.com/page/GM/PlayerInitialSpawn ).

**Comment by TimGoll** [comment]
I've added the playerReady hook some time ago. This one might be perfect for this

**Comment by Alf21** [comment]
#395
