### ISSUE TITLE
Spam confirmation of the death of a deceased person

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#280]
Если человек вышел с сервера, и другой человек пытается осмотреть труп, всем сообщит, что он нашел тело, но так можно нажимать бесконечно и можно довести до состояния, что весь раунд будет спамить об этом уведомлении.

**Comment by Alf21** [comment]
Seems to be a normal TTT bug

**Comment by Alf21** [comment]
Fixed?

**Comment by dok441** [comment]
No, it's still a problem considering the latest working version of the mode.
