### ISSUE TITLE
Turning vampire

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#294]
Предлагаю сделать превращение вампира в голубя как активации ловушки у предателей, чтоб это как-то можно было отслеживать, так-как не определить rdm вампира, если нельзя определить, превращался ли он...

**Comment by Alf21** [comment]
Fixed with the newest TTT2 update?

**Comment by dok441** [comment]
No.

**Comment by Alf21** [comment]
Should work now

**Comment by dok441** [comment]
Все еще нет.

**Comment by Alf21** [comment]
Then I don't understand :(

**Comment by dok441** [comment]
Я проверил и логи и через систему свою, не считает как активацией.

**Comment by Alf21** [comment]
This can just be solved with a better translation.

**Comment by dok441** [comment]
I checked the logs and through the system of its own, is not considered as activated.
