### ISSUE TITLE
Bug with fast reload

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#300]
Есть критический баг, с быстрой перезарядкой. Смысл его в том, что ты можешь стрелять, выстрелить целую обойму, нажав перезарядку или она начнется сама и выкинуть оружие, подобрав его, оно уже будет перезаряжено, что позволит снова стрелять.

**Comment by Alf21** [comment]
Even not possible to understand the process of reloading...

**Comment by dok441** [comment]
Что невозможно понять? Это же дает огромное преимущество, нажал перезарядку, выкинул оружие. подобрал, а у тебя уже полная обойма и стреляй не хочу дальше.

**Comment by Alf21** [comment]
Is this a default TTT bug? If I understand right, you reload the weapon and throw it away. After picking it up again, there is a full weapon?

**Comment by dok441** [comment]
Ты правильно понял.

**Comment by Alf21** [comment]
Is it fixed now?

**Comment by Alf21** [comment]
@dok441

**Comment by dok441** [comment]
No
