### ISSUE TITLE
The jester-like sidekick, but still a buffoon.

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#310]
Если шут после смерти становится сообщником, то не показывается шакалу, что он им стал. Шакал все еще видел его как шут, в чате ничего не писало. Так же хотел уточнить, он точно не может стать сообщником, но только ясновидящего в этом случае, а должен быть только сообщником шакала? Просто как тут распознавать чей он сообщник, если он может быть на 2 стороны...

**Comment by dok441** [comment]
Так же в дополнение, в такой ситуации было такое, когда шут который стал сообщником, убил шакала, раунд закончился и предатели выиграли.

**Comment by Alf21** [comment]
The traitors win if everyone is dead. If the Jackal died the same time as the Jester died, the Traitors will win (they fulfilled their goal to kill everyone)...
