### ISSUE TITLE
Jester Selfkill & Phoenix Model only (?)

### ISSUE THREAD

**Issue by dodorian88** [TTT-2/TTT2#324]
The Jester can still kill himself with the "kill" command in console. 

The other thing I noticed (not sure if feature or bug though) that in every round the playermodel keeps Phoenix only. There should be 3 more terrorist models though:

local ttt_playermodels = {
	Model("models/player/phoenix.mdl"), <- only this one is used
	Model("models/player/arctic.mdl"),
	Model("models/player/guerilla.mdl"),
	Model("models/player/leet.mdl")
}

I tried to use custom models, but the mode always uses the first line only, so it seems.

**Comment by Alf21** [comment]
Re-open this if it's still a thing.
