### ISSUE TITLE
Critical bug for the innocent

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#339]
Есть серьезный баг, связный с хитростью игроков. Когда невиновный остается 1 на 1 с предателем, то он может попросить перейти всех мертвых в наблюдатели, и как только они переходят в наблюдатели, он видит кто жив, а кто мертв, таким образом можно помогать невиновным, мертв ты или нет, просто переходя в наблюдатели.

There is a serious bug connected with the cunning of the players. When the innocent is left 1 on 1 with the traitor, he can ask all the dead to go to the observers, and as soon as they go to the observers, he sees who is alive and who is dead, so you can help the innocent, dead or not, just going to the observers.

**Comment by TimGoll** [comment]
are you talking about the vanishing dots in the mini scoreboard? I think @TheNickSkater has tried a few things to tackle this problem.
