### ISSUE TITLE
Equipment Shop Sorting

### ISSUE THREAD

**Issue by TheSuspect2306** [TTT-2/TTT2#348]
ich habe es bis jetzt nirgends gesehen hier im github deswegen:

im shopeditor einstellen können, dass man festlegen kann welches item welchen slot oder sortierung belegt, zb die armor ganz oben, dann das radar usw. wie es im normalen ttt auch ist bloß das man evtl noch die möglichkeit hat es selber zu gestalten was wohin soll

**Comment by TimGoll** [comment]
Wir haben gerade nochmal drüber nachgedacht und uns dagegen entschieden. Ist kein Feature welches für uns aktuell den Aufwand wert ist. Ein generelles Sortieren wird aber wohl in der 1.0 kommen.
