### ISSUE TITLE
Running and his problems.

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#350]
Now many people are concerned about the problem with running. This is due to the fact that now the standard running on SHIFT, but also conversational treacherous chat is also on SHIFT and people are annoyed. (I know that can be customized, but many beginners and every time tell them, it's annoying) So many people are already used to running on double tap, for example w,w. You can add the ability to customize, in addition to running on the 1 button, an alternative is running on the double-click of the button, many people ask it to add. Ah and immediately to remove the standard running on SHIFT, and do his immediately on 2(w), and if need to switch on use button, two hare one adding =)

Сейчас многих людей волнует проблема с бегом. Связано это с тем, что сейчас по стандарту бег на SHIFT, но и разговорный предательский чат тоже на SHIFT и людей это раздражает. (Я знаю, что можно настроить, но многие новички и каждый раз говорить им, это раздражает) Так же люди многие уже привыкли к бегу на двойное нажатие, к примеру w,w. Можете добавить возможность настройки, помимо бега на 1 кнопку, альтернативу, это бег на двойное нажатие кнопки, люди многие просят это добавит. Ну и сразу убрать стандартный бег на SHIFT, а сделать его сразу на 2(w), а если надо переключиться на использование кнопки, два зайца одним добавлением =)

**Comment by TimGoll** [comment]
I like the idea with double W and it was requested multiple times. But I dislike the idea of removing the default on shift since running on shift is the default in every game. But it's open for a discussion.

**Comment by dok441** [comment]
Like I said, to SHIFT, to speak with the traitors, so they will just override in the manual, as many complain, so as not everyone is smart and don't know how.

**Comment by TimGoll** [comment]
You can change the traitor chat key in the GMOD settings. Additionally we plan on changing the voice system. But this is not confirmed yet, it's just planned

**Comment by LunexKun** [comment]
Changing the vooice system! Sounds good!

**Comment by TimGoll** [comment]
Nonono. We plan on changin gthe keybinding system for the voice system. **MAYBE**

**Comment by dok441** [comment]
I wrote that you can change, but many beginners and do not know how and what to do and every time they need help. Therefore, if 2 implementations are running, that would be great.
On expense voice system, his need edit, I agree, very pisses me off, when man dies and he shines lights yellow and you know, that he died...

**Comment by TimGoll** [comment]
I don't now how feasible this would be, but what about an option for server owners to overwrite the default key?

**Comment by TimGoll** [comment]
@lebroomer what do you think about this? I think it was you that made the last change to the bind system.

**Comment by lebroomer** [comment]
I think @tobiti made an ULX Extension for the TTT2 bind system. I don't know, if this is already possible with the addon, nur even if not, it would fit in there very well.

**Comment by TimGoll** [comment]
His addon only allows to add commands. But yes, it would fit in there!

**Comment by Alf21** [comment]
Solved?

**Comment by dok441** [comment]
Why solved? They did nothing but excite.

**Comment by TimGoll** [comment]
Yeah, but we won't change the default key of sprint to something arbitrary. So you have to create an addon that changes this or ask @Tobiti if he wants to implement this feature into his addon.

**Comment by dok441** [comment]
And add the possibility of using the activation of the sprint by double tap?

**Comment by TimGoll** [comment]
It's on our todo list, not sure when it is implemented though

**Comment by Histalek** [comment]
sprinting by double tapping W should now be possible thanks to #417 .


I haven't tested it but i would think this issue remains:
> On expense voice system, its need edit, I agree, very pisses me off, when man dies and he shines lights yellow and you know, that he died...

i would assume dok means, that if somebody dies while talking the color of the voicepopup changes to yellow before it disappears. Which shows the other players that he died.

**Comment by TimGoll** [comment]
Yes, it works like a charm. The problem with the voice chat colors needs its own issue if it still exists. Thanks!
