### ISSUE TITLE
Round end subtext overlap on languages with short titles

### ISSUE THREAD

**Issue by TheOnly8Z** [TTT-2/TTT2#364]
**Description**
At the end of a round on the results screen, if a language has a very short translation for the winning team (in my case, Chinese), the small text underneath the winning team display will overlap. To be specific, it is the "how many players took place, of which how many are traitors" and "the round lasted how long" text.

**To Reproduce**
Use a language with a short team victory text.

**Additional context**
I am using a Chinese language translation that is not finished. To reproduce, you may change "TRAITORS WIN" to "叛徒胜利" and see the overlap.

I suggest either checking for text width and adjust the positions, or make it one line entirely.

**Comment by TimGoll** [comment]
We currently plan to redesign the roundendscreen! So this will be fixed, you have to be a bit patient though

**Comment by Alf21** [comment]
Does this problem still exist?

**Comment by TimGoll** [comment]
It has been a while. #684 will fix this though
