### ISSUE TITLE
Disable Item icon in Body

### ISSUE THREAD

**Issue by TheSuspect2306** [TTT-2/TTT2#379]
man kann ja in der item lua sowas einstellen wie "ITEM.hud" das kann man bsp auf nil stellen sodass es nicht links im hud steht, das wäre auch noch nice wenn man das gleiche bei ITEM.material machen kann oder es sowas wie ITEM.bodyMaterial gibt sodass man immer noch .material behält für shop icons usw

**Comment by TimGoll** [comment]
Just use the hook `TTTBodySearchPopulate`. It is already in the game.

For example:
```lua
hook.Add('TTTBodySearchPopulate', 'my_hook_id', function(search, raw)
	PrintTable(search)

	-- remove equipment item 'item_ttt_infinishoot' from body search
	search.eq_item_ttt_infinishoot = nil
end)
```

**Comment by TimGoll** [comment]
I added an additional flag to the item base, it's called `ITEM.populateSearch`. It's true by default, set to false if your item should be hidden.

see: https://github.com/TTT-2/TTT2/commit/6cb95308d9c4d686a72bc287332264edd8e14612
