### ISSUE TITLE
Displays the label of the marker

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#383]
I believe that the display that the person is marked is inconveniently located and closed by other text, so it should be done below.
![Безымянный](https://user-images.githubusercontent.com/7480655/67071956-46b5f480-f19d-11e9-8cfa-cbe8bf612433.png)

**Comment by TimGoll** [comment]
Strange on my screen it is below that.
Will be fixed once we rework the overlay

**Comment by TimGoll** [comment]
This will be fixed in the following update. We've completely reworked the targetID and therefore this is no longer a problem
