### ISSUE TITLE
Performance increase

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#384]
https://pastebin.com/xAK9Xk1Z
I here used script badcoderz and observed, that on client case falls fps on some roles. It is when you play with people it is just the same and noticeable, that's what I got using this script, maybe it will help improve performance.

**Comment by Alf21** [comment]
Thanks for your help! :) We are aware of some performance lags like the miniscoreboard, working on it if there is any time (already noticed and a registered entry in our ToDo-List) :)

**Comment by dok441** [comment]
https://pastebin.com/y41RijNRAfter all the changes, I tested again and this time much less of a load itself, but still there is not the perfect code reading system, you can look yourself

**Comment by TimGoll** [comment]
your link is dead

**Comment by dok441** [comment]
https://pastebin.com/JK4rWpb5 new
