### ISSUE TITLE
Identification of "unknown" Bug

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#409]
**Describe the bug**
We found out a bug that appears in the client's console and it happens when an Unknown gets identified when he doesn't have a role yet.
(Examples: Dying of fall damage, Killing a Jester, etc..)

**To Reproduce**
Steps to reproduce the behaviour:
1) Force a player or bot Unknown 
2) Slay the unknown(don't kill him with your weapons) 
3) Identify the unknown body

![5745a604-a2ae-48b7-be8e-4aac3124be70](https://user-images.githubusercontent.com/36534723/70189873-c15ab500-16f4-11ea-832f-606123ce0180.png)

[ERROR] addons/ttt2-master/gamemodes/terrortown/gamemode/client/cl_main.lua:342: attempt to index a nil value
  1. func - addons/ttt2-master/gamemodes/terrortown/gamemode/client/cl_main.lua:342
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by TimGoll** [comment]
Fixed in https://github.com/TTT-2/TTT2/commit/7eca7e28ce852c083f004dc2d556e1410a2220c5
