### ISSUE TITLE
Strange Armor Behaviour

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#411]
**Describe the bug**
I don’t know if this is intended but I noticed some strange stuff with the new armor system;
In particular, there are 2 things I think don’t make much sense/aren’t balanced.
(All tests in this topic were done with a deagle that deals 37 damage always shooting at the body) 
First, this is the normal armor behaviour: 

![1](https://user-images.githubusercontent.com/36534723/70395775-91682600-1a02-11ea-9146-fc2bb33eb61d.jpg)

After the yellow line the innocent player drinks the armor soda (which gives 15 armor) and when the armor gets destroyed the damage returns normal as it should.

![2](https://user-images.githubusercontent.com/36534723/70395823-13584f00-1a03-11ea-81ba-a279fa583945.PNG)

In the first instance we again tried with the soda, and everything works fine, but when the traitor buys the armor from the shop, which gives 30 armor (still level 1 armor), everything kind of falls apart…
First of all the buyable armor is much better compared to the one that is in the soda, but weirder is the fact that once it gets destroyed (before the yellow line) there still seems to be a “hidden” armor that shields the player and this will remain until that player dies.

The second unusual behaviour is that certain classes have an invisible armor from the start of the round, I think that this is maybe intentional and if it is it would be really nice to be able to change these values, because some of them can be really unbalanced.

![3](https://user-images.githubusercontent.com/36534723/70395836-3daa0c80-1a03-11ea-969b-95940f1cffbd.jpg)

![4](https://user-images.githubusercontent.com/36534723/70395838-41d62a00-1a03-11ea-9fa1-6b2eeaa6c5c9.jpg)

In these examples we tried with the Serial Killer and Necromancer, both spawn with 0 armor but have some hidden armor values that make them way more resistant than most classes, and that can even be improved by buying armor or drinking a soda.

**Expected behaviour**
The armor should stop shielding when destroyed and and certain classes shouldn't have hidden armor values

**Desktop (please complete the following information):**
 - Collection-Link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=1806066645
 - Server-Errors in the server console: no error in server side console 
 - Client-Errors in the developer console no error in client side console

**Comment by TimGoll** [comment]
Too be honest, I have no clue why this could happen. My first thought was that you have somewhere an old file cached that gives the player the old and the new armor, but I don't think this is the case. Especially combined with the fact that some roles seem to receive less damage. Maybe someone else has an idea?

**Comment by ThePlatinumGhost** [comment]
I usually clean the cache quite often 
When I encounter a problem it is usually the first thing I do

**Comment by TimGoll** [comment]
Can someone else verify / reproduce this issue? Maybe @TheNickSkater ?

**Comment by TheNickSkater** [comment]
Yes tested it and I can't reproduce the bug.
I get less damage with armor and once it's depleted I get normal damage again, doesn't matter if it's armor bought from the shop or the soda.

**Comment by ThePlatinumGhost** [comment]
Tested with GitHub last version Right?

**Comment by TheNickSkater** [comment]
> Tested with GitHub last version Right?

Of course.

**Comment by ThePlatinumGhost** [comment]
We were able to solve the armor problem
apparently it was caused by this addon 
![image](https://user-images.githubusercontent.com/36534723/70561223-5b55ae00-1b8a-11ea-88d8-53fbd155a352.png)
https://steamcommunity.com/sharedfiles/filedetails/?id=1640512667
Removing it no longer presents the bug ( maybe someone else can try if this addon has some incompatibility issue with new armor system(?) )
But only one thing remained strange, the Serial killer continued to have a hidden passive armor
So I looked in the code and I find this on   
ttt2-role_sk-master\lua\terrortown\entities\roles\serialkiller\shared.lua on code line 122 
![image](https://user-images.githubusercontent.com/36534723/70561162-40833980-1b8a-11ea-925c-7f856b9cba8c.png)
The serial killer has an hidden armor value off 50% and does 25% more damage
By modifying ScaleDamage I can manage these values
Now it works fine.

**Comment by TimGoll** [comment]
Good to know, thanks. I will look into it on the weekend or so.

@alf21 we could give the serial killer 60 armor, the same value the marker has
