### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by Satton2** [TTT-2/TTT2#418]
1. These errors appear when I try to change some setting in the Administration tab without needed permission:
```
[ERROR] addons/ttt2-master/gamemodes/terrortown/gamemode/client/cl_help.lua:680: attempt to call global 'GetParamTranslation' (a nil value)
  1. func - addons/ttt2-master/gamemodes/terrortown/gamemode/client/cl_help.lua:680
   2. unknown - lua/includes/extensions/net.lua:32


[ERROR] addons/ttt2-master/gamemodes/terrortown/gamemode/client/cl_help.lua:668: attempt to call global 'GetParamTranslation' (a nil value)
  1. func - addons/ttt2-master/gamemodes/terrortown/gamemode/client/cl_help.lua:668
   2. unknown - lua/includes/extensions/net.lua:32


[ERROR] addons/ttt2-master/gamemodes/terrortown/gamemode/client/cl_help.lua:656: attempt to call global 'GetParamTranslation' (a nil value)
  1. func - addons/ttt2-master/gamemodes/terrortown/gamemode/client/cl_help.lua:656
   2. unknown - lua/includes/extensions/net.lua:32
```
![1](https://user-images.githubusercontent.com/23385240/71312431-f167bf00-243b-11ea-88db-f6898c72ce8a.gif)

2. Russian letters don't change into capitals on the menu while the English letters do. Also, they don't fit in the buttons (change the style of buttons/split the text into two lines?):
![image](https://user-images.githubusercontent.com/23385240/71312452-35f35a80-243c-11ea-8a3c-f47ce3310698.png)
![image](https://user-images.githubusercontent.com/23385240/71312466-62a77200-243c-11ea-8c31-6719a92fb5f4.png)

3. Is it okay that there are`[key]` and not the key you set? I don't think so:
![image](https://user-images.githubusercontent.com/23385240/71312603-d1d19600-243d-11ea-827f-f3aedfa2a7b4.png)
![image](https://user-images.githubusercontent.com/23385240/71312605-d7c77700-243d-11ea-8e55-eb2b5aa3681b.png)

4. I thought this... thing (I forgot the word :D) must stick in one place and shouldn't adapt to the size of the string.
![image](https://user-images.githubusercontent.com/23385240/71312708-08f47700-243f-11ea-8f72-66bdc2136b03.png)

**Comment by Satton2** [comment]
5. The button is hiding some part of the text:
![image](https://user-images.githubusercontent.com/23385240/71312977-2297bd80-2443-11ea-9ce3-97f84838f697.png)

**Comment by TimGoll** [comment]
2. this is a gmod error, we use the provided function to convert to uppercase. If this function has problems with russian, report it to them
3. is intended this way since some items need key kombinations etc
5. is known and will be fixed with the GUI rework coming ... at some point (version 1.0)

**Comment by Satton2** [comment]
> is intended this way since some items need key kombinations etc

I don't understand this. The key is already shown in this little box, so what's the problem to show the same key in the text?
![image](https://user-images.githubusercontent.com/23385240/71313205-7657d600-2446-11ea-98e2-893f80ee08e6.png)

**Comment by TimGoll** [comment]
I could show it there
but for example the confirmation text uses some additional keys and it would introduce inconsitencies in this situation
But I'll think about this

**Comment by Satton2** [comment]
Confirmation te... am... you are talking about this one?
![image](https://user-images.githubusercontent.com/23385240/71313305-ace22080-2447-11ea-860d-4ad4ad4db5f2.png)
It currently uses `{usekey}` and `{walkkey}` to show the keys. So I don't see any problem with that.
`L.corpse_hint = "Press [{usekey}] to search. [{walkkey} + {usekey}] to search covertly."`

**Comment by TimGoll** [comment]
Yeah I might change this if you think it is better changed

**Comment by Satton2** [comment]
I think this `[key]` **must** show players the key that they need to press. Anyway, will you do this or not depends on your decision.

**Comment by TimGoll** [comment]
I've changed 3 in https://github.com/TTT-2/TTT2/commit/ab1d03336042e58049eb30bf94d3f535693e2257

**Comment by TimGoll** [comment]
All things are fixed except stuff related to vgui since this will be reworked completely after the 0.6 update
