### ISSUE TITLE
Hud behaves weird at resolutions < Full HD

### ISSUE THREAD

**Issue by menof36go** [TTT-2/TTT2#420]
**Video**
[Here](https://youtu.be/PN0RmTGzFY8)

**Describe the bug**
Upon joining the server with a resolution different from my monitor resolution (Full HD), the hud positions seem totally of. It looks like the hud elements are still using my monitor resolution instead of the actual window size to calculate the positions. After changing the video resolution or directly calling Reset on the hud, the positions are correct.

**To Reproduce**
1. Run the game in windowed mode
2. Use a resolution like 1600x900 and join the server
3. The hud should now look screwed up
4. Use lua_run_cl to call Reset directly or change the resolution to fix it again

**Expected behaviour**
Responsive hud layout

**Desktop (please complete the following information):**
 - TTT2 master 2ed6c7e8d11efc398a88f7fca2824ed2e4f81ee8 (Latest commit) with some added print statements I used to try and figure out what's wrong
 - No Server-Errors
 - No Client-Errors

**Additional context**
Merry Christmas and Happy Holidays

**Comment by TimGoll** [comment]
Yes this is "intended". It has nothing to do with sub full HD, but with a resolution change in general.

**Comment by TimGoll** [comment]
Okay, after trying for a bit I can't confirm any of your problems, there is even an automatic rescaling when the resolution is changes.

We should think about one additional case though: Changing the resolution and not being ingame does not trigger the caling at all. This should be changed.

Additionally one could think about changing the scale factor when changing the resolution with 1920x1080 being the default value (1.0)

**Comment by TimGoll** [comment]
I don't think this issue still exists
