### ISSUE TITLE
Attempt to index global 'EPOP' (a nil value) 

### ISSUE THREAD

**Issue by XplosiveP3nguin** [TTT-2/TTT2#423]
This error occurs upon booting of the server.

[Amis|2|STEAM_0:1:64512614] Lua Error:

[Trouble in Terrorist Town 2 (Advanced Update) - v0.5.5b] gamemodes/terrortown/gamemode/shared/hud_elements/ttteventpopup/pure_skin_eventpopup.lua:56: attempt to index global 'EPOP' (a nil value)
  1. PerformLayout - gamemodes/terrortown/gamemode/shared/hud_elements/ttteventpopup/pure_skin_eventpopup.lua:56
   2. PerformLayout - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:88
    3. Initialize - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:116
     4. Initialize - gamemodes/terrortown/gamemode/shared/huds/old_ttt/cl_init.lua:60
      5. LoadAllHUDS - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:225
       6. unknown - gamemodes/terrortown/gamemode/client/cl_main.lua:111

The collection we have is...
https://steamcommunity.com/sharedfiles/filedetails/?id=1875076088

**Comment by TimGoll** [comment]
There's probably an earlier error. EPOP exists 100%

**Comment by XplosiveP3nguin** [comment]
Yes there arent any appearing as incompatible. We have sorted those and updated them and removed the old ones.

**Comment by saibotk** [comment]
There has to be an error prior to this, you would have to check the server console again and give us the first error that appears.
I also noticed, that your log shows an old version of **TTT2 v0.5.5b**, but the current version is **TTT2 v0.5.7b**, so please update the addon and try again.
