### ISSUE TITLE
Body check by a detective.

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#425]
For some reason, he writes to the detective that he checked this body, when only an innocent man had checked it before and called the detective. Also in the table immediately writes about the role of a person to everyone when checking an innocent, not a detective.

**Comment by saibotk** [comment]
Could you please try to formulate this in another way? Eg. by explaining a specific way on how to reproduce this bug? I am sorry, but i really do not know what you are trying to say.

**Comment by dok441** [comment]
Well, I'll write more correctly later.

**Comment by Satton2** [comment]
@saibotk 
Let me try to explain...
For some reason, when you search a body (no matter what the role you have), search results are available for every player via scoreboard (magnifying glass icon also appears near confirmed dead player).

In standard TTT, search results are available for everyone _only if detective searches a body_.

Sometimes, a magnifying glass icon appears if a body was searched silently, so an "alive" player can be identified as dead due to this bug.

**Comment by saibotk** [comment]
Thank you for reporting the bug, i searched through the code and found the issue, i will discuss this further with the other team members and we'll find a solution. Thank you :+1:

**Comment by TimGoll** [comment]
Fixed it, please test: https://github.com/TTT-2/TTT2/commit/f060b143cecffe0cfa68e1e3dbb6f8bd8a0019a4

This reimpliments the old behaviour, but with a workaround until the confirmation system gets reworked in the next version

**Comment by dok441** [comment]
Problems remained, except for the problem with the detective.

**Comment by TimGoll** [comment]
Ah, you mean the problem is that the client has the data, even when no detective confirmed it? Yes, I know. This is a workaround right now. This will be completely redone properly in a future update

**Comment by dok441** [comment]
Also, the magnifying glass icon appears on the body, where it is still unknown to the innocent, they disappeared or not.

**Comment by dok441** [comment]
If the observer checks the body, the magnifying glass icon will appear in the table of the player and everyone will know that he is dead.

**Comment by TimGoll** [comment]
Hmm, I'll look into it again.

**Comment by TimGoll** [comment]
I don't know if I understood you correctly. Can you please check if it now behaves the way it is intended? Thanks.

**Comment by dok441** [comment]
Yes, you fixed it.
