### ISSUE TITLE
Missing strings.

### ISSUE THREAD

**Issue by Satton2** [TTT-2/TTT2#427]
Currently, these strings are missing in localization files:

1. 
![image](https://user-images.githubusercontent.com/23385240/50937025-08a7d980-1483-11e9-846b-d22e8fc1ad08.png)
2. 
![image](https://user-images.githubusercontent.com/23385240/50937040-1cebd680-1483-11e9-9e10-c7f045faf084.png)
3. I don't why it's translated (maybe dok441 translated) but this little title's popup string is missing too.
![image](https://user-images.githubusercontent.com/23385240/50937074-53295600-1483-11e9-8b9b-941fdaaaba1c.png)
4.
![image](https://user-images.githubusercontent.com/23385240/50937208-c0d58200-1483-11e9-88f3-a6be9a3fc922.png)
5.
![image](https://user-images.githubusercontent.com/23385240/50937269-f8dcc500-1483-11e9-8dd3-a0d0ee9e31c3.png)
6.
![image](https://user-images.githubusercontent.com/23385240/50937291-08f4a480-1484-11e9-887d-2b878a80b812.png)
7.
![image](https://user-images.githubusercontent.com/23385240/50937301-16aa2a00-1484-11e9-92dd-c65ceb7b169a.png)
8.
![image](https://user-images.githubusercontent.com/23385240/50937334-35102580-1484-11e9-879b-50daec4a6b68.png)
9.
![image](https://user-images.githubusercontent.com/23385240/50937357-48bb8c00-1484-11e9-9648-ad3f93cf8104.png)
and
![image](https://user-images.githubusercontent.com/23385240/50937417-91734500-1484-11e9-9921-f02357648728.png)

Edit: oh, forgot this:
10. I don't where it takes «Back» string but it's missing too.
![image](https://user-images.githubusercontent.com/23385240/50937559-4e65a180-1485-11e9-8b64-7ab695db8ac6.png)

**Comment by TimGoll** [comment]
I think all of this is taken care of in #480 
Therefore I'll close this. Since the complete UI changed, you can reopen a new issue if something is still missing after the merge.
