### ISSUE TITLE
Double tap on "S" to sprint backwards

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#429]
**Is your feature request related to a problem? Please describe.**
At this moment you can only double tap on "W" for sprint fowards, I suggest also the possibility to double tap on "S" to sprint backwards, because the traditional key bind sprint can also sprint backwards

**Comment by TimGoll** [comment]
Okay, I thought about this for a bit. I think if we do this, double tap on all four direction keys should work.

And maybe one additional change to the two sprint modes. If you start sprinting with double movekey and then press and hold the sprint key while still holding the movekey, releasing the sprintkey should stop the sprinting.

**Comment by Histalek** [comment]
> If you start sprinting with double movekey and then press and hold the sprint key while still holding the movekey, releasing the sprintkey should stop the sprinting.

wouldn't that once again conflict with the traitorchat? because shift is still the default, right?

**Comment by TimGoll** [comment]
> > If you start sprinting with double movekey and then press and hold the sprint key while still holding the movekey, releasing the sprintkey should stop the sprinting.
> 
> wouldn't that once again conflict with the traitorchat? because shift is still the default, right?

Yes. But if you unbind your sprintkey, the feature is disabled. We won't disable sprint on shift as a default since it is useful for most of the palyers. Those that do not like this feature can disable it for themselves.

**Comment by menof36go** [comment]
[This pull request] implements the requested feature (https://github.com/TTT-2/TTT2/pull/435)
