### ISSUE TITLE
Spectator Bug

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#434]
**Describe the bug**
After the commit 7721342c87ac6f3c1b775ff22630169cec26d6a2, when someone's killed he instantly goes into spectator for some reason.
Until 7eca7e28ce852c083f004dc2d556e1410a2220c5 all worked fine

**Comment by TimGoll** [comment]
does it still work with the second commit you mentioned? because I've just seen that there is a typo

**Comment by ThePlatinumGhost** [comment]
yes it still work in 7eca7e28ce852c083f004dc2d556e1410a2220c5

**Comment by TimGoll** [comment]
okay. Could you describe the issue a bit more? What do you mean by "he instantly goes into spectator"? For me, nothing has changed here

**Comment by ThePlatinumGhost** [comment]
I can do a video wait

**Comment by TimGoll** [comment]
thanks! And please check if there is an error

**Comment by ThePlatinumGhost** [comment]
No error in Server/client side console

https://youtu.be/_Y8B_Op_oWc
I also test with player and it does the same bug

**Comment by TheNickSkater** [comment]
I can confirm this error.

**Comment by TimGoll** [comment]
Oh, I see. I have the same problem!

**Comment by TimGoll** [comment]
should be fixed by https://github.com/TTT-2/TTT2/commit/acad8d2eb6954a7c708499f95ac787beefb244a5

**Comment by TimGoll** [comment]
Nick confirmed that it works now
