### ISSUE TITLE
[REWORK] Weapon Switching

### ISSUE THREAD

**Issue by Alf21** [TTT-2/TTT2#445]
Is this still a thing in gmod? Maybe we need to keep this in mind with the new weapon switching system. What, if you have an empty weapon that can't be selected and you can't drop it, so it is blocking a slot? https://github.com/TTT-2/TTT2/blob/5125ea729e03a93efa20f722a4f28fffef6a20ff/gamemodes/terrortown/gamemode/server/sv_weaponry.lua#L509

**Comment by TimGoll** [comment]
Interesting fact. But I haven't had any problems with spawned weapons. So this seems to be fixed? (Even with weapons without any ammo inside)

**Comment by saibotk** [comment]
@menof36go also did test this extensively, so did you observe any issues with this?

**Comment by saibotk** [comment]
@TimGoll and me did some testing on this, and took a look at the wiki etc. but could not find any issue with this. This does not seem to be a problem anymore, so I'm closing this for now.
