### ISSUE TITLE
Manually drawing elements from HUD ForceElement

### ISSUE THREAD

**Issue by timschumi** [TTT-2/TTT2#447]
**Is your feature request related to a problem? Please describe.**
I'm trying to reenable TTT2 compatibility for a addon I use, [TTT Spectator Deathmatch](https://github.com/Tommy228/TTT_Spectator_Deathmatch/). As far as I can tell, it doesn't do any modifications on the HUD, however, the creator decided to [draw some HUD elements manually](https://github.com/Tommy228/TTT_Spectator_Deathmatch/blob/master/lua/cl_specdm_hud.lua#L114).

Previously, this wasn't a problem, since the storage for WSWITCH and MSTACK (or rather, their Draw() function) was accessable publicly. However, it broke with commit 9427393ad065bc068ca3a634f767f110c894c3a5, where those HUD elements got converted to a new system.

**Describe the solution you'd like**
Provide (or point out) a way to draw a single `old_ttt_\*` HUD element, preferrably by making the Draw() method accessible.

**Describe alternatives you've considered**
If the above isn't possible, suggestions on how to rework the HUD system of the other addon to be compatible with TTT and TTT2 would be nice (I'll take some time to understand _why_ those elements are drawn one-by-one to ease the effort).

**Comment by TimGoll** [comment]
@TheNickScater and I looked through the Code of this addon recently. Honestly, it is a mess. I don't know why, but he overrides a huge amount of gamemode hooks that therefore break many TTT2 features. Nick has fixed it in a hacky way, maybe you too can create a stable version together.

**Comment by saibotk** [comment]
I think we could make the playerinfo element a bit more modular as to split up the single elements draw functions so they can be called by elements deriving from it. As i now saw that multiple elements, are nearly a copy of the main element instead of a subclass

**Comment by saibotk** [comment]
I looked further into this and i do not see any chance/need to adjust the playerinfo element anymore.
