### ISSUE TITLE
Players don't get roles.

### ISSUE THREAD

**Issue by stebar2015** [TTT-2/TTT2#465]
Version: v0.5.7b

description:
I have installed TTT2 and some roles.
However, no player gets a role.
When I type ttt_roles_index all roles come.
ttt_toggle_role [ROLE_INDEX] works too.
ttt_force_role [ROLE_INDEX] does not work.
Is there a way to find out why the roles are not going?

Workshop version:
https://steamcommunity.com/workshop/filedetails/?id=1357204556
(TTT2 (Base) - v0.5.7b - New Roles, Extensible, Better Performance, ULX Support)

errors in the server console:
I did not find any errors in the console.

**Comment by TimGoll** [comment]
Have you checked the FAQ? https://github.com/TTT-2/TTT2/wiki/faq

But thanks for this great report, for once someone lists his version!

**Comment by stebar2015** [comment]
Yes, I have read the FAQ.
As far as I know there is nothing on this topic.

**Comment by TimGoll** [comment]
Q07

**Comment by stebar2015** [comment]
Oh sorry I missed that.
Thank you.

**Comment by TimGoll** [comment]
Does it work now?

**Comment by stebar2015** [comment]
yes.
