### ISSUE TITLE
Jester gewinnt, wenn er sich durch die Konsole tötet

### ISSUE THREAD

**Issue by Creyox** [TTT-2/TTT2#468]
Hi, 

ich wollte mal kurz melden, dass ich vor ca. 2 Tagen auf meinem Server mitgekriegt habe, dass es möglich ist, sich als Jester per "kill" in die Konsole zu töten und dabei zu gewinnen.

Interessant für euch sind bestimmt die Winstates aus der Config:

ttt2_jester_winstate_6 0
ttt2_jester_winstate_5 0
ttt2_jester_winstate_4 0
ttt2_jester_winstate_3 0
ttt2_jester_winstate_2 0
ttt2_jester_winstate_1 0
ttt2_jester_winstate_0 1
ttt2_jester_winstate 1

Die TTT2 Version ist v0.5.7b, die auf dem Server verwendete Collection könnt ihr euch gerne hier angucken: https://steamcommunity.com/sharedfiles/filedetails/?id=849222406

Wenn ihr noch Fragen habt, nur her damit

**Comment by LunexKun** [comment]
Das der Jester sich selbst per Konsolenbefehl umbringen kann ist bereits seit langer Zeit bekannt.
Danke trotzdem für deinen Bugreport. :)
Soweit ich weiß ist dem Jester in "naher zukunft™" ein rework angedacht. Weiteres ist also abzuwarten. :)

**Comment by Creyox** [comment]
Oh, okay xD Besser ein mal zu viel gemeldet als ein mal zu wenig :)

**Comment by TimGoll** [comment]
@Lunex, der Jester wurde am WE von mir schon komplett neu geschrieben. Werde es testen ob jetzt auch der Konsolenkill Bug gefixt ist
