### ISSUE TITLE
no clue error 

### ISSUE THREAD

**Issue by m00n21** [TTT-2/TTT2#469]
Lua Error:
[Trouble in Terrorist Town 2 (Advanced Update) - v0.5.5b] gamemodes/terrortown/entities/entities/ttt_traitor_button/shared.lua:13: Calling net.Start with unpooled message name! [ http://goo.gl/qcx0y ]
1. Start - [C]:-1
2. fn - gamemodes/terrortown/entities/entities/ttt_traitor_button/shared.lua:13
3. Run - addons/ulib/lua/ulib/shared/hook.lua:109
4. unknown - gamemodes/terrortown/gamemode/client/cl_main.lua:109

**Comment by TimGoll** [comment]
Version? Steps to reproduce?

**Comment by Histalek** [comment]
We really need you to supply the version and a description of the bug.  Closed for now
