### ISSUE TITLE
Multiple Bugs - (Announcement and name display)

### ISSUE THREAD

**Issue by Creyox** [TTT-2/TTT2#473]
Hey, ich baller mal einfach alle Bugs raus, die mir in der Version 0.6b aufgefallen sind:

**Bugs:
1.** Namen werden doppelt angezeigt, beim Detective wird zusätzlich dieser Text in blau (manchen) Spielern angezeigt (hat bei mir nichts mit deutsch oder englischer Sprache zu tun)
![ttt_bb_teenroom_b20006](https://user-images.githubusercontent.com/54220297/74691547-7de7f100-51e3-11ea-960d-051b2ab1c460.jpg)
![ttt_bb_teenroom_b20007](https://user-images.githubusercontent.com/54220297/74691545-7cb6c400-51e3-11ea-8552-fbd349ef5135.jpg)

**2.** Der Jester wird oben rechts zwei Mal angekündigt
![ttt_waterworld_remastered0008](https://user-images.githubusercontent.com/54220297/74691546-7de7f100-51e3-11ea-9094-67afc84d9b97.jpg)

**3.** (Leider kein Screenshot) Wenn man Traitor ist und ein Jester in der Runde spawnt, erscheint in der oberen rechten Nachricht nur der Placeholder '{player_name}' für den Namen des Jesters. 

**Server-Collection:** https://steamcommunity.com/sharedfiles/filedetails/?id=849222406
**Version:** 0.6b (Im Workshop steht 0.6.1b, im Log aber nur 0.6b, obwohl die ja eigentlich direkt mitgeupdatet wird...

**Comment by saibotk** [comment]
@Creyox Könntest du den Bug mit dem Jester bitte nochmal im https://github.com/TTT-2/ttt2-role_jes Repository als eigenes Issue aufmachen? Das macht es für uns einfacher. 
Und der 1. Bug tritt mit einer reinen TTT2 Installation nicht auf, habt ihr irgendwas zusätzlich installiert oder parallel noch ne alte Version installiert?

**Comment by Creyox** [comment]
@saibotk Jo klar, hab ich verpeilt, bin schon so dran gewöhnt, dass ich davon ausgehe, dass der Jester einfach dazugehört :)
Ich habe jetzt alle Addons vom Server runtergeschmissen und neu aus dem Workshop runterladen lassen. Gleichzeitig habe ich alle custom Addons gelöscht und auch die Language-Dateien, um zu gucken, ob ich nicht irgendwas geändert habe. Alles davon führt zum selben Ergebnis wie oben. Dieser Bug tritt aber erst seit gestern auf, es gab da glaub ich auch ein Garrys Mod Update... 
Hier ist die Log, falls Sie euch interessiert: https://pastebin.com/eZZfVXKh

**Comment by TimGoll** [comment]
Hast du ein Screenshot zu 1? Vllt kann ich sagen woher das kommt

**Comment by Creyox** [comment]
Die ersten beiden Screenshots beziehen sich nur auf diesen Bug. 
![ttt_bb_teenroom_b20007](https://user-images.githubusercontent.com/54220297/74720394-04c5b980-5236-11ea-95bc-dae3c36d8217.jpg)

Wenn ihr es euch selbst angucken wollt, das ist die Server IP: 94.16.118.98

**Comment by TimGoll** [comment]
Oh, die GitHub App zeigt wohl keine Bilder an. Gut zu wissen.
Das sieht so aus als würde ein zweites Addon targetID zeichnen. Und da targetID Clientseitig ist, bitte auch mal den Client Cache clearen

**Comment by Creyox** [comment]
Ich bin aktuell nicht zuhause, werde dann aber gucken.

Tim Goll <notifications@github.com> schrieb am Di., 18. Feb. 2020, 10:11:

**Comment by TimGoll** [comment]
Habe es mir gerade nochmal am großen Bildschirm angeschaut. Ja, du hast das neue targetID und das alte. In unserem TTT2 ist aber kein Sourcecode mehr vom alten drin.
Also hast du entweder was im cache, oder irgendein Addon fügt das auch hinzu

**Comment by Creyox** [comment]
So also das verantwortliche Addon war dieser Advanced Disguiser: https://steamcommunity.com/sharedfiles/filedetails/?id=610632051

Jetzt sind alle Anezigefehler weg, auch die des Detectives.
