### ISSUE TITLE
revive function overhaul

### ISSUE THREAD

**Issue by TheNickSkater** [TTT-2/TTT2#475]
The Revive function in sh_player_ext.lua should be reworked.

It currently only counts as revived if you were already dead AND confirmed. This function should always return true, if you were revived, not just if you got confirmed.

Suggestion: Rename the current function and make a second one, or change the current one.

**Comment by Alf21** [comment]
1. Müsste MaxHealth nicht vor dem Revive gesetzt werden? https://github.com/TTT-2/TTT2/blob/211faabdeadc9e1f05a022f64bfa2e28b5a346ea/gamemodes/terrortown/gamemode/server/sv_player_ext.lua#L874 (oder capt das das Health automatisch runter?)

2. credits var is unnötig?: https://github.com/TTT-2/TTT2/blob/211faabdeadc9e1f05a022f64bfa2e28b5a346ea/gamemodes/terrortown/gamemode/server/sv_player_ext.lua#L876

3. Fehlende Translation: https://github.com/TTT-2/TTT2/blob/211faabdeadc9e1f05a022f64bfa2e28b5a346ea/gamemodes/terrortown/gamemode/server/sv_player_ext.lua#L890 und bisschen weiter drüber

4. https://github.com/TTT-2/TTT2/blob/211faabdeadc9e1f05a022f64bfa2e28b5a346ea/gamemodes/terrortown/gamemode/server/sv_player_ext.lua#L872 wie wäre es, der PlayerLoadout Funktion mit zu übergeben (oder eine Funktion einzubauen), ob es ein Revive ist oder das erste Loadout mit der gleichen Rolle
zu 4.: Problem kommt nämlich, wenn man als Rolle eine Waffe bekommt, die droppable ist, stirbt und dann revived wird. Dann hat man noch eine Waffe
Das intern abzuhandeln is nämlich doof, denn was, wenn ein Rollenwechsel stattfindet oder gar Innocent->Sidekick->IwasAnderes->Sidekick wird. Sind Edge-Cases, aber so als Idee
Könnte man entweder über ne extra Variable ODER eine optionale CheckFuntion lösen

**Comment by TimGoll** [comment]
Ich glaube hier gibt es ein Missverständnis. Nick redet nicht von der Revive Funktion, sondern von den Funktionen fürs Miniscoreboard. Sowas wie `ply:IsRevived()` etc. Und ja, die müssen reworked werden.
