### ISSUE TITLE
TTT2 Errors and Causes Issues when running other gamemodes

### ISSUE THREAD

**Issue by ColeyG** [TTT-2/TTT2#476]
- 0.6bh

In other game modes (in my case extreme football throwdown) ttt 2 causes the following error to be thrown in console.

```lua
[TTT2 v0.6b-h1] lua/bind/cl_init.lua:85: attempt to index global 'HELPSCRN' (a nil value)
  1. fn - lua/bind/cl_init.lua:85
   2. unknown - lua/ulib/shared/hook.lua:109
```
Otherwise, game specific binds don't work related to other game modes when in that game mode.

**Comment by Histalek** [comment]
Is there any reason you have 2 different custom gamemodes installed on your server? 

Also i have trouble understanding what you exactly mean with 
> Otherwise, game specific binds don't work related to other game modes when in that game mode.

could you elaborate on that one?

**Comment by ColeyG** [comment]
Hi!

So the server in question is just a variety server that we switch back and forth from different gamemodes. Since the recent update (0.6) whenever we switch to gamemodes other than TTT 2, we see the posted error in the console, and the server is really glitchy. For example, for some reason the error causes our "extreme football throwdown" gamemode to not control properly. Namely some control binds don't do anything. 

I hope this helps!

**Comment by ColeyG** [comment]
I've done a little bit more digging and can confirm that any other game mode does in fact produce the same issue on a server with the update of TTT 2. In this case I tested prop hunt. Is there a consistent way to roll back versions? In my case I am using the workshop integration to mount the addon but perhaps using an older version would help?

**Comment by TimGoll** [comment]
using an older version would be to roll back all TTT2 addons as well

**Comment by ColeyG** [comment]
> using an older version would be to roll back all TTT2 addons as well

Hmmm, we use a number of custom TTT2 roles so that seems like a lot of overhead. Perhaps I won't try that.

**Comment by TimGoll** [comment]
Hmm, maybe I can fix this bug. Is this the only/first error?
And why/how does that happen at all? The files shouldn't be loaded at all

**Comment by ColeyG** [comment]
Thanks! So yeah, that is the only error in console. The error mentioned is just repeated over and over again. When the server switches to a game mode other than TTT2 that script gets loaded for some reason and I am not sure why (and the TTT2 gamemode does work fine). Another hint is that the update recently definitely had some effect on this script as the server didn't have the issue previously. I've joined the discord too in case you need any other questions answered. (Coley#1457)

**Comment by TimGoll** [comment]
Are you completely sure? Maybe there is something prior to the spam.
I will look into it tomorrow. But honestly I have no idea right now

**Comment by ColeyG** [comment]
Yeah, the top of the log is only slightly different. Just being a variation of the other error with the opening cut off:

```
it.lua:85: attempt to index global 'HELPSCRN' (a nil value)
  1. fn - lua/bind/cl_init.lua:85
   2. unknown - lua/ulib/shared/hook.lua:109
```

**Comment by Alf21** [comment]
Okay I'll keep this alive:

1. Does this error still happen after the 0.6.2b update?
2. Can you please send the complete log file? To speed this process up, it would be great if you could start your server, directly try to reproduce this error and when it's happen, stopping it.
3. What do you mean with "custom gamemodes" or your "extreme football throwdown" gm? What's it exactly?
4. What addons are you using? Please send your WS-Collection and maybe create a list of your addons placed in the server's /addons folder.
5. Could we test the issue together? We should talk about a meeting on the discord.

These steps should be done one by one. If we don't get a result, it would be great if you go to the next step on your own.
Anyways thanks for your report, we wanna fix this issue too. But it seems to be hard to reproduce.
