### ISSUE TITLE
New Update (?) - Server doesnt change automatically to TTT2 anymore

### ISSUE THREAD

**Issue by Creyox** [TTT-2/TTT2#479]
Hey,

today I was working on my server and I noticed a severe bug: When I join this error is printed in the console:

```
TTT initializing convar settings...
L 03/01/2020 - 16:05:46: "Crysis<2><STEAM_0:1:61702499><>" entered the game
[rlib] 04:05:51 [info]      |  [pco] » [ Crysis ] set mode [ enabled ]
[Crysis|2|STEAM_0:1:61702499] Lua Error:

[ERROR] gamemodes/terrortown/gamemode/vgui/sb_main.lua:373: attempt to index field 'hostname' (a nil value)
  1. unknown - gamemodes/terrortown/gamemode/vgui/sb_main.lua:373


[Crysis|2|STEAM_0:1:61702499] Lua Error:

[ERROR] gamemodes/terrortown/gamemode/vgui/sb_main.lua:373: attempt to index field 'hostname' (a nil value)
  1. unknown - gamemodes/terrortown/gamemode/vgui/sb_main.lua:373


[Crysis|2|STEAM_0:1:61702499] Lua Error:

[ERROR] gamemodes/terrortown/gamemode/vgui/sb_main.lua:297: attempt to index field 'ply_groups' (a nil value)
  1. unknown - gamemodes/terrortown/gamemode/vgui/sb_main.lua:297


[Crysis|2|STEAM_0:1:61702499] Lua Error:

[ERROR] gamemodes/terrortown/gamemode/cl_hud.lua:193: attempt to index local 'L' (a nil value)
  1. SpecHUDPaint - gamemodes/terrortown/gamemode/cl_hud.lua:193
   2. unknown - gamemodes/terrortown/gamemode/cl_hud.lua:331


[Crysis|2|STEAM_0:1:61702499] Lua Error:

[ERROR] gamemodes/terrortown/gamemode/cl_hud.lua:193: attempt to index local 'L' (a nil value)
  1. SpecHUDPaint - gamemodes/terrortown/gamemode/cl_hud.lua:193
   2. unknown - gamemodes/terrortown/gamemode/cl_hud.lua:331
```
My start parameters:
```
## Server Start Settings | https://docs.linuxgsm.com/configuration/start-parameters
ip=""
port="27015"
clientport="27005"
sourcetvport="27020"
defaultmap="ttt_minecraft_b5"
maxplayers="12"
tickrate="66"
gamemode="terrortown"
```
It seems as if something with TTT2 changed, because yesterday everything worked fine. Here's a screenshot of the bug:
![20200301160605_1](https://user-images.githubusercontent.com/54220297/75628319-0731f700-5bd8-11ea-8fbf-a845c93df4ab.jpg)
![20200301160617_1](https://user-images.githubusercontent.com/54220297/75628320-08632400-5bd8-11ea-8282-5ef6046db6b0.jpg)

I already figured out, why this happens: The server doesn't change the gamemode to TTT2 automatically when starting up. I can't tell you the exact version of TTT2, because it's not loaded and in conclusion to this not printed in the log, but it has to be the latest released workshop version. You can review the whole log here: https://pastebin.com/RUW5yAe6

I rollbacked my server to a backup I made the 17th of February (where everything worked) and the error still happened, so something must have changed... 

Id be grateful if you would fix this bug, because at the moment the whole server is not usable. Maybe I'm dumb and just have to change the start parameters to "terrortown2" or whatever...

Thanks for you work :D

**Comment by Creyox** [comment]
I forgot the server collection: https://steamcommunity.com/sharedfiles/filedetails/?id=849222406

**Comment by Alf21** [comment]
Hey there, thanks for the report :)
I reverted the version back to the one from yesterday in order to investigate your reported bug. Could you try to test again? If it's working now, there seems to be a new bug we are going to fix asap.

**Comment by Creyox** [comment]
Okay the error doesn't exist anymore. Seems as if this is a bug in the newest version. Thanks for the quick reaction

**Comment by Alf21** [comment]
Okay ty for the fast response. Could you please list the addons that are stored in your server's /addons folder too ? :)

**Comment by Creyox** [comment]
I got 3 more addons: Rlib, TTT-SB-Ranks and luneramotd
https://github.com/Decicus/TTT-Scoreboard-Ranks-for-ULX
https://github.com/im-richard/rlib

**Comment by Alf21** [comment]
Okay we think that the gmod update tool created some corrupted .gma files, so I retried again and updated to the newest version 0.6.2b. If you have some time, feel free to test again and respond, whether it's fixed :)

**Comment by Creyox** [comment]
Seems fixed to me

**Comment by Alf21** [comment]
Haha o.O Then we need to say thanks to the gmod updating tool, happens quite often :(
Feel free to report anything else you noticed, even ideas or add-on ideas: https://github.com/TTT-2/addon-ideas

**Comment by Creyox** [comment]
Yeah I'll do and already did ;P
