### ISSUE TITLE
Materials are missing

### ISSUE THREAD

**Issue by tominal** [TTT-2/TTT2#486]
- TTT2 Base - v0.6.3b
- Materials missing completely. Materials are correctly bzipped in the webserver.

I overwrote the existing terrortown files with TTT2's Github files because TTT2 alone would not function at all. I must be missing something here. There are no docs for server setup.

![image](https://i.imgur.com/UUqyt2o.png)

**Comment by saibotk** [comment]
The workshop version should work out of the box and should be the way to go.
If you still decide to use the Github version (might be unstable), the gamemode already does at all files to FastDL. You might need to check your FastDL / Server configuration, as for FastDL you would need an additional webserver and the following configs enabled:
```
sv_downloadurl "http://YOURFASTDLDOMAIN.com/fastdl"
sv_allowdownload 1
```

You might want to take a look at LinuxGSM and their tutorial on this topic: https://docs.linuxgsm.com/commands/fastdl

Documentation for server setup are work in progress, as we are currently writing the documentation / API documentation. But general server setup should work as with every other gmod addon, as this is just another addon that can be added to your game / collection and works out of the box.

**Comment by tominal** [comment]
Got it. I'm old fashioned so I like the fastdl side of things. I'll extract the workshop addon and give it a shot.
