### ISSUE TITLE
bug voip

### ISSUE THREAD

**Issue by vin350** [TTT-2/TTT2#487]
## Disclaimer

If you are missing the following information your issue will be closed!

- "v0.6.3b"
- "I press the traitor's voip key (I can speak normally), then when I press everyone's voip key the traitor's voip is active, after about 10 seconds it returns to normal.
(it always happened)"

Also please make sure to read the [FAQ](https://github.com/TTT-2/TTT2/wiki/faq) first!

## Your version of TTT2 (mandatory)

Leave one of the following:

- v0.6.3
- I don't use github
- I don't use github

## Video

https://youtu.be/XQyhjD6iyH4

## Describe the bug (mandatory)

https://youtu.be/XQyhjD6iyH4

## To reproduce

Steps to reproduce the behaviour:

1. press the traitor's voip button
2. then press the voip key of all

## Expected behaviour

when I press the traitor's voip I speak to traitors and when I press everyone's voip I speak to everyone.

## Context (please provide as much as you can)

- https://steamcommunity.com/sharedfiles/filedetails/?id=2016463733
- https://pastebin.com/YbeZPBjT
- https://pastebin.com/qvvhhA2G
- simplecommands, pointshop2, atlaschat

## Additional context

[addons.zip](https://github.com/TTT-2/TTT2/files/4364594/addons.zip)

**Comment by Histalek** [comment]
You have multiple incompatible addons installed.

> https://pastebin.com/YbeZPBjT
Please remove those addons / use the listed alternatives and try again.

If the problem still happens after you did that, you can reopen this issue :)

**Comment by TimGoll** [comment]
https://docs.ttt2.neoxult.de/troubleshooting/

Here are some further information that you should read
