### ISSUE TITLE
HUD elements not rendering when contained in different addons

### ISSUE THREAD

**Issue by Blast1113** [TTT-2/TTT2#490]
TTT2 v0.6.3b

When using my [custom HUD](https://steamcommunity.com/sharedfiles/filedetails/?id=2033174705),
Elements from other addons do not draw unless I use `self:ForceElement(element name)` in `cl_init.lua`.
The [other addon](https://steamcommunity.com/sharedfiles/filedetails/?id=2035029508).

It does run the `PreInitialize`, `Initialize`, and `GetDefaults` functions, but never runs the `Draw` function.

This may not be a bug and could just be a mistake I made, but I can't find anything different about my HUD than the default ones, including the element defined in the original vampire HUD.

**Comment by TimGoll** [comment]
Your PreInit has to look like this:

```lua
function HUDELEMENT:PreInitialize()
	BaseClass.PreInitialize(self)

	local hud = huds.GetStored("octagonal")
	if hud then
		hud:ForceElement(self.id)
	end

	-- set as NOT fallback default
	self.disabledUnlessForced = true
end
```

**Comment by TimGoll** [comment]
BUt looking at your addon... why did you add so may convars for the size? You have seen our HUD editor?

**Comment by Blast1113** [comment]
I probably should use the HUD editor (I might do that later). It currently doesn't because a lot of the code is directly copied from my older HUD.

That PreInit code worked perfectly! Thank you very much.

**Comment by TimGoll** [comment]
take a look at our documentation: https://docs.ttt2.neoxult.de/developers/content-creation/creating-a-hud-theme/ (still WIP)
If you derive from the `scaleable HUD` all things needed for the dynamic scaling are already done

**Comment by TimGoll** [comment]
Another FYI: I don't know what you're doing with your addon, but it breaks all my HUDs

**Comment by Blast1113** [comment]
It may need some other roles installed, but it seems to work fine for me with just the jester.
![asdfasdfasdfasdfasdf](https://user-images.githubusercontent.com/6200238/77568429-84dbe080-6ec0-11ea-916e-dadd297d9de5.png)

**Comment by TimGoll** [comment]
Another question: You know about this addon, don't you?

**Comment by Blast1113** [comment]
I know mine looks very similar to that one (and was originally based off it) but there are a lot of things I don't like about it.

**Comment by Blast1113** [comment]
Plus, there were some extra features I wanted.
