### ISSUE TITLE
Unable to pickup weapons using "E"

### ISSUE THREAD

**Issue by RatchetRussian** [TTT-2/TTT2#492]
I am having an issue where I cannot pickup weapons by looking at them and pressing "E"

I am able to pick up 1 weapon at which point I get a "TTT2 is creating script errors" message and this is shown in the console: 

```
[TTT2 v0.6.3] gamemodes/terrortown/gamemode/server/sv_player_ext.lua:1262: attempt to concatenate a nil value
  1. PickupWeapon - gamemodes/terrortown/gamemode/server/sv_player_ext.lua:1262
   2. func - gamemodes/terrortown/gamemode/server/sv_weapon_pickup.lua:59
    3. unknown - lua/includes/extensions/net.lua:32
```

After this, trying to press E on any other weapons yields a message saying 
`You already picked up a weapon, wait until you receive it`

Is it possible that using custom weapons is causing this?

**Comment by RatchetRussian** [comment]
I apologize for jumping to this conclusion so quickly without further testing on my part. This problem only occurred when running the game locally and not on a dedicated server. I test all my server addons locally before pushing any updates to my server. 

This feature is working perfectly now that I tested it from my dedicated server and I thank you for this simple but infinitely superior weapon switching system!

**Comment by TimGoll** [comment]
I'm glad it is working now. However I'm always testing things locally and I had never any problems
