### ISSUE TITLE
Add categories to the shop

### ISSUE THREAD

**Issue by PayZuni** [TTT-2/TTT2#494]
I think the traitor/detective shop can get pretty confusing when a lot of Traitor/Detective Item addons are installed.

To make the shop easier to handle. I'd like to have categories which either the server admin or any player can create to sort the items.

The only alternative I could find was the favorites system, which is already implemented. However I think that the favorites system is very limited and doesn't solve the aforementioned problems.

 I created a quick mockup to show how this could look: 
![Desktop - 1](https://user-images.githubusercontent.com/17912127/78123709-e0512580-740e-11ea-88b5-0bfcb45623f4.png)

**Comment by TimGoll** [comment]
Actually we're already at a rework and this is planned!
But feel free to suggest more detailed ideas

**Comment by PayZuni** [comment]
Thanks, for the quick response :)
This is very good news. I sure will suggest more ideas if I come up with more features. I might even consider contributing code if I have the time to do so.

**Comment by TimGoll** [comment]
https://github.com/TTT-2/TTT2/pull/480

This pullrequest is the base for the vgui rework and changes the F1 settings screen. Based on that, the shop and all other menues will be reworked as well. Feel free to check it out
