### ISSUE TITLE
Showing the team instead of the role before the name in team chat

### ISSUE THREAD

**Issue by Pythagorion** [TTT-2/TTT2#495]
**Is your feature request related to a problem? Please describe.**
I have started programming a Traitor role for TTT2: The Lion.  The problem: TTT2 just shows the role and not the team, so the Lion will be detected as soon as he uses the chat once.

**Describe the solution you'd like**
Roles should be shown as their team in the team chat and not as their role.

**Describe alternatives you've considered**
An alternative might be a function or something similar, so that you as the coder can individually define what is displayed before the name in the team chat.

**Additional context**
![unknown](https://user-images.githubusercontent.com/43889730/78130673-0b8d4200-741a-11ea-9646-bfe96e0779b5.png)

**Comment by Alf21** [comment]
That's an issue on your side. The client just uses the data he has to use. If you send the wrong (or in that case the faulty correct) data, this happens. Instead, you should modify the role (that is send by the server to the client), so that the clients just receive the Lion as a normal traitor. Otherwise, you will run into several other issues (scoreboard, voicechat, etc.).

**Comment by Pythagorion** [comment]
> That's an issue on your side. The client just uses the data he has to use. If you send the wrong (or in that case the faulty correct) data, this happens. Instead, you should modify the role (that is send by the server to the client), so that the clients just receive the Lion as a normal traitor. Otherwise, you will run into several other issues (scoreboard, voicechat, etc.).
> 
> Ref.:
> 
> https://github.com/TTT-2/TTT2/blob/783ef7e7b7a5881ee800b1b117920eb43fe81f71/gamemodes/terrortown/gamemode/client/cl_chat.lua#L43
> 
> // edit: Additionally I'm against the team display. If a team member is using the **team** chat, you already know his team - it's yours. So this would be a redundant data. Instead, showing the exact (known) role is relevant for the gameplay.

Ah. That´s interesting. I understand the problems, but I can´t follow at the point where you explain how I can change the data that is sent. How can I change this data, you told me about?

**Comment by Alf21** [comment]
> > That's an issue on your side. The client just uses the data he has to use. If you send the wrong (or in that case the faulty correct) data, this happens. Instead, you should modify the role (that is send by the server to the client), so that the clients just receive the Lion as a normal traitor. Otherwise, you will run into several other issues (scoreboard, voicechat, etc.).
> > Ref.:
> > https://github.com/TTT-2/TTT2/blob/783ef7e7b7a5881ee800b1b117920eb43fe81f71/gamemodes/terrortown/gamemode/client/cl_chat.lua#L43
> > 
> > // edit: Additionally I'm against the team display. If a team member is using the **team** chat, you already know his team - it's yours. So this would be a redundant data. Instead, showing the exact (known) role is relevant for the gameplay.
> 
> Ah. That´s interesting. I understand the problems, but I can´t follow at the point where you explain how I can change the data that is sent. How can I change this data, you told me about?
> 
> edit: Wait. TTT2 uses the SubRole to be printed in the chat? So if I give the Lion the SubRole Traitor it should show traitor in the chat or do I mistaken?

Changing this data is something we called „Role Hacking“ before, now it isn‘t hacky anymore. You just have to use a specific hook and modify the data that is send to the clients. Here, you can give a look into the code of the Spy, that should match your case perfectly: https://github.com/TTT-2/ttt2-role_spy/blob/2022d7f70fa3296aa658a064d34f320f90d84944/lua/terrortown/entities/roles/spy/shared.lua#L51

**Comment by TimGoll** [comment]
I think it can be closed as it is resolved and nothing that should be done on the TTT2 side.
