### ISSUE TITLE
Fresh installation, small approved addon list, missing UI textures

### ISSUE THREAD

**Issue by Fires1** [TTT-2/TTT2#497]
v0.6.3b

Seem to be missing the border texture for these pure skin elements

https://i.imgur.com/31G4Byb.png and https://i.imgur.com/VBqOvyf.png and finally https://i.imgur.com/PenLMG4.jpg

I also am missing the scoreboard icon https://i.imgur.com/X5Mb70x.png

This is my collection: https://steamcommunity.com/sharedfiles/filedetails/?id=2043978888

I downloaded ALL my addons in the collection and FastDL'ed any sort of material, model or particle. Including the direct material content from TTT2 itself. I've tried subscribing to the collection as well and its still missing

**Comment by Fires1** [comment]
Just found #486, looking into his solution

**Comment by TimGoll** [comment]
It's not missing, you're doing something wrong here. And you don't need fastDL for TTT2. However, TTT2 includes the files needed for fastDL if you really want to use it.

**Comment by Fires1** [comment]
Going to attempt to remove all FastDL items pertaining to TTT2 and clean my collection out of everything so it'll just be TTT2, **it IS inside my collection**, so I'm not sure what could be going wrong.

**Comment by TimGoll** [comment]
It might be, with an emphasis on *might*, that a combination of fastDL with TTT2 from the workshop does not work. TTT2 includes all files needed for fastDL server. Did you add the materials to your fastDL server? Otherwise it might fail to download them.

But honestly I have no idea.

**Comment by Fires1** [comment]
I agree it could be possible due to combining the two. I'll let you know since I'm testing it within the next 10 minutes.

**Comment by Fires1** [comment]
Garry's Mod issue!

If anyone has this happen in the future, don't use FastDL, use the workshop(like recommended), if it gets all fucked up, restart your game. Completely fixed the issue for me. Feelin dumb.

**Comment by TimGoll** [comment]
We all love GMod and its issues!
