### ISSUE TITLE
Console error (maybe connected with hold to aim)

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#498]
Sometimes this error appears in the console, I have not yet well deduced the triggering event, I have been trying to understand why this error has happened for a while

[ERROR] addons/ttt2-master/gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:833: attempt to call method 'GetIronsights' (a nil value)
  1. fn - addons/ttt2-master/gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:833
   2. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109

I don't know if it's related, but I have the "Hold to aim" option on
I say this because many users who don't have this option never happened to him
This error is client side

**Comment by Histalek** [comment]
It would be good to know which weapons you were using when this error shows up. Most likely it will be a weapon without ironsights, so maybe some traitor/detective weapon? I would suspect something that isn't a gun like a slam mine or something more 'special' like the supersheep maybe?

**Comment by ThePlatinumGhost** [comment]
This is my collection https://steamcommunity.com/sharedfiles/filedetails/?id=1806066645
and I use this weapon pack https://steamcommunity.com/sharedfiles/filedetails/?id=194965598 on my server

**Comment by Histalek** [comment]
I can't test it for now but i'll keep it in mind. If you happen to get any more clues please let us know :)

**Comment by ThePlatinumGhost** [comment]
I will try to replicate it as soon as I have more tests I will post more info
