### ISSUE TITLE
No detective with other roles?

### ISSUE THREAD

**Issue by Fires1** [TTT-2/TTT2#499]
v0.6.3b

I have

* Innocent 0.10
* Traitor 0.24
* Detective 0.16
* Bodyguard 0.15
* Deputy 
* Hitman 0.07
* Sheriff 0.13

Numbers after are the "pct" convar values. 

No idea why because we have 10 players, so we have 2 traitors and no detectives.

Would be curious if someone could explain these pct values.

**Comment by saibotk** [comment]
Thanks for your report! 
The issue is already tracked in #477 and is worked on, but will take some time, as the whole role selection system will be rewritten. Please bear with us.

**Comment by TimGoll** [comment]
Just a quick tip: you might be able to get the detective to spawn with some ideas mentioned in the linked issue
