### ISSUE TITLE
Server doesn't work anymore / Gamemode won't change to TTT2

### ISSUE THREAD

**Issue by Creyox** [TTT-2/TTT2#500]
Hey, 

I just got the report of the people playing on my server, that nothing works anymore. I get the following errors:

https://pastebin.com/SYrXg2RL

I'm not quite sure yet if you released a new version or if it is the pharaoh, because he appears in the error log as well. Unfortunately I can't tell you the current version of TTT2, because my server doesn't change anymore to TTT2 but it's the current workshop version. Here's the complete log:

https://pastebin.com/nk9zzaCU

And by the way: Yesterday everything worked fine and I didn't upload more content, so it has to be an update of an existing addon.
I already deleted all my custom addons to see if this helps, but that's not the problem.

Server workshop collection: https://steamcommunity.com/sharedfiles/filedetails/?id=849222406

**Comment by Alf21** [comment]
Yesterday there was a **tested** TTT2 update v0.6.4b. Some minutes ago, we tested again to validate. It is still working.

I gave a look into your report and it seems that TTT2 is downloaded by the workshop, but not by your custom downloading. There are two options: You custom downloading is buggy and doing wrong caching or the steam cache is bugged. 

What are you using or why are your add-ons downloaded two times??

**Comment by Creyox** [comment]
Okay I removed now all my custom addons, which are not downloaded from the workshop. I didn't know it, but I had two automatic workshop downloader in my collection. I removed them. Then I restarted the whole server without my custom addons and without the workshop downloader. Same error. I thought it may be the role Pharaoh & Graverobber I recently added on my server, so I removed it as well. Still the same error.

**Comment by Creyox** [comment]
I tried removing the TTT2 Base from the collection and mounting it directly on the server. No change though...

**Comment by TimGoll** [comment]
Have you maybe deleted some addons manuall from the new addons path? If you did so, this causes problems because gmod handles addons in a strange way.
Either way, reinstalling your server could fix your problems.

**Comment by Creyox** [comment]
You were right, a clean reinstallation fixed it. Maybe a gmod update broke it, I don't know.
