### ISSUE TITLE
TTT2 downloads assets even though addon is installed on client

### ISSUE THREAD

**Issue by mclucario** [TTT-2/TTT2#505]
## Your version of TTT2 (mandatory)
Steam Workshop Version v0.6.4b

## Describe the bug (mandatory)
When players subscribe to my addon collection and join the server they still need to download additional content directly from my server. I dont see the reason why, everything should be already included when they download the workshop addon.

## To reproduce
1. Create a server with TTT2
2. Let the test client download TTT2
3. Join the server with the client
4. Client should now try to download files from the server.

## Expected behaviour
The client status should say "No files to download." and continue loading shenanigans.

## Context (please provide as much as you can)

- Collection link of your Server:
https://steamcommunity.com/sharedfiles/filedetails/?id=1728154834 (TTT2 isnt included since this is my "production ready" pack)
- **All** Server errors in the server console:
Coming later
- Client errors in the developer console
Coming later
- Other addons installed in your servers `addons` folder
None. I dont use anything external or manually install addons. 
- Screenshots
None. I dont think they are needed.

## Additional context
I wanna provide my players a server where they just need to download the workshop addons and can instantly play. Downloading files from a server without fastdl is slow and setting one up is very cumbersome. Having to do all that extra work doesnt make sense either since its already in the workshop.

**Comment by Histalek** [comment]
Please provide at least some of the files the clients tries to download, screenshots of the progressbar in the lower left corner for example.

**Comment by TimGoll** [comment]
TTT2 ships with a file for fastDL users. Without fastDL the clients shows that he is downloading stuff without actually downloading anything. Maybe you're talking about this?

We thought multiple times about removing the fastDL stuff because it might confuse people.

**Comment by mclucario** [comment]
Ah, I think I found the problem. The TTT2 addon is actually fine. The game just tried to download the files because the addon was downloaded but it was disabled in the addon overview. Looks like the addon wasnt the problem after all. I am sorry.

**Comment by Histalek** [comment]
I'm glad you could resolve this :)

If you have any questions feel free to ask us on our Discord (https://discord.gg/9njYXGY)
