### ISSUE TITLE
Fehlende Übersetzung

### ISSUE THREAD

**Issue by Banane767** [TTT-2/TTT2#526]
**Version von TTT2**: v0.6.4b | Workshop Version
**Getestete Sprache**: Deutsch
**Zum Bug**: Es fehlen jeweils die Übersetzung target_detective & target_traitor. 

Den Fehler habe ich erkannt, falls man Ingame auf die Person schaut (bsp. Bei Detektiv sieht man den Blauen Kreis und darunter steht „[Error : Translation of target_detective not found]“. Dieser Fehler tritt auch bei den Traitorn auf, falls man einen weiteren Traitor im Team hat und auf diesen schaut.

**Comment by TimGoll** [comment]
Kannst du bitte einen Screenshot posten? Danke

**Comment by Banane767** [comment]
![20200429110937_1](https://user-images.githubusercontent.com/58948903/80580702-429c4680-8a0c-11ea-8068-1b0f6b17ef43.jpg)
![20200429110951_1](https://user-images.githubusercontent.com/58948903/80580704-43cd7380-8a0c-11ea-86c9-d785f17ebf36.jpg)

**Comment by TimGoll** [comment]
Do you have the current version? The strings are missing because this is really outdated.

It looks like this:
![image](https://user-images.githubusercontent.com/13639408/80580824-78412f80-8a0c-11ea-9c7f-b4d8abcb4e3b.png)

Also there's something wrong with the HUD outlines

**Comment by Banane767** [comment]
Ich hab die Workshop Version.

Habs eben auch mal mit der Github Version Probiert. Lade ich diese runter, entpacke sie und lade sie in den Addons Ordner auf den Server hoch, kommt ein Error in der Console, wegen dem randomAmmo-Spawning/Entfernen.

Muss deshalb auf die Workshop Edition zurückgreifen, weil diese noch Funktioniert.

**Comment by TimGoll** [comment]
Die Workshop Version hat aber schon das neue targetID. Entweder hast du ein Addon welches targetID überschreibt anstatt es zu modifizieren, oder dein Cache spielt verrückt. Am besten löschst du den mal.

Und die GitHub Version funktioniert definitiv. Nutze die selber beim Entwickeln. Der Error scheint also einen anderen Grund zu haben.

Hast du mal auf den Output vom Addon Checker in der Server Console geschaut? Vielleicht nutzt du ja ein bekanntes Addon, das nicht funktioniert.

**Comment by TimGoll** [comment]
Gerade nochmal GMod geöffnet und getestet, funktioniert wie es soll bei mir.

![image](https://user-images.githubusercontent.com/13639408/80581703-cf93cf80-8a0d-11ea-97d6-53c258870621.png)

**Comment by Banane767** [comment]
Hab eben nochmals nachgeschaut, aber in der Konsole wird mit kein inkompatibles Workshop-/Addon angezeigt. 

Aber hier kannst du, falls du willst, gerne selbst mal nachschauen:
Steam Workshop-Kollektion: https://steamcommunity.com/sharedfiles/filedetails/?id=2072411951
Server-Addons:
![Unbenannt](https://user-images.githubusercontent.com/58948903/80586862-e76f5180-8a15-11ea-8f47-ad8a4df99897.png)

**Comment by TimGoll** [comment]
hm, sehe auch nichts
vielleicht ist bei dir lokal ne alte TTT2 Version gecached oder so. Ich habe ehrlich keine Ahnung. Jedenfalls sind bei dir irgendwelche alten lua-files. TargetID sieht schon lange nicht mehr so aus. Seit dem gab es einige Updates.

**Comment by Banane767** [comment]
Hab den Cache gestern auch schonmal komplett gelöscht.
Da hat sich aber nichts dran geändert.
Übel komisch.

**Comment by Banane767** [comment]
Habe auch bemerkt, dass, falls ich auf die Waffen schaue, keine Informationen oder ähnliches angezeigt wird, was normaler weiße so sein sollte. Irgendwas ist mit der HUD falsch. lol

**Comment by TimGoll** [comment]
Probier es bitte einfach mal ohne die Addons die du manuell installiert hast. Ich kenne die nicht alle, vielleicht ist ja eines davon schuld.

**Comment by Banane767** [comment]
Werd ich mal machen. Ich lösche mal alles vom Server bis auf ulx & ulib... ^^

**Comment by Banane767** [comment]
Keine Wirkung. Immernoch gleich.
Wundert mich extremst.

**Comment by Banane767** [comment]
Ich hab ne Idee. Ich kopiere alles wichtige vom Server und installier den kompletten Bums mal neu.

**Comment by TimGoll** [comment]
Gute Idee. Wir sollten dieses Gespräch dann aber eher auf Discord fortsetzen.
