### ISSUE TITLE
Nicht als Traitor ausgewählt werden

### ISSUE THREAD

**Issue by Banane767** [TTT-2/TTT2#527]
Ich habe auf einem Server ein Problem. Anfangs war es noch Lustig, aber langsam wird es einfach traurig. Ein Kollege von mir wird gefühlt jede Runde Traitor. 
Ich weiß zwar, dass das man zufällig ausgewählt wird, aber mir fehlt die Funktion wie beim Detektiv, sich aus diesem Vorgang auszuschließen. Beim F1 Menü könnte man also eine weitere Checkbox einfügen, welche dies erlaubt.

**Möglicherweise kann es bei der Implementierung davon zu folgendem Problem kommen**: Jeder Spieler hat das Auswählen zum Traitor deaktiviert und somit würde es keine Traitor geben. Dafür sollte man also irgendeine Lösung/Kompromiss finden.

**Comment by EJStile** [comment]
Also ich habe ein ähnliches Problem auf meinem Server
Jedes mal, wenn eine Runde bzw. eine Map lädt, dann fühlt es sich so an, als ob nur ein Teil der Mitspieler Traitor wird bzw. werden kann.

Ich habe probiert ein diesen Mod hier zu installieren, aber leider ist er mit TTT2 leider nicht kompatibel:
https://github.com/lzinga/TTTWeightedTraitorSelection

Ich finde die Idee des Mods von Izinga aber sehr schön und vorallem transparent für die Spieler.
Ich kenne den Aufbau von TTT2 jetzt leider nicht, aber ist es möglich so ein transparentes Traitorselect hier mit einzubauen oder sogar das https://github.com/lzinga/TTTWeightedTraitorSelection für TTT2 an zu passen?

**Comment by saibotk** [comment]
@Banane767 prinzipiell gibt es dein vorhergesehenes Problem schon mal nicht, da wir jetzt schon einfach so dann jemanden auswählen, also so, dass die Checkbox nur eine Präferenz darstellt und keine endgültige Möglichkeit diese Rolle nie zu bekommen. 

@EJStile das stimmt, wir haben das sogar schon länger im Visier bzw. als Idee auf unserer Liste: https://trello.com/c/kRHy6Baf 
Allerdings wird das ganze etwas schwerer mit mehreren Rollen etc. dabei ist es schwierig eine gute Lösung zu finden, die den Großteil der Spieler gerne hätte bzw. der dann auch noch so detailliert einstellbar ist. 
Das Addon ist leider inkompatibel, da es die Funktionen für die Rollenauswahl überschreibt und ändert. Wir werden es mal im Hinterkopf behalten für die zukünftige Rollenauswahlmethode.

Generell sind wir momentan sowieso dabei, die Rollenauswahl umzuschreiben und zu verbessern, da es mehrere Probleme damit momentan gibt, dabei wollen wir im ersten Schritt (https://github.com/TTT-2/TTT2/pull/517) erst einmal den Code aufräumen und erste Probleme beheben, und später dann sowieso die Rollenauswahl noch einmal überarbeiten, also auch anpassbar machen. Dazu sind wir momentan noch in der Planungsphase und überlegen uns dann welche Faktoren wir wie betrachten und einstellbar machen können. 

Dafür ist so ein Feedback natürlich unverzichtbar, vielen Dank euch beiden.
