### ISSUE TITLE
Error bei Installation

### ISSUE THREAD

**Issue by FerbFloo** [TTT-2/TTT2#532]
Immer wenn ich das Spiel starte bekomme ich folgenden Error:

Not loading addon 'F:\SteamLibrary\steamapps\workshop\content\4000\1357204556/ttt2.gma' - addon header invalid
Couldn't mount addon file 'F:\SteamLibrary\steamapps\workshop\content\4000\1357204556/ttt2.gma' from 'TTT2 (Base) - v0.6.4b - New Roles, Extensible, Better Performance, ULX Support' (1357204556)

und der Gamemode wird mir nur im Addons Tab angezeigt, aber nicht unten rechts bei den Gamemodes.

**Comment by TimGoll** [comment]
vielleicht musst du den gamemode neu herunterladen?

**Comment by FerbFloo** [comment]
Hab ich probiert. Außerdem hab ich mal das Verzeichnis gecheckt, in dem des addon angeblich nicht sein soll, und die .gma-Datei war da. Ich habe sie dann manuell in Gmods Addon Ordner kopiert, auch ohne Erfolg.

**Comment by TimGoll** [comment]
Komisch. Ich kann nur sagen, dass es definitiv funktioniert. Wir nutzen auf unserem Server selber die Workshop Version

**Comment by TheSuspect2306** [comment]
garrys mod nicht offen haben während du das addon de-abonnierst und dannach wieder abonnierst das sollte das problem beheben, das ist seit dem facepunch sich entschieden hat irgendwas am workshop system zu machen ka ob es facepunch wirklich war ist ja auch egal

**Comment by saibotk** [comment]
Wenn nochmal was sein sollte, einfach nochmal melden, allerdings sieht es momentan nicht nach einem Fehler mit TTT2 aus. Daher schließe ich das hier vorerst mal.
