### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#536]
## Your version of TTT2 (mandatory)

Leave one of the following:
- Non-latest GitHub version (please provide what you can to specify)

## Describe the bug (mandatory)
from this commits 3f7b0e68b345f216f22e56efbaa8942efa726d2b onwards 
the hud no longer works and i get many errors when i try to join the server

![image](https://user-images.githubusercontent.com/36534723/81298637-53d0fd00-9075-11ea-95d7-d5d22dedcf19.png)

this is last commits that works for me ade8ba4c2555968ff81bb0f912a81ca2aaf9a8b1

obviously i test first on my test server before putting everything
if it is only my error of some kind I will obviously close the post

**Comment by TimGoll** [comment]
do you use some custom HUDs?

**Comment by ThePlatinumGhost** [comment]
nope only from TTT2
octagonal,pureskin

**Comment by TimGoll** [comment]
octagonal is a custom HUD
remove it for now, it will be updated soon

**Comment by ThePlatinumGhost** [comment]
ah okey thanks 
i will check if this error is caused by this

**Comment by TimGoll** [comment]
I've pushed a fix for octagonal. Should work for now

**Comment by ThePlatinumGhost** [comment]
ok i will test!

**Comment by ThePlatinumGhost** [comment]
now work
