### ISSUE TITLE
Double opening

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#542]
As you can see in the screenshot, if you open one door going down the stairs, then 2 doors open immediately. And so almost everywhere where there are doors that are located near each other open at the same time.
![Безымянный](https://user-images.githubusercontent.com/7480655/83014099-c6a31780-a026-11ea-9aff-471c3191ada4.png)

**Comment by TimGoll** [comment]
There is a convar in ulx under the tab "TTT2 Doors" where you can disable that behaviour. Doors are grouped by proximity. However only doors with the same rotation should be grouped. Was one of the doors opened by default? Which version are you using?

**Comment by TimGoll** [comment]
You could also give me the mapname so I can investigate this by myself. Maybe I can fix this.

**Comment by dok441** [comment]
ttt_67thway_v7_j_l

**Comment by TimGoll** [comment]
okay, IÄll take a look at it

**Comment by ThePlatinumGhost** [comment]
I can confirm this bug happen also "ttt_rooftops_2016_v1"
https://steamcommunity.com/sharedfiles/filedetails/?id=534491717
Near the elevator

**Comment by TimGoll** [comment]
I'm already at it and I think I have it. Give me half an hour.

**Comment by TimGoll** [comment]
Fixed it, PR is ready to be reviewed
