### ISSUE TITLE
The traitor's buttons are not working

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#545]
I personally and other users have noticed repeatedly that there are buttons of traitors are not activated, for what reason I do not know, but such a problem sometimes appears, I will try to record it myself on video, but wanted you to pay attention to this problem.

**Comment by saibotk** [comment]
There is not enough information, for us to reproduce or even get an idea on why it should not work. 
Also, your report does not comply with our bug report template (Issue template), which would also ask you for more information, and we explicitly stated, that we will close issues, that do not fill out the template. So I will close this for now, feel free to open up a new issue, with more information and that fills out the template.

Thanks
