### ISSUE TITLE
ERROR UPDATE DOOR

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#546]
[ERROR] addons/ttt2-tttv2/lua/ttt2/libraries/door.lua:57: attempt to get length of local 'data' (a userdata value)
  1. GetClosedAngle - addons/ttt2-tttv2/lua/ttt2/libraries/door.lua:57
   2. FindPair - addons/ttt2-tttv2/lua/ttt2/libraries/door.lua:72
    3. HandleDoorPairs - addons/ttt2-tttv2/lua/ttt2/libraries/door.lua:99
     4. SetUp - addons/ttt2-tttv2/lua/ttt2/libraries/door.lua:164
      5. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:764
       6. CleanUpMap - [C]:-1
        7. CleanUpMap - addons/tttdamagelogs-master/lua/damagelogs/shared/sync.lua:42
         8. CleanUp - gamemodes/terrortown/gamemode/server/sv_main.lua:786
          9. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:901

**Comment by TimGoll** [comment]
Already known. Thanks!

**Comment by dok441** [comment]
The error has not been fixed.

**Comment by TimGoll** [comment]
The same error can not happen anymore since the line is completely removed. Are you sure you've updated your version?

**Comment by TimGoll** [comment]
Additionally it works for me and I don't have an error anymore

**Comment by dok441** [comment]
I updated it, but you just fixed the value, not deleted the line.

-- the center pos is slightly shifted to the top to prevent ground
-- -- collisions in the wall trace
local pos Center = pos + Vector(0, 0, 0.525 * size Player.z)

Was
local pos Center = pos + Vector(0, 0, 0.5 * size Player.z)

**Comment by TimGoll** [comment]
this is a different fix for another error, this is a completely different file.

this one: https://github.com/TTT-2/TTT2/commit/042b4dbc59674e26046e8f3d4e29f8a4e6eef452

**Comment by dok441** [comment]
Missed apparently.
