### ISSUE TITLE
Double-click for buying item

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#553]
## Problem 
When you shop something in the shop you need to be quick and do one more less action can make you win 
at this moment for buy an item in the shop you need to

1. Press [key] for open the shop
2. Move mouse to the item
3. Click the item
4. Move mouse to Buy
5. Click buy

## Suggest
I suggest double click for buy item in the shop

1. Press [key] for open the shop
2. Move mouse to the item
3. Double-Click the item

Maybe a client side cvar to enable or disable this feature, it would be even better

**Comment by TimGoll** [comment]
This is already a todo for our shoprework: https://trello.com/c/S6nzwnZ0/77-shop-rework
