### ISSUE TITLE
Doors are brothers.

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#555]
https://steamcommunity.com/sharedfiles/filedetails/?id=246369972
![Безымянный](https://user-images.githubusercontent.com/7480655/83489184-b53e8d00-a4b6-11ea-9763-5abadcae8c86.png)
As you can see in the screenshot, both doors open when you click on one of them. Attached a map

**Comment by TimGoll** [comment]
Like I said, Doors in close proximity will be grouped. If you don't like this, you can disable it with a convar.

**Comment by dok441** [comment]
What parameter?! I don't see it in the door Department.

**Comment by TimGoll** [comment]
![image](https://user-images.githubusercontent.com/13639408/83539718-af1cd080-a4f7-11ea-8830-41a2ff000da7.png)

**Comment by dok441** [comment]
I turn it off, the doors still close at the same time, you need to change the card to confirm?

**Comment by TimGoll** [comment]
you need torestart the round. The grouping happens post map cleanup.

**Comment by dok441** [comment]
Understood
