### ISSUE TITLE
Server doesnt change to TTT2 anymore

### ISSUE THREAD

**Issue by Creyox** [TTT-2/TTT2#567]
My server doesnt change to the TTT2 gamemode anymore. I had this bug once already, when you pushed an update where this occured, that's why I just wanted to ask if you pushed out an update that may cause this?

I can't tell you my TTT2 version atm, but it's the workshop version. If you want to look up my log when the server boots up: https://pastebin.com/YSV0yCz5

Workshop Collection: https://steamcommunity.com/sharedfiles/filedetails/?id=849222406

I already tried deleting some addons and redownloading every addon to the server, but it seems as if an addon of TTT2 may have got an update, or Gmod got an update... 

Would be nice to know if its due to this addon or may be another ttt2 role addon. 

I hope I'm not bothering you, thanks <3

**Comment by TimGoll** [comment]
I'm guessing you still have it set to the terrortown gamemode?

**Comment by Creyox** [comment]
Yes, because I never had to change the starting gamemode in order to get TTT2 working. I just reread the FAQs and Setup-Guide and I didn't see any mention of another gamemode for TTT2. What is the name of the gamemode to write in the config?

**Comment by TimGoll** [comment]
`terrortown`
TTT2 is just a normal TTT addon.

**Comment by Creyox** [comment]
Yeah the server's starting with the terrortown gamemode

**Comment by TimGoll** [comment]
Looking at your log it seems like TTT2 is mounted but not loaded. Do you have some other TTT altering addons like "custom roles"?

**Comment by Creyox** [comment]
No, not that I'm aware of. And the server worked like 2 or 3 days ago perfectly fine I'd say. So it seems as if an update of an addon was downloaded when the server restarted which may have broken something. As I said: I've removed the latest addons I've addod to be sure I didn't broke it.

**Comment by Creyox** [comment]
Okay I just wiped the whole server and did a clean reinstallation. Seems as if it works now... Dont know what broke it, sorry for bothering you and keep up the good work ;P
