### ISSUE TITLE
No DNA

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#569]
As you can see in the screenshot, I took the DNA, but it shows that there is no DNA.
The latest version of updates is used.
![Безымянный](https://user-images.githubusercontent.com/7480655/83914048-24e39f00-a779-11ea-90e7-c23b20fb2058.png)

**Comment by TimGoll** [comment]
Are there any errors or steps to reproduce?

**Comment by TimGoll** [comment]
@lebroomer This is probably something for you.

**Comment by dok441** [comment]
There are no errors, this is the latest update of the DNA

**Comment by lebroomer** [comment]
I will take a look at it. Can you describe the situations, in which the problem occurs or are you able to reproduce the bug?

**Comment by dok441** [comment]
Perhaps I realized why it was, here the reason is that the person came out or died and because of it does not show that this person is dead.
