### ISSUE TITLE
When round starts dosent change roles or cant damage

### ISSUE THREAD

**Issue by Miki13201** [TTT-2/TTT2#574]
I used ULX++ To add bots when the round startered my role was "Preparing" It gives me the role weapon but i cant use the shop and damage heres the error i got `[ERROR] lua/autorun/lf_playermodel_selector.lua:290: bad argument #2 to 'SetMDL' (string expected, got nil)
  1. SetMDL - [C]:-1
   2. SetModel - lua/autorun/lf_playermodel_selector.lua:290
    3. SetRole - gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:135
     4. SelectRoles - gamemodes/terrortown/gamemode/server/sv_roleselection.lua:526
      5. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:1155

Timer Failed! [prep2begin][@gamemodes/terrortown/gamemode/server/sv_main.lua (line 941)`

**Comment by TimGoll** [comment]
This looks like an issue with the playermodel selector, not with TTT2

**Comment by Miki13201** [comment]
Oooh maybe enchaned player model selector breakes it let me check

**Comment by TimGoll** [comment]
I think you have to set `ttt_enforce_playermodel` to 0 when using the PMS

**Comment by Miki13201** [comment]
Nope working enchaned player model selector breakes it Thank you for the help

**Comment by TimGoll** [comment]
But EPMS works when setting the convar to 0, I'm pretty sure

**Comment by TimGoll** [comment]
With the drawback of not having rolespecific models (e.g. zombie models for the zombies etc)
