### ISSUE TITLE
Missing translation in Russian and German.

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#575]
I checked in Russian and German and both versions are 100% missing translation and because of this it looks like in the screenshot.
![Безымянный](https://user-images.githubusercontent.com/7480655/84025406-2c32c480-a994-11ea-9a9b-cabb005fcb94.png)

**Comment by dok441** [comment]
By the way, I want to supplement, add descriptions to the DNA scanner, because by pressing R, you can remove DNA, but there is no word about it anywhere.

**Comment by TimGoll** [comment]
@lebroomer Maybe you could add this information to the dna scanner. While doing this you could extend `AddHudHelp` by a third line
