### ISSUE TITLE
ttt_playercolor_mode doesnt work

### ISSUE THREAD

**Issue by TheSuspect2306** [TTT-2/TTT2#576]
the ttt playercolor mode doesnt work with ttt2
what does it do ? ... it colored all players in the same color every round random, thats just a fun command or feature thats not working anymore so i guess veryyyy loooow priority

command is "ttt_playercolor_mode" just set it to "1"

**Comment by Histalek** [comment]
Do you perhaps know if this was working at some point in TTT2?
I'm really not sure but i think i've seen it working on a ttt2 server some months ago

**Comment by TheSuspect2306** [comment]
ok its working but i remembered it was more colorful ^^

**Comment by ThePlatinumGhost** [comment]
![image](https://user-images.githubusercontent.com/36534723/84068977-13dd9c80-a9ca-11ea-8156-6610be5d59b5.png)
You need to set it to "3" or "2"

**Comment by TheSuspect2306** [comment]
is this a new ttt2 thing ? i never knew that was a thing ^^

**Comment by ThePlatinumGhost** [comment]
No no is from TTT base 
http://www.troubleinterroristtown.com/config-and-commands/convars
