### ISSUE TITLE
Error server Addonchecker

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#578]
After the server is started.

[ERROR] gamemodes/terrortown/gamemode/server/sv_main.lua:390: attempt to index global 'Addonchecker' (a nil value)
  1. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:390

Timer Failed! [Simple][@gamemodes/terrortown/gamemode/server/sv_main.lua (line 389)]

**Comment by TimGoll** [comment]
You have messed something up while updating:

![image](https://user-images.githubusercontent.com/13639408/84476129-00625800-ac8e-11ea-9a0e-49d04353f8e1.png)
