### ISSUE TITLE
Remove plymeta:Is[Role] except inno, traitor, detective

### ISSUE THREAD

**Issue by TheNickSkater** [TTT-2/TTT2#581]
I don't think TTT2 needs to register the Is[Role] function for every role that is on the Server.. For compatibility IsTraitor IsDetective and IsInnocent should stay of course.

But, just as example.. If a Role has the name of some function, it gets overwritten.. This happened for me in the SpecDM, the Ghost role creates the "IsGhost" function, tough SpecDM creates this function itself and needs it.

**Comment by Pustekuchen98** [comment]
I got a question about this. The Hitman is using the same function to exclude roles from being selected as a target. If this function would be removed wouldn't that break the hitman for example? And if I may ask, how would you go about fixing this issue then (hitman not able to exclude some roles after removing the is[Role] function)?

**Comment by TimGoll** [comment]
The Hitman code could be changed to the `ply:GetSubRole() == ROLE_NAME`

**Comment by Pustekuchen98** [comment]
ah okay ^^

**Comment by TheNickSkater** [comment]
> The Hitman code could be changed to the `ply:GetSubRole() == ROLE_NAME`

I would actually say it SHOULD be done like that tbh.

**Comment by TimGoll** [comment]
> > The Hitman code could be changed to the `ply:GetSubRole() == ROLE_NAME`
> 
> I would actually say it SHOULD be done like that tbh.

Yes, it is the style that we're using. I wasn't aware of the other functions at all. Probably something that was created in the early times of TTT2.

**Comment by TheNickSkater** [comment]
> > > The Hitman code could be changed to the `ply:GetSubRole() == ROLE_NAME`
> > 
> > 
> > I would actually say it SHOULD be done like that tbh.
> 
> Yes, it is the style that we're using. I wasn't aware of the other functions at all. Probably something that was created in the early times of TTT2.

Probably.. I dont even find the code where this is created xD

**Comment by TheNickSkater** [comment]
https://github.com/TTT-2/TTT2/blob/master/lua/includes/modules/roles.lua#L76 everything from this line just would need to be deleted.. The default functions are already hardcoded and will still work fine.. If everyone agrees at some point, I'd ofc make a PR.. or somebody else does it idk.

**Comment by saibotk** [comment]
Yes, in my opinion this is also not as explicit as needed, for example `IsTraitor` will check if the base role is a traitor (eg. to make traitor doors etc compatible), but other `Is"ROLE"` functions check for the subrole, which does seem to be inconsistent and unintuitive to me. Removing them would force more precise and explicit code / checks :+1: 

Also we already annotated the `IsTraitor` function as deprecated here: https://github.com/TTT-2/TTT2/blob/231c9e48ec7ac1dcfc85b8257a49c9cbf636a637/gamemodes/terrortown/gamemode/shared/sh_player_ext.lua#L375
