### ISSUE TITLE
MinPlayers for item purchases

### ISSUE THREAD

**Issue by NickCloudAT** [TTT-2/TTT2#592]
Just like the limited or globalLimited things for shop items, a minPlayers thing.
This can be discuessed, do only alive players count or all players except forceSpec players etc..

**Comment by TimGoll** [comment]
This should be based on the anount of players at the start of a round, shouldn't it?

**Comment by TheNickSkater** [comment]
> This should be based on the anount of players at the start of a round, shouldn't it?

Yes, forgot to add that xD

**Comment by EntranceJew** [comment]
This appears to be already implemented? 

https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/gamemode/shared/sh_init.lua#L695-L711

Unless I don't understand the scope of the issue.

**Comment by Histalek** [comment]
This was implemented a while ago.
