### ISSUE TITLE
Calling kill on a dead player causes another corpse to spawn

### ISSUE THREAD

**Issue by Zaratusa** [TTT-2/TTT2#611]
## Your version of TTT2 (mandatory)

- Workshop version from Steam (v0.7.2b)

## Describe the bug (mandatory)

Calling [kill](https://wiki.facepunch.com/gmod/Player:Kill) on a dead player causes another corpse to spawn.

## To reproduce

Steps to reproduce the behaviour:

1. Kill a player with an explosion for example
2. Right after it, kill the player with the [kill](https://wiki.facepunch.com/gmod/Player:Kill) function

## Expected behaviour

Only one corpse spawns with explosion as the kill reason.

## Additional context

It was working correctly in TTT. It may be caused by a different implementation of [GM:PlayerDeath](https://wiki.facepunch.com/gmod/GM:PlayerDeath).

**Comment by saibotk** [comment]
I cannot reproduce this, I killed a bot, and called Kill() server side on the respective player entity using lua_run and as expected it does nothing.

**Comment by Zaratusa** [comment]
I had a script which kill a player from an explosion and then kills the player via [kill](https://wiki.facepunch.com/gmod/Player:Kill). It may only happen, when it called in the same frame and thus may only be relevant for modders.

**Comment by TimGoll** [comment]
Ahh if this is the case we could prevent this in TTT2

**Comment by saibotk** [comment]
> I had a script which kill a player from an explosion and then kills the player via [kill](https://wiki.facepunch.com/gmod/Player:Kill). It may only happen, when it called in the same frame and thus may only be relevant for modders.

@Zaratusa would you mind sharing that somehow or maybe also add a detailed setup, to reproduce this?

**Comment by Zaratusa** [comment]
Here in line 204 is the explosion damage and in line 216 is the kill: https://github.com/Zaratusa/ttt-jihad-bomb/blob/6dd294cf1c5671c2cb48ed7ce2763236c6464599/gamemodes/terrortown/entities/weapons/weapon_ttt_jihad_bomb/shared.lua#L216
