### ISSUE TITLE
Buyable items slots are broken

### ISSUE THREAD

**Issue by charrllie** [TTT-2/TTT2#644]
## Your version of TTT2 (mandatory)
0.7.2 (github/workshop) / 0.7.3 (workshop)

## Describe the bug (mandatory)
Hey there!
During a test of my TTT2 server one of my admins has noticed a very strange and easy to overlook bug.
Almost all buyable items slots are fixed to "slot 7".
You can buy multiple items without the slot limit.

First I thought that it is a bug related to my personal changes in a code, but it seems to be a bug in gamemode itself.

I've:
- disabled all of my addons (on my server) - didn't help
- roled back to 0.7.2 (on my server)  - didn't help, I even checked screenshot that I've made at August 4th and bug is visible there clear as day.
- cleared all the cache and database files (local computer), used workshop version (0.7.3)
- restarted game multiple times in different configurations

Pics:
https://imgur.com/a/LFjMv45

Video from other server (play at timestamp):
https://youtu.be/uYtjjegDavk?t=1237

## Steps to reproduce the behaviour:
- Open the item shop
- Look at the assigned item slot number

**Comment by TimGoll** [comment]
I think slot 7 has by default an infinite amount of slots for weapons. Or was it slot 8?
Since this is something UI related, it is something that should be adressed in our upcoming UI rework!

Thanks for the detailed bugreport btw.

**Comment by charrllie** [comment]
Thanks for the quick response!
I've just double checked, indeed a lot of items are assigned to the "slot 7" by default, so I explicitly tested items assigned to some other slot.
Both C4 and silenced pistol are assigned to slot 6, I am able to buy them both at once.
I moved them to slot 1 - same.

It looks like slot is forced to 7 no matter what I set in a lua file.
I also checked to be sure - they are not overwritten by TTT2 gamemode.

I've checked default TTT (disabled TTT2) - slots are working correctly, I am not able to carry both weapons at once.
Considering the fact that slots are assigned in client-side code it might be UI related bug but it breaks the game a bit.
![bug_v2](https://user-images.githubusercontent.com/884926/91721194-a9876300-eb98-11ea-8ae2-b91b1ab833ce.png)

**Comment by TimGoll** [comment]
The slot is irrelevant in TTT2, the wapon type defines the slot

**Comment by charrllie** [comment]
Ohhhh that explains why grenades worked fine.
Big thanks!

**Comment by TimGoll** [comment]
So, I'm not 100% sure if your report is still a bug. Is there something that doesn't work?

**Comment by charrllie** [comment]
I've checked, I am unable to buy/carry more than 1 buyable grenade, so yes report is not a bug after all.
I guess I'll just have to change SWEP.KIND for some of buyable items.
Thank You once again for Your time, sorry for false alarm.

**Comment by TimGoll** [comment]
Sounds great, so no bug after all! :D 

A small tip for you: Check out the "TTT2 Inventory" tab in ulx to change the amount of carried weapons per slot
