### ISSUE TITLE
[Feature Request] Additional Hook called after PlayerTakeDamage should output real damage

### ISSUE THREAD

**Issue by ZenBre4ker** [TTT-2/TTT2#657]
**Is your feature request related to a problem? Please describe.**
The hitdamage numbers addon only shows the raw damage before karma and other effects get considered, as it only hooks to the GM:EntityTakeDamage. 
Even trying to mod it in by using the net.receive("ttt2_damage_received")-function, wouldn't work as the GM:PlayerTakeDamage only sends the "amount" instead of dmginfo:GetDamage() to the cl_damage_indicator.

**Describe the solution you'd like**
My solution would be to create a new function like GM:EntityTookScaledDamage to hook to, which just contains all the processed information after GM:EntityTakeDamage and GM:PlayerTakeDamage got called.

**Describe alternatives you've considered**
Alternatively you could send the information like this:
net.Start("ttt2_damage_received")
net.WriteFloat(dmginfo:GetDamage())
net.Send(ent)
but I'm unsure if it would be possible to have more than one receive function. Normally a packet can be only sent once and would need to be resend with the same information, which sound unnecessary.

**Important Files**
TTT2\gamemodes\terrortown\gamemode
..\server\sv_player.lua
..\client\cl_damage_indicator

**Comment by TimGoll** [comment]
I actually like your proposal of an additional hook as I've seen the same problem as well. This hook could be used in our addons as well.

**Comment by ZenBre4ker** [comment]
Feature bereits in Garrys Mod:
https://wiki.facepunch.com/gmod/GM:PostEntityTakeDamage
