### ISSUE TITLE
Voice Chat funktioniert nur als Traitor

### ISSUE THREAD

**Issue by bammertine** [TTT-2/TTT2#660]
Version: v0.7.4b

Auf der neuesten Version vom Workshop, funktioniert der Voicechat nur, wenn man Traitor ist.

Reproduce:
"X" drücken.

**Comment by Histalek** [comment]
----> English version below <----
Wir können mit deinem Bugreport so leider nichts anfangen, bitte halte dich an unser Bug-Template und öffne das Issue dann wieder :)

-----------------------------------------------------
This bugreport is sadly unusable for us, please use our bugreport template and re-open the issue :)
