### ISSUE TITLE
Voice Chat nur als Traitor möglich

### ISSUE THREAD

**Issue by bammertine** [TTT-2/TTT2#661]
## Disclaimer

- "0.7.4b"
- "Man kann nur, wenn man Traitor ist, sprechen. Keine weiteren Rollen sind installiert."

## Your version of TTT2 (mandatory)

- Workshop version from Steam

## Describe the bug (mandatory)
Man kann nur, wenn man Traitor ist, sprechen. Keine weiteren Rollen sind installiert.

## To reproduce

Steps to reproduce the behaviour:

Drücke Ingame die "Sprech" Taste. "X" ist dafür Standard. Man kann von anderen nur verstanden werden, wenn man Traitor ist.
Die Clientseitige Anzeige, das gesprochen wird, erscheint aber.

## Context (please provide as much as you can)

https://www.gmodstore.com/market/view/voicechat-wavemeter
ist installiert. Das Entfernen davon ändert allerdings nichts.

Es sind ausschließlich Addons von hier installiert:
https://steamcommunity.com/workshop/filedetails/?id=1357745995

Wenn ich allerdings die sv_voice der Version 0.6. irgendwas verwende, funktioniert der Voicechat einwandfrei.

**Comment by Histalek** [comment]
Nach meinen Tests mit der verlinkten Kollektion funktioniert der Globale VoiceChat einwandfrei. 

Ich möchte hier aber nochmal darauf hinweise, dass der TeamVoiceChat und der GlobalVoiceChat getrennte hotkeys haben. Falls du nur mit Traitor, Innocent und Detective spielst hat nur der Traitor einen TeamVoiceChat. Innos/Dete haben nur den GlobalVoiceChat den alle benutzen können. Ist "X" evtl dein Hotkey für den TeamVoiceChat? 

F1 -> Key Bindings (oder im Deutschen `Tastenbelegungen`

**Comment by bammertine** [comment]
Also bei mir klappt es - out of the box- nicht, keine Ahnung. Wird wohl irgendwas stören.

**Comment by bammertine** [comment]
Komplett alles neu abonniert etc. Gleicher Fehler. Global Chat funktioniert nicht, nur Traitor können im global Chat sprechen und verstanden werden.

**Comment by saibotk** [comment]
Wir haben das jetzt nochmal ausprobiert, auch auf unserem Testserver mit allen unseren Addons und können keinen Fehler finden, deswegen schließe ich das Issue mal.
