### ISSUE TITLE
Weapon Pickup: Only works for groundlevel weapons

### ISSUE THREAD

**Issue by bammertine** [TTT-2/TTT2#662]
## Disclaimer

If you are missing the following information your issue will be closed!

- 0.7.4b
- Das Aufheben von Waffen ist nur möglich, wenn diese gerade auf dem Boden liegen.

Also please make sure to read the [FAQ](https://docs.ttt2.neoxult.de/troubleshooting) and [existing issues](https://github.com/TTT-2/TTT2/issues?q=is%3Aissue) first!

## Your version of TTT2 (mandatory)

- Workshop version from Steam
- Latest GitHub version

## Describe the bug (mandatory)

Waffen können nicht aufgehoben werden, wenn diese zum Beispiel auf gleicher höhe liegen (mit "E"), also dieser Hervorhebung. Das klappt nur, wenn die Waffe direkt unter einem, bzw. gerade auf dem Boden liegt. Wenn die Waffe aber auf einer Kiste liegt, man dann auf die Kiste springt (und die Waffe wieder unter einem liegt), kann man sie aufheben. Von unten aber nicht.

Ich nutze TFA Waffen

## To reproduce

Steps to reproduce the behaviour:

1. Suche eine Waffen
2. Waffe darf nicht direkt auf dem Boden liegen
3. Aufheben mit "E" klappt nun nicht, obwohl das Overlay kommt.

## Expected behaviour

Eigentlich sollte man die Waffen aufheben können, bzw mit "E" aufnehmen.

## Context (please provide as much as you can)

TFA Weapons mit TTT2. Sonst clean.
https://steamcommunity.com/sharedfiles/filedetails/?l=german&id=415143062

**Comment by TimGoll** [comment]
Hast du mal getestet, ob das auch passiert, wenn du normale GarrysMod Waffen nutzt?

**Comment by bammertine** [comment]
Ja, genau dasselbe Problem mit Standard TTT Waffen.

**Comment by TimGoll** [comment]
Ist das Problem erst mit dem letzten Update aufgetreten?

**Comment by bammertine** [comment]
Nutze erst seit 0.7.4b das TTT2. Bzw. habe von einer Uralt-Version darauf geupdated. Das gab es damals noch nicht.

**Comment by TimGoll** [comment]
Ahh, ich teste es mal gerade ob ich das Problem auch habe

**Comment by TimGoll** [comment]
![image](https://user-images.githubusercontent.com/13639408/95017326-02935c80-0659-11eb-8ba1-8cdebb4e7ae2.png)
![image](https://user-images.githubusercontent.com/13639408/95017332-0626e380-0659-11eb-9488-1b2dc792f9b0.png)

Habe ich das richtig reproduziert? Das geht bei mir

**Comment by TimGoll** [comment]
Mehr Tests:
![image](https://user-images.githubusercontent.com/13639408/95017436-9fee9080-0659-11eb-99d7-de9c9bad14a8.png)
![image](https://user-images.githubusercontent.com/13639408/95017439-a1b85400-0659-11eb-9df1-a6e4fef89e28.png)

![image](https://user-images.githubusercontent.com/13639408/95017448-aa108f00-0659-11eb-8c2f-4b09f022084f.png)
![image](https://user-images.githubusercontent.com/13639408/95017452-abda5280-0659-11eb-99cf-f6b280535e69.png)

**Comment by bammertine** [comment]
Auf einer anderen Map habe ich das Problem nicht.
Ich schaue mal, ob es evtl an der Map liegt.

**Comment by TimGoll** [comment]
vielleicht CS:S auf dem Server nicht gemounted und daher sind die Hitboxen falsch?

**Comment by saibotk** [comment]
Da wir den Fehler nicht reproduzieren können, schließe ich das Issue erstmal, wenn es noch etwas Konkretes gibt, gerne nochmal melden.

**Comment by nrauschcom** [comment]
Habe das selbe Problem seit 0.7.4b, vorher hat das tadellos funktioniert.

**Comment by TimGoll** [comment]
Kannst du mehr Informationen zum Reproduzieren geben? Bei uns geht alles einwandfrei, auch mit sehr vielen Addons

**Comment by nrauschcom** [comment]
Leider nein, keine Ahnung. Wir haben keine Addons hinzugefügt, lediglich ein paar entfernt.

Teilweise kann ich die Waffe über "E" gar nicht aufnehmen, teilweise droppe ich meine aktuelle und bekomme die aufgenommene in einen nicht-aktiven Slot.

Wenn du kurz Zeit hast (und die Downloadzeit nicht scheust), kannst du auch auf meinem Server vorbeischauen unter "nrausch.com", Passwort "pufo". Dann könnten wir zumindest mal eingrenzen, dass es an anderen Addons als der TTT2 Base liegt.

Ansonsten gibt es die Plugin-Liste (Achtung, lang!) auch hier: https://steamcommunity.com/sharedfiles/filedetails/?id=365261951

Ich werde schauen, ob ich in Konsole oder sonstwo Auffälligkeiten finde.

**Comment by TimGoll** [comment]
just FYI, das hier ist public. Vllt willst du das Passwort jetzt ändern, da es jeder im Discord gesehen hat :D 

Aber generell heute sehr schlecht. Ab morgen habe ich jedoch Zeit! :)

**Comment by nrauschcom** [comment]
Passwort ist egal, ist nur damit man nicht über die öffentliche Liste drauf kommt :D 

Morgen ist wahrscheinlich niemand auf dem Server, aber vielleicht kannst du das Problem ja auch alleine finden. Ansonsten erreichst du mich über rausch.nico@gmail.com, dann kann ich sicher schnell vorbeikommen.

**Comment by nrauschcom** [comment]
Sieht aus als könnte dieser Commit etwas damit zu tun haben: https://github.com/TTT-2/TTT2/commit/37541be47ac40c8828b78be95906f35d140b364a

Da ich mich in eurem Source aber nicht wirklich auskenne, stelle ich da nur eine wilde Vermutung an ^^

**Comment by TimGoll** [comment]
vorrausgesetzt du hältst dein gmod up to date: nein, denke nicht. Wir haben nun einfach von dem Teleportieren der Waffen zur Nutzung der korrekten Funktion gewechselt

**Comment by nrauschcom** [comment]
![image](https://user-images.githubusercontent.com/1051009/95909742-4b58bd00-0d9f-11eb-9a52-d9305e3a34a2.png)
Hier noch ein Screenshot, nachdem ich versucht habe, eine Waffe aufzunehmen. Sie scheint also doch einfach hochteleportiert geworden zu sein, hm.
Passiert auch mit den Originalwaffen.

**Comment by TimGoll** [comment]
sicher, dass du die aktuelle TTT2 Version hast? Auf diese Höhe haben wir die Waffen in <0.7.3b teleportiert. Das wird seit der neuen Version gar nicht mehr gemacht. Vielleicht ein GMod Cache Problem?

**Comment by nrauschcom** [comment]
Der Changelog im Game ist aktuell, und der Server wurde schon mehrfach neu gestartet. Ich schaue morgen nochmal nach.

**Comment by TimGoll** [comment]
Ich weiß auch nicht .. vielleicht den gamemode neu installieren?

**Comment by Alf21** [comment]
Ich empfehle dir mal, einen Server beizutreten, wo es geht. Z.B. unseren Official Server. Wenn es dann geht dennoch nicht geht, wissen wir, dass es an deinem Client liegt. Geht es, hast du ne Fehlkonfiguration an deinem Server

**Comment by TimGoll** [comment]
gute Idee. Aber ich habs auf unserem Server noch nicht getestet.
@nrauschcom können wir gerne morgen machen. Die IP ist `ttt.neoxult.de`

**Comment by nrauschcom** [comment]
Tatsächlich ist der Grund eigentlich offensichtlich.. Da ihr auf die neue Pickup-Methode gewechselt habt, hat ein Garrys Mod Update im Server gefehlt, das trotz mehrmaligem Restart und Update-Script im systemd nicht geladen wurde..

Nach manuellem Update über die SteamCMD funktioniert jetzt alles wieder. Danke für eure schnelle Hilfe anyway :)

@bammertine Vielleicht willst du das auch mal testen?

**Comment by TimGoll** [comment]
aha, da gab es schon mehrere Leute hier auf Discord, die das Problem hatten! Gut, dass das jetzt geklärt ist. Hätte dann aber Error in der Konsole geben sollen. Mit denen hätte ich euch sofort sagen können, was der Grund ist.

Hinweis: Server aktualisiert sich nie automatisch, musst du mit SteamCMD updaten

**Comment by nrauschcom** [comment]
Joa, ich habe eine update.sh, die den SteamCMD Prozess durchführt, in der before_start Routine im systemd des Servers. Eigentlich sollte das immer ausgeführt werden. Weird! Aber Fehler lag dann auf jeden Fall auf meiner Seite, das Issue hier kann also im Aktenschrank bleiben ;)
