### ISSUE TITLE
Innocents can't defuse other innocents C4

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#679]
## Your version of TTT2 (mandatory)

Leave one of the following:
- Latest GitHub version

## Video
https://youtu.be/fCwWP37c8OI

## Describe the bug (mandatory)
When an innocent places a c4 other innocents can't defuse them
and the message that appears is wrong

## Expected behaviour

This should be intended only for Team Traitor(?)

**Comment by Histalek** [comment]
The message is  most definitely wrong. But other than that i'm not sure if we should make an exception for innocents.

I think in general the rule regarding defusing the c4 should be either that you can't defuse it if the owner/placer of the c4 is in your team and still alive or just everybody can defuse the bomb.

i don't even know why another traitor should not be allowed to defuse the bomb of his teammate

**Comment by ThePlatinumGhost** [comment]
> i don't even know why another traitor should not be allowed to defuse the bomb of his teammate

yeah I agree with you, I was thinking  that this would be intended, but the fact that innocent can't defuse other innocent c4 is wrong and also the message is wrong
