### ISSUE TITLE
Remove Addons from Checker

### ISSUE THREAD

**Issue by dhkatz** [TTT-2/TTT2#696]
## Your version of TTT2 (mandatory)

v0.7.4b (Workshop)

## Describe the bug (mandatory)

Currently some of my addons are listed inside [sv_addonchecker.lua](https://github.com/TTT-2/TTT2/blob/a1fb79d16f253208d4c91205e3746a4e0cd0b9b8/gamemodes/terrortown/gamemode/server/sv_addonchecker.lua)

https://github.com/TTT-2/TTT2/blob/a1fb79d16f253208d4c91205e3746a4e0cd0b9b8/gamemodes/terrortown/gamemode/server/sv_addonchecker.lua#L180

https://github.com/TTT-2/TTT2/blob/a1fb79d16f253208d4c91205e3746a4e0cd0b9b8/gamemodes/terrortown/gamemode/server/sv_addonchecker.lua#L260

I have updated these addons to fully support TTT2 (as well as my other TTT addons), including ULX menu support where applicable. Therefore I believe they should be removed from the addon checker now.

The source repositories for the addons in question are here:

https://github.com/gmod-workshop/ttt-clairvoyancy

https://github.com/gmod-workshop/ttt-martyrdom

I've also added TTT2 support for these addons:

https://github.com/gmod-workshop/ttt-timestop

https://github.com/gmod-workshop/ttt-laststand

**Comment by TimGoll** [comment]
Great! For the martyrdom: Please use my icon since we use a simple black/white icon: https://github.com/TTT-2/ttt_addon_graphics/blob/master/ICONS/icons_sidebar_64/item_hud_effect_martyrdom.png

and your laststanding has two colors whiich will look strange for bright hud colors because the color of the icon will be black

**Comment by dhkatz** [comment]
You want me to change the icon to be pure white for last stand?

**Comment by TimGoll** [comment]
It's your addon, do whatever you like :D It's just a recommendation from my side. I guess you have TTT2 installed? Go to the HUD Editor and set the HUD color to white, you'll see the "problem"

**Comment by dhkatz** [comment]
Yeah you were right. I took your advice and updated the icon for the ttt-martyrdom and ttt-laststand addons, already pushed to workshop

**Comment by TimGoll** [comment]
great, I'll take a look at them and then update the addonchecker

**Comment by dhkatz** [comment]
Thanks. Let me know if there's anything you think I should update

**Comment by JoKrus** [comment]
I can confirm for Clairvoyancy that it is functioning very well in TTT2, ConVar settings plus the addon itself

**Comment by TimGoll** [comment]
@JoKrus Thanks! As soon as I start working on TTT2 again, I'll update the addonchecker.

**Comment by dhkatz** [comment]
Thank you everybody 😀
