### ISSUE TITLE
[Feature Request] Configurable Knife Damage

### ISSUE THREAD

**Issue by RossGosling-Github** [TTT-2/TTT2#698]
**Is your feature request related to a problem?**

Before the use of TTT2 we were able to modify the file, `C:/~/gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua`, and that would allow us to increase the knife damage so that it would one-hit kill.

TTT2 doesn't use this lua, but `TTT2/gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua` instead, so we can't change how much damage is dealt unfortunately.

**Describe the solution you'd like**

A console command or interface that allows the option to change knife damage.

Probably an overkill implementation but, an interface that would allow you to modify the damage, accuracy, rate of fire, etc of every weapon would be great, giving you full control over weapons bought in by other addons etc, but I'm unsure of the feasibility there.

**Describe alternatives you've considered**

I have not been able to find anything on the workshop or within the install directory that can get  around this.

**Comment by TheNickSkater** [comment]
You can actually still overwrite the knife. You will just have to create the knife file in the same directory as ttt2 has it in (in your addons folder though).

Example create "weapon_ttt_knife.lua" in addons/ttt2/gamemodes/terrortown/entities/weapons and paste the knife code from ttt2 in there and you will be able to edit it.
This is just a more "hacky" solution.

**Comment by RossGosling-Github** [comment]
That workaround is great, thank you

**Comment by TimGoll** [comment]
Also addon like this may work here: https://steamcommunity.com/sharedfiles/filedetails/?id=933160196

**Comment by TimGoll** [comment]
Since you found a solution I will close this
