### ISSUE TITLE
Role Selection at 5 Players

### ISSUE THREAD

**Issue by TheNickSkater** [TTT-2/TTT2#700]
## Your version of TTT2 (mandatory)

Leave one of the following:

- Latest GitHub version

## Describe the bug (mandatory)

It seems like since alf made the Role Layering update, special roles can no longer be selected at 5 players.
I noticed this because I always had my Jackal to spawn at min. 5 players, but after the update we never ever had a Jackal at 5 players again.

What I did to be sure:
Created a 100% new Server with ONLY TTT2, ULX/ULIB/TTT2-ULX and the Jackal Role > Set the Jackal to 100% random and even 1 player minimum. Also tried to change the min inno pct to the very lowest.. But no Jackal spawned. Only at 6 players he began to spawn again.

What I also did: I went through ALL commits after the role layering update to be sure it defintiley was alfs update. Once I used the commit before the role layering update, everything works nicely again.

## To reproduce

Steps to reproduce the behaviour:

Let a Round start with 5 players and a role (like Jackal) set to min players 5 and 100% random.

## Expected behaviour

A special role should get selected but it's not.

I would love to see somebody else test this too.

**Comment by ZenBre4ker** [comment]
I will look into it, but did you check the number of allowed base and subroles?

**Comment by TheNickSkater** [comment]
> I will look into it, but did you check the number of allowed base and subroles?

I sure did. They are set to infinite (0) but also tested it with just a very high number.

**Comment by ZenBre4ker** [comment]
Okay tested this too. It's really a bug with the current rolelayering-system. But I guess it's player number independent as you can get the jackal role if you also enable a second baserole. But you always only get one of those roles even with random set to 100 and the pct changed accordingly as well as min_inno_pct set to 0.

**Comment by ZenBre4ker** [comment]
To really reproduce this issue:
1) Edit rolelayering to be layer1: detective, layer2: other role (jackal)
2) Make Detective min players to a higher number than you want to test (in this case minimum of 6)
3) Make Jackal min players to a lower number than detective (in this case maximum of 5)
4) Now play a game with more or equal than min players of jackal and less than min players of detective (in this case 5)

=> As a result you will never get the jackal

Problem seems to be, that one layer after an invalid/empty layer gets skipped. Therefore anything in layer 3 or above should still work.
