### ISSUE TITLE
Game crash on language settings

### ISSUE THREAD

**Issue by MisterClems** [TTT-2/TTT2#705]
## Disclaimer

If you are missing the following information your issue will be closed!

- "Your version of TTT2" : Lastest version
- "Describe the bug"

Also please make sure to read the [FAQ](https://docs.ttt2.neoxult.de/troubleshooting) and [existing issues](https://github.com/TTT-2/TTT2/issues?q=is%3Aissue) first!

## Your version of TTT2 (mandatory)

(v0.7.4b) lastest version

## Video

https://streamable.com/6w9cni

## Describe the bug (mandatory)

When i go to the language settings  i got an error and my game crash, sometimes he didnt crash and the HUD refresh and i got : This translation is {coverage}% complete with the english language taken as a default reference. and after that he instantly crash

## Context (please provide as much as you can)

I only have TTT2 installed on a local server

## Additional context

Screen with the lua error 
![Capture](https://user-images.githubusercontent.com/73431903/103444445-8b299500-4c68-11eb-95ad-cf3b1b7fd78b.PNG)

**Comment by TimGoll** [comment]
latest workshop or steam version?

**Comment by MisterClems** [comment]
latest github version

**Comment by TimGoll** [comment]
alright, give me a minute. I'll test it right now

**Comment by TimGoll** [comment]
Okay, I can confirm this error. I'll look into it. No idea how I missed this. Probably a merging error that happened in a late stage.
