### ISSUE TITLE
TTT2 Guide empty.

### ISSUE THREAD

**Issue by Bakurama** [TTT-2/TTT2#723]
Hey, Im not the Server owner or anything, but he doesnt know if he can change it, so im asking here directly. 

First of all the new UI is pretty nice and overall really clear to understand, but we dont get roll informations or anything really in the TTT2 Guide menu.  
![20210213183605_1](https://user-images.githubusercontent.com/79018537/107856720-63624b00-6e2a-11eb-84cd-befa4ee5523a.jpg) Is this a Bug or does the Admin have to import the information into the screen? 

TTT2 Base 0.8.0b
https://steamcommunity.com/sharedfiles/filedetails/?id=849222406 (the Workshop collection if it helps.)

Thank you for your work.

**Comment by TimGoll** [comment]
Yes, this is work in progress currently

**Comment by ROODAY** [comment]
@TimGoll is there a guide on how to help contribute on the guides? I'd love to help get it done as I just started using TTT2 on my server and my friends and I are still confused a lot on what our roles and classes do

**Comment by TimGoll** [comment]
If you contact me on discord, we can talk about it. I'd really appreciate your contribution
