### ISSUE TITLE
ON or OFF button/CVAR for the 'send a credit to anyone, even those players who aren't not on your team' feature

### ISSUE THREAD

**Issue by DevilYami** [TTT-2/TTT2#734]
**Is your feature request related to a problem? Please describe.**
Although for the many extra roles it's great letting Detectives & Traitors and other roles give creds to about any player, for those servers who don't use those roles and want to only be able to give points to their teammates in a quick set of clicks, having the entire player list screws up their speed and maybe even the round if they are too hasty and forget how it's no longer only their teammates in the **transfer credit list**.
On some of the session of my server we had some situations where one T would give a credit to the detective by mistake then got called KOS and their entire round was ruined.

**Describe the solution you'd like**
Adding a simple button or a console command(cvar) to turn ON or OFF the ability to send credits to everyone or only to your team would suffice.

**Describe alternatives you've considered**
Letting people know where to change it/remove it on the code/config files would be the other way of letting them opt out of this new feature, if they would want to change it according to their needs.

**Additional context**
![ttt_credit_transfer](https://user-images.githubusercontent.com/66830868/109438172-a58dae00-7a20-11eb-9f79-c4f03d322fa3.png)

**Comment by saibotk** [comment]
Thank you for your report!

We will consider changing that, and I get your point of losing too much time searching for the right person.

Thanks!

**Comment by saibotk** [comment]
What do you think about sorting this list with team members first and an additional indicator like "NAME (teammate)" ?

Would that solve your problem sufficiently?

**Comment by TimGoll** [comment]
> What do you think about sorting this list with team members first and an additional indicator like "NAME (teammate)" ?
> 
> Would that solve your problem sufficiently?

Wouldn't this create the issue again that the current list tried to solve?

**Comment by saibotk** [comment]
> > What do you think about sorting this list with team members first and an additional indicator like "NAME (teammate)" ?
> > Would that solve your problem sufficiently?
> 
> Wouldn't this create the issue again that the current list tried to solve?

What issue? This would solve the need to scroll down the list and also the issue that you need to be familiar with the names of your teammates

**Comment by TimGoll** [comment]
> > > What do you think about sorting this list with team members first and an additional indicator like "NAME (teammate)" ?
> > > Would that solve your problem sufficiently?
> > 
> > 
> > Wouldn't this create the issue again that the current list tried to solve?
> 
> What issue? This would solve the need to scroll down the list and also the issue that you need to be familiar with the names of your teammates

The issue that you can see who is a spy for example

**Comment by saibotk** [comment]
The only thing i want to change is the order of the entries and an additional marker, you can still send credits to others.

**Comment by TimGoll** [comment]
> The only thing i want to change is the order of the entries and an additional marker, you can still send credits to others.

Yes. But if there is no "teammate" next to the spy, you know that he is the spy and not another T

**Comment by saibotk** [comment]
That would never be the case, since others see the spy as an actual teammate because of the role syncing and in general such cases should not affect the design of such a feature. A role like the spy should work with this as he does with other checks for the same team etc

**Comment by TimGoll** [comment]
ah, that's a valid point
