### ISSUE TITLE
TTT2 causing many errors on the server

### ISSUE THREAD

**Issue by MrLuxALot** [TTT-2/TTT2#805]
My Server Collection 
https://steamcommunity.com/sharedfiles/filedetails/?id=2480247774

When I add the TTT2 addons my Server gets 50 errors, some of them looping into big numbers.
Need help.
![Screenshot_198](https://user-images.githubusercontent.com/52431814/117636007-abbaac00-b180-11eb-812e-3d2354ae0043.png)

**Comment by TimGoll** [comment]
this is probably not caused by TTT2, but by a different addon. Try using the `addonchecker` command in the server console

**Comment by MrLuxALot** [comment]
How do I use this addonchecker?

**Comment by TimGoll** [comment]
Literally what I just said. Type `addonchecker` in the serverconsole.

See our FAQ: https://docs.ttt2.neoxult.de/troubleshooting/
