### ISSUE TITLE
Nerf not making sound when crouch bhoping 

### ISSUE THREAD

**Issue by broiiler** [TTT-2/TTT2#810]
title is pretty self explanatory make it so when you crouch bhop on the ground it makes sound for accelerating at certaint amount of speed

**Comment by broiiler** [comment]
https://github.com/Facepunch/garrysmod/blob/be251723824643351cb88a969818425d1ddf42b3/garrysmod/gamemodes/terrortown/gamemode/shared.lua#L158

**Comment by ZenBre4ker** [comment]
As crouching is limited to something under 150 speed. I will test if it actually works or it had a reason why they put the crouch statement in there. Usually it should be fine if we just check for the speed.

**Comment by ZenBre4ker** [comment]
Can be closed I guess.

**Comment by TimGoll** [comment]
thanks, yes
