### ISSUE TITLE
Turn off voice chat.

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#843]
I noticed a mistake with voice chat. People stop working voice chat, bug there are 2 types. In one case, it always shows you what you say (although others do not hear you and do not see your chat badge), although you did not speak and could even be in observers for a long time. In case 2, you just lose the opportunity to talk, when you press the button, nothing happens.

## Your version of TTT2 (- "v0.9.2b")
- Latest GitHub version.

- Collection link of your Server https://steamcommunity.com/sharedfiles/filedetails/?id=1975562240

**Comment by ZenBre4ker** [comment]
I don't really understand your problem. Heres my summary:
1. You see the voice chat icon even if you dont talk and that also happens as observer and nobody can hear you. Might your voice chat key be broken or you have it always on and your mic is not registered in gmod?
2. Sometimes you want to talk, but when you press the voice chat key, you can't see the icon? Same as above. Seems like there might be another issue of you handling voice chat.

You should definitely check your collection. Maybe try it without all those stuff and only TTT2, does it still happen?
