### ISSUE TITLE
Show Roles

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#844]
- "There is a bug for a long time, when a person enters at the time of the start of the round, for an unknown reason, people in a taboo with their roles can be shown, as a traitor is permissible. I don't know how to repeat it, but to this day it is."
## Your version of TTT2 (- "v0.9.2b")
- Latest GitHub version.
- Collection link of your Server https://steamcommunity.com/sharedfiles/filedetails/?id=1975562240

**Comment by ZenBre4ker** [comment]
Your workshop collection is of no help, as you seemingly repackaged all content yourself @dok441. I also dont really understand your problem. What do you mean with "people in a taboo"? So can some traitor see roles they shouldnt be able to see?
Could be just an issue with your collection. How do you use TTT2? Is it in one of those packages or do you use the github-version?

**Comment by TimGoll** [comment]
I don't understand the issue exactly, but it could be the spy bug that got recently fixed. Because the spy caused all roles to be shown. I will therefore close this issue.

Related issue: https://github.com/TTT-2/ttt2-role_spy/issues/29
