### ISSUE TITLE
dead body ragdoll cause too much network traffic

### ISSUE THREAD

**Issue by swordjjjkkk** [TTT-2/TTT2#848]
**Is your feature request related to a problem? Please describe.**
dead body use ragdoll system cause too much network traffic that not necessary. 
i found that if body pull into water , it will spend a long time sync ragdoll traffic which make server under presure.

**Describe the solution you'd like**
so i want to know if there a way to reduce ragdoll trafic ,i see gmod wiki and set some entity flag ,but it doesn't work. maybe i use it in a wrong way . 
any suggestion will be aprreciated. thank you very much.

**Comment by TheNickSkater** [comment]
As far as I know ragdolls causing much Network traffic is a well known "problem" in gmod already, which is mostly caused by all the "complex parts" of a ragdoll, especially if they have many bones. I dont think you can really "fix" this yourself tbh. Maybe if you can manage to make ragdolls have no bones so they dont need to calculate that.

**Comment by swordjjjkkk** [comment]
i don't know the ralationship about model and bone, i see source code after ents.create("prop_ragdoll") only rag:SetModel(ply:GetModel()  seems relate with bone.  anyway, the situation is i provide a lot of model for players,  if i can make ragdoll have no bones , so i need make one  or i have to modify every model?

**Comment by swordjjjkkk** [comment]
so if it's no setting to reduce traffic ,i have an idea.  i can make an empty entity to replace dead body in severside ,and sync it pos to client.  in client side, create a ragdoll body only in client make sure the client body pos = server empty entity. it may reduce traffic , do you think it able to work ?
