### ISSUE TITLE
either Jackal or Detective spawns but never both

### ISSUE THREAD

**Issue by kaimuu** [TTT-2/TTT2#849]
v0.9.2b

At 5 players whenever you enable for a jackal and a detective to spawn only one of them spawns (the one on the left or bottom in the role layering setting) even when every other ULX setting is made to allow for both theoretically

Is there any way to have both Jackal and Detective roles at the same time?

**Comment by TimGoll** [comment]
Could you show what you've done in rolelayering?

**Comment by kaimuu** [comment]
Can't screenshot now but it used to be (default) that layer 0 was Detective and Layer 1 was Jackal and then we changed both to Layer 0 and if Jackal is on the left then it's always going to just pick the jackal and if it's on the right then it will always pick a detective.

**Comment by TimGoll** [comment]
Wait so your first issue is no issue at all. If both roles are on the same layer, only one of them is selected. So this is a feature. If you want both roles keep them unpooled or put them in separate layers.

But now you say that only the first role in a layer is selected? never the second?

**Comment by kaimuu** [comment]
Yes, they used to be on seperate layers but we changed it to find out if it would fix itself (which it didnt which would be intended going by your explanation). I'll test around later when I can to see if putting it on different layers again and playing around with some settings will fix it and I'll update.

Could've been an issue with the max_roles setting being less before it was changed to be on the same layer.

**Comment by kaimuu** [comment]
Alright so, even when creating two layers where one is Detective and the other is Jackal it will still only spawn either one and not both even when both are set to 100%. Lowering the Innocent percentage fixes this though and both are allowed to spawn.

So we found a solution but it doesn't seem to be working as intended at all.

**Comment by ZenBre4ker** [comment]
This is kinda intended. Other layers are only considered if there is enough general space.
First are always innocents and traitors independent of rolelayering and no matter the pct if min players is exceeded, at least one role gets assigned per layer.
Therefore I would set the innocent to 0, the traitors to 0.4 or similar and then jackal and dete on 0.2. And either keep them unlayered or both on separate layers.
Then you should get 1 inno, 2 traitor, 1 jackal and 1 dete with 5 players.

**Comment by kaimuu** [comment]
This just seems like such an unintuitive way of handling things to me. At that point you could basically just remove the innocent percentage so it always works the same way in my opinion. Don't really see a usecase for the innocent percentage if it works this way.

**Comment by ZenBre4ker** [comment]
The innocent percentage was for the old way, where you just say how many innocents there should be as a minimum, while every other unlayered role can be additional and random.
That would still make sense once you exceed your limited 5 player setup and get to a higher number, where there will be unlayered random roles again.

**Comment by TimGoll** [comment]
I see why it is unintuitive, but @ZenBre4ker is right as well. Maybe we come up with a better solution to this problem

**Comment by ZenBre4ker** [comment]
I guess we can close this, feel free to reopen if we didnt fix the problem. It seems like just a problem with setting up rolelayering.
