### ISSUE TITLE
Properly documented config vars

### ISSUE THREAD

**Issue by fgblomqvist** [TTT-2/TTT2#851]
**Is your feature request related to a problem? Please describe.**
I like to configure things the old-school way, in a cfg file. However, so far I've not been able to find the available cfg vars for TTT2, only the recommendation to install ULX, which I don't want.

**Describe the solution you'd like**
A proper page in the docs that documents all of them, just like the OG TTT.

**Comment by TimGoll** [comment]
see our docs: https://api-docs.ttt2.neoxult.de/createconvar/none

However we will move those settings with documentation to the F1 menu soon
