### ISSUE TITLE
Damage indicator shows when taking 0 damage

### ISSUE THREAD

**Issue by TaintedEnergy** [TTT-2/TTT2#856]
Version:
v0.9.2b

Issue description:
When the Jester shoots a player, that player's screen will turn red. This causes people to think they are taking damage and often kill the Jester.

Expected behaviour:
The Jester does not cause a player's screen to turn red when shooting them.

**Comment by ZenBre4ker** [comment]
I think this is valid. At least it makes sense. Gotta check the code.
