### ISSUE TITLE
spawn editor tool causes script errors

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/TTT2#904]
## Your version of TTT2 (mandatory)

- Workshop version from Steam

## Describe the bug (mandatory)

If you use "Start Spawn Edit" from the F1 menu under "Spawn Editor" from "Administration" and walk/fly around with the "Spawn Editor Tool" then you will get script errors in the client/server console.

This is the error:
[TTT2 (Base) - v0.10.2b] render.DrawSphere: Arguments #3 and/or #4 have invalid value!
  1. fn - gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua:322
   2. unknown - lua/ulib/shared/hook.lua:109

## Context (please provide as much as you can)

- Collection link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195

**Comment by ZenBre4ker** [comment]
Might be division by zero, is my guess.
https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua#L320

**Comment by TimGoll** [comment]
nope, it is that the arguments 3 and 4 of `render.DrawSphere` have to be in a certain range. However there is no documentation on this. So I guessed it has to be greater than one. But probably it has to be greater than 3 or so?

**Comment by ZenBre4ker** [comment]
But isnt (4 + whatever) always greater than 3 or so?

**Comment by TimGoll** [comment]
yes, but my suspicion was that the distance can be negative? But I have no idea. Maybe the minimum is 5. It is hard to test because I could not reproduce it and there is no documentation

**Comment by ZenBre4ker** [comment]
At least lua knows infinity
![grafik](https://user-images.githubusercontent.com/72046466/141976236-c433980b-e301-4d8a-9f38-ac0e09b82e7a.png)

**Comment by TimGoll** [comment]
maybe you're right

**Comment by ZenBre4ker** [comment]
Probably could limit the maxsteps to 50 or 100 anyways. As the quality can increase quite a lot for small distances 😄
Just need to see if gmod math can handle infinity. So max(inf, 50) is 50 ^^

**Comment by ZenBre4ker** [comment]
That could work:
![grafik](https://user-images.githubusercontent.com/72046466/141977480-6f03abf0-7ab2-4ce2-a971-811968fc3a92.png)

**Comment by TimGoll** [comment]
The go ahead and try it!
