### ISSUE TITLE
traitoshop/[role]shop bug

### ISSUE THREAD

**Issue by Plut021** [TTT-2/TTT2#941]
## Your version of TTT2 (mandatory)

TTT2 version: v0.11.3b

## Describe the bug (mandatory)

Buying a item in a shop, when you are already equipped with items from a class, sometimes  results in not getting the item but spending the credit

it happens especially when buying an item for an already occupied slot 

## To reproduce

in a game select a class which gives you so many items your inventory is counted as full then try to buy an item 
the credit will be charged but you wont receive an item

## Expected behaviour

either increase the inventory size or don't charge a credit for a not received weapon

## Context (please provide as much as you can)
this is the link to the collection I am using although some mods are deactivated because they are not working correctly anymore:
https://steamcommunity.com/sharedfiles/filedetails/?id=2103434125

this are most of the classes used one the server:
https://steamcommunity.com/sharedfiles/filedetails/?id=2106420823

**Comment by TimGoll** [comment]
You are using the better equipment menu? I'm surprised your game works at all. Please remove that addon and try again. The addonchecker should have thrown a warning about this addon.

**Comment by Plut021** [comment]
> You are using the better equipment menu? I'm surprised your game works at all. Please remove that addon and try again. The addonchecker should have thrown a warning about this addon.

ok the better equipment shop was cousing the problem
