### ISSUE TITLE
VC not working

### ISSUE THREAD

**Issue by TH3GAM3K1NG** [TTT-2/TTT2#953]
The vc button doesnt work, if I type +voicerecord into console I can talk. Please fix
![image](https://user-images.githubusercontent.com/49150797/144753131-7e0bb613-d448-4b16-8ffe-41dd454fe8d8.png)

**Comment by guilletj** [comment]
Same problem here. It also happens when using team voice chat.
Tried to run the gamemode without any addon and the problem persists.

**Comment by ZenBre4ker** [comment]
Thanks for confirming, will fix it with next update.

**Comment by saibotk** [comment]
Thank Gmod and its next update for this:

`Added +voicerecord to blocked console command list`

**Comment by TimGoll** [comment]
The fix is simple though: https://github.com/Facepunch/garrysmod/commit/ad636ea0569228b3656e72637a76570db488856c

It is just really shitty that they introduce the new function in the same update that they removed the old one. This is a pain to update because we have to release our update in the moment GMod is updated. This will cause so many problems with servers and clients that did not immidiately update.

Here you can see that they added this function in the coming update: https://docs.google.com/document/u/1/d/e/2PACX-1vTzEJEpdEje8e-FgsbyWGydu_Ez7p82MwOUPmRlUAAJ-KpkNJhHctyadZosfUYjVTz26KGip7bI7M9T/pub

I don't know why they do this, this is really bad practice. They should give us at least one update cycle time to update it.

**Comment by TimGoll** [comment]
I opened an issue to the GMod team as their breaking update is really bad practice and makes updating the game really hard.

**Comment by saibotk** [comment]
Oh wow i did. See that function but honestly for me functions in a permissions module are rather used to request permissions or ask if the user has something enabled. So I did not think that this would be the replacement function lol

**Comment by TimGoll** [comment]
yeah, the module name is a bit weird

**Comment by guilletj** [comment]
So for now switching to the non-beta branch would be a temporary fix for this?
Anyways this is really annoying since many people now uses the x86-64 beta for their clients.

I've never programmed in LUA before but it couldn't be that you can detect which branch the client is using and do different stuff with that? Sorry if this is a stupid question.

**Comment by TimGoll** [comment]
yes, this would fix it. And I 100% agree with you, this is why I opened the issue on the Facepunch GitHub (see above). We can't fix it right now because it is either borken for the beta users or the normal users. This is really shit update practice.

**Comment by guilletj** [comment]
Okay so messing around with the cl_voice.lua file I THINK I fixed it.
I've tested it with both branches, no errors for now but I'm not 100% sure if this is a good way to fix it.

Using what Kefta posted, I changed the voice enable and voice disable functions, replacing the "RunConsoleCommand()" with these conditional blocks:
```lua
if (isfunction(permissions.EnableVoiceChat)) then
    permissions.EnableVoiceChat( true )
else
    RunConsoleCommand("+voicerecord")
end
```

```lua
if (isfunction(permissions.EnableVoiceChat)) then
    permissions.EnableVoiceChat( false )
else
    RunConsoleCommand("-voicerecord")
end
```
I don't really know if this is going to blow up soon or later, but seems to work for now.

**Comment by TimGoll** [comment]
you're right, this would work indeed. It is still bad practive by Facepunch.

**Comment by guilletj** [comment]
Yeah, but as far as I know they've been doing things like that since ever soooooo... Well, guess we have to deal with it.

**Comment by TimGoll** [comment]
Could any of you test if my fix is working: https://github.com/TTT-2/TTT2/pull/954 Thanks a lot.

**Comment by Jonathan-Jackson** [comment]
@TimGoll apologies for my ignorance - is there an easy way to go about testing this? I have a few people I was intending to play this with tonight so we can test this fix, I assumed copying the changes into the lua on my local gmod and restarting would be enough (GarrysMod\garrysmod\gamemodes\terrortown\gamemode\cl_voice.lua), but appears to make no difference (again - sorry, I have very little knowledge with gmod)

**Comment by TimGoll** [comment]
no, put it on the server. And yes, the single file is enough. But you could also just put the whole TTT2 folder in the server's addons folder.

**Comment by corysimmonds** [comment]
I'm also a completely clueless with GMOD/ LUA. I completely replaced cl_voice.lua with the changes you made in the PR and tested in game with a friend (2 people in game). 

When you're innocent you can speak fine, no issues. When you're the traitor the voice doesn't transmit at all. The voice popup in the bottom right appears, but no voice is transmitted.

**Comment by TimGoll** [comment]
I had a similar issue. I couldn't see the voice overlay as a traitor. However I'm pretty unsure what broke it. Also I can't test if this is a new issue or not because the old GMod version no longer exists. Hm.

**Comment by TimGoll** [comment]
@corysimmonds I fixed it probably. Looks like it was a stupid copy paste error that I did not spot earlier. Please try it again.

**Comment by corysimmonds** [comment]
@TimGoll Thanks Tim. I've set line 82 to true and tested again (after closing down gmod and rehosting a server), but the issue still remains for the traitor.

**Comment by Jonathan-Jackson** [comment]
There's a comment over at: https://github.com/Facepunch/garrysmod-issues/issues/5037

> Traitor voice chat. And no there's no "modern" method: the game needs to be able to activate the microphone conditionally using a key not binded to +voicerecord.

Which seems possibly related? Again, apologies for ignorance - I am very much out of my normal depth.

**Comment by TimGoll** [comment]
this is the reason this whole thing got changed, I'm testing some things right now

**Comment by TimGoll** [comment]
Hm, Voicechat is working for me though:

traitor teamchat:
![image](https://user-images.githubusercontent.com/13639408/146253491-4ad40e1e-280e-4e7c-aaae-c730f4d83cde.png)

global chat:
![image](https://user-images.githubusercontent.com/13639408/146253631-c64531ea-8b82-41f4-84d2-e644a3665a13.png)

I can not verify that the voicechat is actually working. However the voicechat UI is now displayed as it should.

**Comment by corysimmonds** [comment]
The UI displays for the traitor, but doesn't actually transmit voice when I tried with a friend. We both became the traitor to test this, and only when innocent can the voice transmit (with the UI showing too).

Again the only thing I've changed is the cl_voice.lua file, completely replacing it with the changes you made in the PR - with my limited knowledge I'm not sure if that's all required to do?

**Comment by TimGoll** [comment]
that should be everything. I guess I have to test it with someone

**Comment by corysimmonds** [comment]
@TimGoll If you need to test with someone you can test with my friend, he's just added you on steam, he's the guy with aviator sunglasses on his profile picture.

**Comment by TimGoll** [comment]
Update: Even with a spy enabled it works. Could you send us your collection?
