### ISSUE TITLE
Make vanilla weapons obvious in the equipment editor

### ISSUE THREAD

**Issue by wgetJane** [TTT-2/TTT2#964]
example of how this can be confusing:
![](https://cdn.discordapp.com/attachments/547119387392475136/965578968868728852/unknown.png)

vanilla weapons in the editor could be named like "_MAC10 (Built-in)_" or have a little icon or border that signifies it

**Comment by TimGoll** [comment]
I had to close/reopen this to link it to a PR. Don't ask me why
