### ISSUE TITLE
Add support for old targetid hint system

### ISSUE THREAD

**Issue by wgetJane** [TTT-2/TTT2#965]
Currently, hovering over entities that have a `ENT.TargetIDHint` table will not show a targetid at all

Here's how the values of the table are used by vanilla TTT (name, hint, fmt)
https://github.com/Facepunch/garrysmod/blob/5aeba7596237c2af72108867cf0565b7f263e23d/garrysmod/gamemodes/terrortown/gamemode/cl_targetid.lua#L323

Note that if this is implemented, this should be removed from the c4 entity (leftover unused code):
https://github.com/TTT-2/TTT2/blob/55760bcadb45f6c2618da2f4b0a4579bda2f893f/gamemodes/terrortown/entities/entities/ttt_c4/shared.lua#L27

**Comment by wgetJane** [comment]
Seems pretty simple to implement since the targetid title can be derived from the "name" value, while the subtitle can be derived from the "hint" and "fmt" function if present

Not sure what the icon should be though, doesn't seem like there's a "generic" icon, maybe it shouldn't have an icon at all

**Comment by EntranceJew** [comment]
this appears to be implemented? 

https://github.com/TTT-2/TTT2/blob/0c245a6e89c8020faff316a6fe99d61fd338760c/lua/ttt2/libraries/targetid.lua#L448-L456

Maybe I can't read very well.
